00001 *      LAST MAINTENANCE TIME: 13.45.48  DATE: 04/04/88            09/03/03
00002 * GENERATED BY STRUCTURE(S) CODE GENERATOR V2.0                   ELELPPML
00003 *     ON 88/04/04 AT 13:45:20.41                                     LV002
00004 * STRUCTURE(S) MEMBER ELELPPMLPW - LEVEL 025 AS OF 04/04/88       ELELPPML
00005 * FROM PANLIB R360059.STRUCTPL.PANLIB                             ELELPPML
00006 *   ELS PRINTER DRIVER FOR CICS                                   ELELPPML
00007  IDENTIFICATION DIVISION.                                         ELELPPML
00008                                                                   ELELPPML
00009  PROGRAM-ID.         ELELPPML.                                    ELELPPML
00010                                                                   ELELPPML
00011  AUTHOR.             EDWARD G LISS                                ELELPPML
00012                                                                   ELELPPML
00013  INSTALLATION.       HEALTH CARE SERVICE CORPORATION              ELELPPML
00014                      A MUTUAL LEGAL RESERVE COMPANY               ELELPPML
00015                      BLUE CROSS/BLUE SHIELD OF ILLINOIS           ELELPPML
00016                      233 N. MICHIGAN AVE                          ELELPPML
00017                      CHICAGO, ILLINOIS 60601                      ELELPPML
00018                                                                   ELELPPML
00019  DATE-WRITTEN.       11-JUN-1987.                                 ELELPPML
00020                                                                   ELELPPML
00021  DATE-COMPILED.                                                   ELELPPML
00022                                                                   ELELPPML
00023  SECURITY.           COPYRIGHT 1987,                              ELELPPML
00024                      HEALTH CARE SERVICE CORPORATION              ELELPPML
00025      SKIP3                                                        ELELPPML
00026  TITLE 'ELS PRINTER DRIVER FOR CICS                       '.      ELELPPML
00027  ENVIRONMENT DIVISION.                                            ELELPPML
00028                                                                   ELELPPML
00029  CONFIGURATION SECTION.                                           ELELPPML
00030  SOURCE-COMPUTER.    IBM-3033.                                    ELELPPML
00031  OBJECT-COMPUTER.    IBM-3033.                                    ELELPPML
00032      EJECT                                                        ELELPPML
00033 ******************************************************************ELELPPML
00034 *                                                                *ELELPPML
00035 *    PROGRAM:    ELELPPML                                        *ELELPPML
00036 *    DATE:       11-JUN-1987                                     *ELELPPML
00037 *    AUTHOR:     EDWARD G LISS                                   *ELELPPML
00038 *    FUNCTION:                                                   *ELELPPML
00039 *       THIS MODULE WILL PRINT THE CONTENTS OF A TEMP STORAGE    *ELELPPML
00040 *       QUEUE AS A 'BACKGROUND' TASK.                            *ELELPPML
00041 *                                                                *ELELPPML
00042 *    NOTES:                                                      *ELELPPML
00043 *       THIS PROGRAM IS STARTED BY THE REQUESTOR IN THE          *ELELPPML
00044 *       TERMINAL OWNER REGION.                                   *ELELPPML
00045 *                                                                *ELELPPML
00046 *                                                                *ELELPPML
00047 ******************************************************************ELELPPML
00048 *                                                                *ELELPPML
00049 *                      MAINTENANCE HISTORY                       *ELELPPML
00050 *                                                                *ELELPPML
00051 *  MOD     DATE     BY  DRPT                ACTION               *ELELPPML
00052 * ----- ----------- --- ----- ---------------------------------- *ELELPPML
00053 * 01.00 11-JUN-1987 EGL       CREATED                            *ELELPPML
00054 * 01.01 24-FEB-1988 EGL       ADDED CODE TO PRINT THE APPLID     *ELELPPML
00055 *                             AND SYSID FIELDS                   *ELELPPML
00056 * 01.02 01-APR-1988 EGL       ADDED CODE TO SEND PAGE IN MORE    *ELELPPML
00057 *                             ONE SEND TO AVOID PRINTER BUFFER   *ELELPPML
00058 *                             OVERFLOWS, THUS RESULTING IN       *ELELPPML
00059 *                             TRUNCATED AND WIERD OUTPUT.        *ELELPPML
00060 *       12-AUG-2003 AKK       MOVE TO QE TO GEN FOR COMPILE      *ELELPPML
00061 *                             ORDER TEST                         *ELELPPML
00062 ******************************************************************ELELPPML
00063      EJECT                                                        ELELPPML
00064  DATA DIVISION.                                                   ELELPPML
00065                                                                   ELELPPML
00066  WORKING-STORAGE SECTION.                                         ELELPPML
00067                                                                   ELELPPML
00068  01  MISC-WORKING-STORAGE.                                        ELELPPML
00069      05  PPB-POINTER             POINTER.                         ELELPPML
00070      05  PQ-POINTER              POINTER.                         ELELPPML
00071      05  PPB-LENGTH              PICTURE S9(4) COMP.              ELELPPML
00072      05  PQ-LENGTH               PICTURE S9(4) COMP.              ELELPPML
00073      05  WS-A-SPACE              PICTURE X     VALUE SPACE.       ELELPPML
00074      05  WS-ITEM-1               PICTURE S9(4) COMP VALUE 1.      ELELPPML
00075      05  WS-LINE-SUB             PICTURE S9(4) COMP.              ELELPPML
00076      05  WS-LINE-COUNT           PICTURE S9(4) COMP.              ELELPPML
00077      05  WS-LINE-LENGTH          PICTURE S9(8) COMP.              ELELPPML
00078      05  WS-MOVE-LENGTH          PICTURE S9(8) COMP.              ELELPPML
00079      05  WS-PRINT-SUB            PICTURE S9(4) COMP.              ELELPPML
00080      05  WS-TIME-EDIT            PICTURE 99B99B99.                ELELPPML
00081      05  FILLER    REDEFINES WS-TIME-EDIT.                        ELELPPML
00082          10  WS-TIME-HH          PICTURE 99.                      ELELPPML
00083          10  FILLER              PICTURE X.                       ELELPPML
00084          10  WS-TIME-MM          PICTURE 99.                      ELELPPML
00085          10  FILLER              PICTURE X.                       ELELPPML
00086          10  WS-TIME-SS          PICTURE 99.                      ELELPPML
00087      05  WS-TEXT-WORK-AREA.                                       ELELPPML
00088          10  FILLER              PICTURE X(12) VALUE SPACES.      ELELPPML
00089          10  WS-TEXT-WORK-AREA-LINE                               ELELPPML
00090                                  PICTURE X(79).                   ELELPPML
00091      05  FILLER   REDEFINES WS-TEXT-WORK-AREA.                    ELELPPML
00092          10  WS-TEXT-WORK-CHAR   OCCURS 91 TIMES                  ELELPPML
00093                                  PICTURE X.                       ELELPPML
00094      EJECT                                                        ELELPPML
00095  01  WS-PRINT-LINES.                                              ELELPPML
00096      05  WS-HEADER-LINES.                                         ELELPPML
00097 ********   HEADER-LINE-1.                                         ELELPPML
00098          10  FILLER-MARGIN       PICTURE X(12) VALUE SPACES.      ELELPPML
00099          10  FILLER              PICTURE X(24) VALUE SPACES.      ELELPPML
00100          10  FILLER              PICTURE X(23) VALUE              ELELPPML
00101              'E. L. S. PRINT REQUEST '.                           ELELPPML
00102          10  WS-HDR-REQ-ID       PICTURE X(8)  VALUE ALL '*'.     ELELPPML
00103          10  WS-HDR-EOL-1        PICTURE X.                       ELELPPML
00104 ********   HEADER-LINE-2.                                         ELELPPML
00105          10  FILLER-MARGIN       PICTURE X(12) VALUE SPACES.      ELELPPML
00106          10  FILLER              PICTURE X(8)  VALUE SPACES.      ELELPPML
00107          10  FILLER              PICTURE X(20) VALUE              ELELPPML
00108              'REQUESTED IN APPLID '.                              ELELPPML
00109          10  WS-REQ-APPLID       PICTURE X(8).                    ELELPPML
00110          10  FILLER              PICTURE X(7)  VALUE ' SYSID '.   ELELPPML
00111          10  WS-REQ-SYSID        PICTURE X(4).                    ELELPPML
00112          10  FILLER              PICTURE X(4)  VALUE ' ON '.      ELELPPML
00113          10  WS-REQ-HDR-DATE     PICTURE Z9/99/99.                ELELPPML
00114          10  FILLER              PICTURE X(4)  VALUE ' AT '.      ELELPPML
00115          10  WS-REQ-HDR-HOUR     PICTURE Z9.                      ELELPPML
00116          10  FILLER              PICTURE X     VALUE ':'.         ELELPPML
00117          10  WS-REQ-HDR-MIN      PICTURE 99.                      ELELPPML
00118          10  FILLER              PICTURE X     VALUE ':'.         ELELPPML
00119          10  WS-REQ-HDR-SEC      PICTURE 99.                      ELELPPML
00120          10  WS-HDR-EOL-2        PICTURE X.                       ELELPPML
00121 ********   HEADER-LINE-3.                                         ELELPPML
00122          10  FILLER-MARGIN       PICTURE X(12) VALUE SPACES.      ELELPPML
00123          10  FILLER              PICTURE X(8)  VALUE SPACES.      ELELPPML
00124          10  FILLER              PICTURE X(20) VALUE              ELELPPML
00125              'PRINTED FROM APPLID '.                              ELELPPML
00126          10  WS-PRT-APPLID       PICTURE X(8).                    ELELPPML
00127          10  FILLER              PICTURE X(7)  VALUE ' SYSID '.   ELELPPML
00128          10  WS-PRT-SYSID        PICTURE X(4).                    ELELPPML
00129          10  FILLER              PICTURE X(4)  VALUE ' ON '.      ELELPPML
00130          10  WS-PRT-HDR-DATE     PICTURE Z9/99/99.                ELELPPML
00131          10  FILLER              PICTURE X(4)  VALUE ' AT '.      ELELPPML
00132          10  WS-PRT-HDR-HOUR     PICTURE Z9.                      ELELPPML
00133          10  FILLER              PICTURE X     VALUE ':'.         ELELPPML
00134          10  WS-PRT-HDR-MIN      PICTURE 99.                      ELELPPML
00135          10  FILLER              PICTURE X     VALUE ':'.         ELELPPML
00136          10  WS-PRT-HDR-SEC      PICTURE 99.                      ELELPPML
00137          10  WS-HDR-EOL-3        PICTURE X.                       ELELPPML
00138          10  WS-HDR-EOL-4        PICTURE X.                       ELELPPML
00139 ******** WS-HEADER-LINE-4 ********                                ELELPPML
00140          10  FILLER              PICTURE X(12) VALUE SPACES.      ELELPPML
00141          10  FILLER              PICTURE X(25) VALUE 'ELPP'.      ELELPPML
00142          10  FILLER              PICTURE X(24) VALUE              ELELPPML
00143              'ENGLISH CONTRACT INQURIY'.                          ELELPPML
00144          10  FILLER              PICTURE X(14) VALUE SPACES.      ELELPPML
00145          10  FILLER              PICTURE X(6)  VALUE ' PAGE '.    ELELPPML
00146          10  WS-HDR-PAGE-NO      PICTURE 999B.                    ELELPPML
00147          10  WS-HDR-PAGE-STAT    PICTURE X(4)  VALUE SPACES.      ELELPPML
00148              88  WS-HDR-MORE                   VALUE 'MORE'.      ELELPPML
00149              88  WS-HDR-LAST                   VALUE 'LAST'.      ELELPPML
00150          10  WS-HDR-EOL-5        PICTURE X.                       ELELPPML
00151      05  WS-TRAILER-LINE-1.                                       ELELPPML
00152          10  FILLER              PICTURE X(12) VALUE SPACES.      ELELPPML
00153          10  FILLER              PICTURE X(50) VALUE              ELELPPML
00154              '<PF2>=PRINT ALL <PF3-6>=INQ PGM <PF7/8>=PREV/NEXT '.ELELPPML
00155          10  FILLER              PICTURE X(20) VALUE              ELELPPML
00156              '<PF10/11>=FIRST/LAST'.                              ELELPPML
00157          10  WS-TRLR-EOL-1       PICTURE X.                       ELELPPML
00158 *                                                                 ELELPPML
00159 *  A PRINT WORK AREA OF 1900 BYTES WAS USED, BASED ON THE         ELELPPML
00160 *  FOLLOWING LOGIC:                                               ELELPPML
00161 *      1800 BYTES FOR HOLDING PARTIAL PAGES      = 1800           ELELPPML
00162 *       100 BYTES FOR MARGINAL OVERFLOW          =  100           ELELPPML
00163 *              TOTAL                             = 3000           ELELPPML
00164 *                                                                 ELELPPML
00165  01  WS-PRINT-AREA               PICTURE X(1900).                 ELELPPML
00166  01  FILLER               REDEFINES WS-PRINT-AREA.                ELELPPML
00167      05  WS-PRINT-BYTES          OCCURS 1900 TIMES                ELELPPML
00168                                  PICTURE X.                       ELELPPML
00169      EJECT                                                        ELELPPML
00170 *                                                                 ELELPPML
00171 *    DATE CONVERSION TABLES.                                      ELELPPML
00172 *                                                                 ELELPPML
00173  01  WS-DATE-CONV-AREA.                                           ELELPPML
00174      05  WS-JULIAN-DATE-TABLE.                                    ELELPPML
00175          10  FILLER              PICTURE S9(4) COMP VALUE +1.     ELELPPML
00176          10  FILLER              PICTURE S9(4) COMP VALUE +32.    ELELPPML
00177          10  FILLER              PICTURE S9(4) COMP VALUE +60.    ELELPPML
00178          10  FILLER              PICTURE S9(4) COMP VALUE +91.    ELELPPML
00179          10  FILLER              PICTURE S9(4) COMP VALUE +121.   ELELPPML
00180          10  FILLER              PICTURE S9(4) COMP VALUE +152.   ELELPPML
00181          10  FILLER              PICTURE S9(4) COMP VALUE +182.   ELELPPML
00182          10  FILLER              PICTURE S9(4) COMP VALUE +213.   ELELPPML
00183          10  FILLER              PICTURE S9(4) COMP VALUE +244.   ELELPPML
00184          10  FILLER              PICTURE S9(4) COMP VALUE +274.   ELELPPML
00185          10  FILLER              PICTURE S9(4) COMP VALUE +305.   ELELPPML
00186          10  FILLER              PICTURE S9(4) COMP VALUE +335.   ELELPPML
00187          10  FILLER              PICTURE S9(4) COMP VALUE +366.   ELELPPML
00188      05  WS-DATE-TABLE  REDEFINES WS-JULIAN-DATE-TABLE            ELELPPML
00189                                  OCCURS 13 TIMES                  ELELPPML
00190                                  INDEXED BY WS-DATE-IDX.          ELELPPML
00191          10  WS-DATE-ITEM        PICTURE S9(4) COMP.              ELELPPML
00192      05  WS-DATE-SEARCH          PICTURE S9(4) COMP.              ELELPPML
00193      05  WS-GREG-DATE            PICTURE 9(6).                    ELELPPML
00194      05  WS-GREG-WORK   REDEFINES WS-GREG-DATE.                   ELELPPML
00195          10  WS-GREG-MM          PICTURE 99.                      ELELPPML
00196          10  WS-GREG-DD          PICTURE 99.                      ELELPPML
00197          10  WS-GREG-YY          PICTURE 99.                      ELELPPML
00198      05  WS-JULIAN-DATE          PICTURE 9(5).                    ELELPPML
00199      05  WS-JULIAN-WORK REDEFINES WS-JULIAN-DATE.                 ELELPPML
00200          10  WS-JULIAN-YY        PICTURE 99.                      ELELPPML
00201          10  WS-JULIAN-DDD       PICTURE 999.                     ELELPPML
00202      05  WS-LEAP-YEAR-IND        PICTURE S9(4) COMP.              ELELPPML
00203          88  WS-LEAP-YEAR             VALUE ZERO.                 ELELPPML
00204      EJECT                                                        ELELPPML
00205      COPY DFHBMSCA.                                               ELELPPML
00206      EJECT                                                        ELELPPML
00207  LINKAGE SECTION.                                                 ELELPPML
00208  01  DFHCOMMAREA.                                                 ELELPPML
00209      05  FILLER                  PICTURE X(1).                    ELELPPML
00210      EJECT                                                        ELELPPML
00211      COPY ELSPRPAC.                                               ELELPPML
00212      EJECT                                                        ELELPPML
00213      COPY ELSPAGQC.                                               ELELPPML
00214  PROCEDURE DIVISION.                                              ELELPPML
00215 ************************************************************      ELELPPML
00216 *                                                          *      ELELPPML
00217 *                    PROCEDURE DIVISION                    *      ELELPPML
00218 *                                                          *      ELELPPML
00219 ************************************************************      ELELPPML
00220                                                                   ELELPPML
00221                                                                   ELELPPML
00222 ************************************************************      ELELPPML
00223 *                                                          *      ELELPPML
00224 *        PRINT ELS OUTPUT                                  *      ELELPPML
00225 *                                                          *      ELELPPML
00226 ************************************************************      ELELPPML
00227  00001-PRINT-ELS-OUTPUT.                                          ELELPPML
00228      PERFORM 00005-INITIALIZATION.                                ELELPPML
00229      SKIP1                                                        ELELPPML
00230 *                                                          *      ELELPPML
00231 *        PROCESSING                                        *      ELELPPML
00232 *                                                          *      ELELPPML
00233          PERFORM 00092-GET-FIRST-PAGE-TO-PROCES                   ELELPPML
00234          PERFORM 00102-PROCESS-ALL-PAGES                          ELELPPML
00235          UNTIL WS-HDR-LAST.                                       ELELPPML
00236      SKIP1                                                        ELELPPML
00237      PERFORM 00196-TERMINATION.                                   ELELPPML
00238                                                                   ELELPPML
00239                                                                   ELELPPML
00240 ************************************************************      ELELPPML
00241 *                                                          *      ELELPPML
00242 *        INITIALIZATION                                    *      ELELPPML
00243 *                                                          *      ELELPPML
00244 ************************************************************      ELELPPML
00245  00005-INITIALIZATION.                                            ELELPPML
00246      PERFORM 00009-GET-THE-PARAMETERS-FROMX.                      ELELPPML
00247      PERFORM 00017-INITIALIZE-PAGE-HEADINGS.                      ELELPPML
00248      SKIP1                                                        ELELPPML
00249 *                                                          *      ELELPPML
00250 *        ESTABLISH ERROR HANDLING                          *      ELELPPML
00251 *                                                          *      ELELPPML
00252          EXEC CICS IGNORE CONDITION                               ELELPPML
00253                ITEMERR                                            ELELPPML
00254                QIDERR                                             ELELPPML
00255                SYSIDERR                                           ELELPPML
00256          END-EXEC.                                                ELELPPML
00257      SKIP1                                                        ELELPPML
00258                                                                   ELELPPML
00259                                                                   ELELPPML
00260 ************************************************************      ELELPPML
00261 *                                                          *      ELELPPML
00262 *        GET THE PARAMETERS FROM CICS                      *      ELELPPML
00263 *                                                          *      ELELPPML
00264 ************************************************************      ELELPPML
00265  00009-GET-THE-PARAMETERS-FROMX.                                  ELELPPML
00266      EXEC CICS RETRIEVE                                           ELELPPML
00267                SET(PPB-POINTER)                                   ELELPPML
00268                LENGTH(PPB-LENGTH)                                 ELELPPML
00269          END-EXEC.                                                ELELPPML
00270      IF PPB-LENGTH NOT = LENGTH OF PPB-PRINT-PARAMETER-BLOCK      ELELPPML
00271          PERFORM 00196-TERMINATION.                               ELELPPML
00272      SET ADDRESS OF PPB-PRINT-PARAMETER-BLOCK                     ELELPPML
00273          TO PPB-POINTER.                                          ELELPPML
00274                                                                   ELELPPML
00275                                                                   ELELPPML
00276 ************************************************************      ELELPPML
00277 *                                                          *      ELELPPML
00278 *        INITIALIZE PAGE HEADINGS                          *      ELELPPML
00279 *                                                          *      ELELPPML
00280 ************************************************************      ELELPPML
00281  00017-INITIALIZE-PAGE-HEADINGS.                                  ELELPPML
00282      SKIP1                                                        ELELPPML
00283 *                                                          *      ELELPPML
00284 *        FORMAT PARM DATE                                  *      ELELPPML
00285 *                                                          *      ELELPPML
00286          MOVE PPB-TRAN-DATE TO WS-JULIAN-DATE                     ELELPPML
00287          PERFORM 00032-CONVERT-JULIAN-DATE-TO-G                   ELELPPML
00288          MOVE WS-GREG-DATE TO WS-REQ-HDR-DATE.                    ELELPPML
00289      SKIP1                                                        ELELPPML
00290      SKIP1                                                        ELELPPML
00291 *                                                          *      ELELPPML
00292 *        FORMAT PARM TIME                                  *      ELELPPML
00293 *                                                          *      ELELPPML
00294          MOVE PPB-TRAN-TIME  TO  WS-TIME-EDIT                     ELELPPML
00295          MOVE WS-TIME-HH     TO  WS-REQ-HDR-HOUR                  ELELPPML
00296          MOVE WS-TIME-MM     TO  WS-REQ-HDR-MIN                   ELELPPML
00297          MOVE WS-TIME-SS     TO  WS-REQ-HDR-SEC.                  ELELPPML
00298      SKIP1                                                        ELELPPML
00299      SKIP1                                                        ELELPPML
00300 *                                                          *      ELELPPML
00301 *        FORMAT CURRENT DATE                               *      ELELPPML
00302 *                                                          *      ELELPPML
00303          MOVE EIBDATE TO WS-JULIAN-DATE                           ELELPPML
00304          PERFORM 00032-CONVERT-JULIAN-DATE-TO-G                   ELELPPML
00305          MOVE WS-GREG-DATE TO WS-PRT-HDR-DATE.                    ELELPPML
00306      SKIP1                                                        ELELPPML
00307      SKIP1                                                        ELELPPML
00308 *                                                          *      ELELPPML
00309 *        FORMAT CURRENT TIME                               *      ELELPPML
00310 *                                                          *      ELELPPML
00311          MOVE EIBTIME        TO  WS-TIME-EDIT                     ELELPPML
00312          MOVE WS-TIME-HH     TO  WS-PRT-HDR-HOUR                  ELELPPML
00313          MOVE WS-TIME-MM     TO  WS-PRT-HDR-MIN                   ELELPPML
00314          MOVE WS-TIME-SS     TO  WS-PRT-HDR-SEC.                  ELELPPML
00315      SKIP1                                                        ELELPPML
00316      SKIP1                                                        ELELPPML
00317 *                                                          *      ELELPPML
00318 *        MOVE REGION IDENTIFICATION                        *      ELELPPML
00319 *                                                          *      ELELPPML
00320          MOVE PPB-TSQ-NAME     TO  WS-HDR-REQ-ID                  ELELPPML
00321          MOVE PPB-OWNER-APPLID TO WS-REQ-APPLID                   ELELPPML
00322          MOVE PPB-OWNER-SYSID  TO WS-REQ-SYSID                    ELELPPML
00323          EXEC CICS ASSIGN                                         ELELPPML
00324              APPLID(WS-PRT-APPLID)                                ELELPPML
00325          END-EXEC                                                 ELELPPML
00326          EXEC CICS ASSIGN                                         ELELPPML
00327              SYSID(WS-PRT-SYSID)                                  ELELPPML
00328          END-EXEC.                                                ELELPPML
00329      SKIP1                                                        ELELPPML
00330      SKIP1                                                        ELELPPML
00331 *                                                          *      ELELPPML
00332 *        MOVE END OF LINE CHARACTER                        *      ELELPPML
00333 *                                                          *      ELELPPML
00334          MOVE DFHBMPNL       TO  WS-HDR-EOL-1                     ELELPPML
00335                              WS-HDR-EOL-2                         ELELPPML
00336                              WS-HDR-EOL-3                         ELELPPML
00337                              WS-HDR-EOL-4                         ELELPPML
00338                              WS-HDR-EOL-5                         ELELPPML
00339                              WS-TRLR-EOL-1.                       ELELPPML
00340      SKIP1                                                        ELELPPML
00341                                                                   ELELPPML
00342                                                                   ELELPPML
00343 ************************************************************      ELELPPML
00344 *                                                          *      ELELPPML
00345 *        CONVERT JULIAN DATE TO GREGORIAN DATE             *      ELELPPML
00346 *                                                          *      ELELPPML
00347 ************************************************************      ELELPPML
00348  00032-CONVERT-JULIAN-DATE-TO-G.                                  ELELPPML
00349      PERFORM 00035-JULIAN-DATE-TO-GREGORIAN.                      ELELPPML
00350      SKIP1                                                        ELELPPML
00351 *                                                          *      ELELPPML
00352 *        JULIAN DATE TO GREGORIAN DATE CONVERSION          *      ELELPPML
00353 *                                                          *      ELELPPML
00354          SET WS-DATE-IDX TO 1                                     ELELPPML
00355          SEARCH WS-DATE-TABLE VARYING WS-DATE-IDX                 ELELPPML
00356          AT END                                                   ELELPPML
00357              MOVE ZEROS TO WS-GREG-DD                             ELELPPML
00358                            WS-GREG-MM                             ELELPPML
00359          WHEN WS-DATE-SEARCH < WS-DATE-ITEM (WS-DATE-IDX)         ELELPPML
00360              SET WS-DATE-IDX DOWN BY 1                            ELELPPML
00361              COMPUTE WS-GREG-DD = WS-DATE-SEARCH -                ELELPPML
00362                                       WS-DATE-ITEM (WS-DATE-IDX)  ELELPPML
00363          + 1                                                      ELELPPML
00364              SET WS-GREG-MM  TO  WS-DATE-IDX                      ELELPPML
00365         END-SEARCH.                                               ELELPPML
00366      SKIP1                                                        ELELPPML
00367                                                                   ELELPPML
00368                                                                   ELELPPML
00369 ************************************************************      ELELPPML
00370 *                                                          *      ELELPPML
00371 *        JULIAN DATE TO GREGORIAN DATE INITIALIZATION      *      ELELPPML
00372 *                                                          *      ELELPPML
00373 ************************************************************      ELELPPML
00374  00035-JULIAN-DATE-TO-GREGORIAN.                                  ELELPPML
00375      DIVIDE 4 INTO WS-JULIAN-YY GIVING WS-DATE-SEARCH             ELELPPML
00376               REMAINDER WS-LEAP-YEAR-IND                          ELELPPML
00377         END-DIVIDE.                                               ELELPPML
00378      MOVE WS-JULIAN-YY  TO WS-GREG-YY.                            ELELPPML
00379      MOVE WS-JULIAN-DDD TO WS-DATE-SEARCH.                        ELELPPML
00380      IF WS-LEAP-YEAR AND WS-DATE-SEARCH > 59                      ELELPPML
00381          PERFORM 00042-ADJUST-FOR-LEAP-YEAR.                      ELELPPML
00382                                                                   ELELPPML
00383                                                                   ELELPPML
00384 ************************************************************      ELELPPML
00385 *                                                          *      ELELPPML
00386 *        ADJUST FOR LEAP YEAR                              *      ELELPPML
00387 *                                                          *      ELELPPML
00388 ************************************************************      ELELPPML
00389  00042-ADJUST-FOR-LEAP-YEAR.                                      ELELPPML
00390      SUBTRACT 1 FROM WS-DATE-SEARCH.                              ELELPPML
00391                                                                   ELELPPML
00392                                                                   ELELPPML
00393 ************************************************************      ELELPPML
00394 *                                                          *      ELELPPML
00395 *        GET FIRST PAGE TO PROCESS                         *      ELELPPML
00396 *                                                          *      ELELPPML
00397 ************************************************************      ELELPPML
00398  00092-GET-FIRST-PAGE-TO-PROCES.                                  ELELPPML
00399      EXEC CICS READQ TS                                           ELELPPML
00400                QUEUE(PPB-TSQ-NAME)                                ELELPPML
00401                SET(PQ-POINTER)                                    ELELPPML
00402                LENGTH(PQ-LENGTH)                                  ELELPPML
00403                ITEM(WS-ITEM-1)                                    ELELPPML
00404                SYSID(PPB-OWNER-SYSID)                             ELELPPML
00405          END-EXEC.                                                ELELPPML
00406      IF EIBRCODE NOT = LOW-VALUES                                 ELELPPML
00407          PERFORM 00196-TERMINATION.                               ELELPPML
00408      SET ADDRESS OF PQ-PAGE-QUEUE TO PQ-POINTER.                  ELELPPML
00409                                                                   ELELPPML
00410                                                                   ELELPPML
00411 ************************************************************      ELELPPML
00412 *                                                          *      ELELPPML
00413 *        PROCESS ALL PAGES                                 *      ELELPPML
00414 *                                                          *      ELELPPML
00415 ************************************************************      ELELPPML
00416  00102-PROCESS-ALL-PAGES.                                         ELELPPML
00417      PERFORM 00105-PROCESS-A-PAGE.                                ELELPPML
00418      PERFORM 00162-GET-NEXT-PAGE-TO-PROCESS.                      ELELPPML
00419                                                                   ELELPPML
00420                                                                   ELELPPML
00421 ************************************************************      ELELPPML
00422 *                                                          *      ELELPPML
00423 *        PROCESS A PAGE                                    *      ELELPPML
00424 *                                                          *      ELELPPML
00425 ************************************************************      ELELPPML
00426  00105-PROCESS-A-PAGE.                                            ELELPPML
00427      PERFORM 00109-START-A-NEW-PAGE.                              ELELPPML
00428      PERFORM 00131-MOVE-THE-DETAIL-LINES                          ELELPPML
00429          VARYING WS-LINE-SUB FROM 1 BY 1                          ELELPPML
00430                   UNTIL WS-LINE-SUB > PQ-OCCURRENCE-COUNT.        ELELPPML
00431      PERFORM 00147-PRINT-THE-PAGE.                                ELELPPML
00432                                                                   ELELPPML
00433                                                                   ELELPPML
00434 ************************************************************      ELELPPML
00435 *                                                          *      ELELPPML
00436 *        START A NEW PAGE                                  *      ELELPPML
00437 *                                                          *      ELELPPML
00438 ************************************************************      ELELPPML
00439  00109-START-A-NEW-PAGE.                                          ELELPPML
00440      MOVE SPACES TO WS-PRINT-AREA.                                ELELPPML
00441      MOVE 1 TO WS-PRINT-SUB.                                      ELELPPML
00442      PERFORM 00114-FORMAT-VARIABLE-PAGE-HEA.                      ELELPPML
00443      SKIP1                                                        ELELPPML
00444 *                                                          *      ELELPPML
00445 *        MOVE PAGE HEADINGS                                *      ELELPPML
00446 *                                                          *      ELELPPML
00447          MOVE LENGTH OF WS-HEADER-LINES  TO WS-MOVE-LENGTH        ELELPPML
00448          CALL 'ELUMVCL' USING WS-HEADER-LINES                     ELELPPML
00449                           WS-MOVE-LENGTH                          ELELPPML
00450                           WS-PRINT-BYTES (WS-PRINT-SUB)           ELELPPML
00451                           WS-MOVE-LENGTH                          ELELPPML
00452                           WS-A-SPACE                              ELELPPML
00453          ADD WS-MOVE-LENGTH TO WS-PRINT-SUB                       ELELPPML
00454          MOVE 5 TO WS-LINE-COUNT.                                 ELELPPML
00455      SKIP1                                                        ELELPPML
00456                                                                   ELELPPML
00457                                                                   ELELPPML
00458 ************************************************************      ELELPPML
00459 *                                                          *      ELELPPML
00460 *        FORMAT VARIABLE PAGE HEADINGS                     *      ELELPPML
00461 *                                                          *      ELELPPML
00462 ************************************************************      ELELPPML
00463  00114-FORMAT-VARIABLE-PAGE-HEA.                                  ELELPPML
00464      MOVE PQ-PAGE-NO  TO  WS-HDR-PAGE-NO.                         ELELPPML
00465      IF PQ-MORE-RECORDS                                           ELELPPML
00466          PERFORM 00118-SET-MORE-PAGES                             ELELPPML
00467      SKIP1                                                        ELELPPML
00468 *                                                          *      ELELPPML
00469 *        SET LAST PAGE                                     *      ELELPPML
00470 *                                                          *      ELELPPML
00471      ELSE                                                         ELELPPML
00472          SET WS-HDR-LAST TO TRUE.                                 ELELPPML
00473      SKIP1                                                        ELELPPML
00474                                                                   ELELPPML
00475                                                                   ELELPPML
00476 ************************************************************      ELELPPML
00477 *                                                          *      ELELPPML
00478 *        SET MORE PAGES                                    *      ELELPPML
00479 *                                                          *      ELELPPML
00480 ************************************************************      ELELPPML
00481  00118-SET-MORE-PAGES.                                            ELELPPML
00482      SET WS-HDR-MORE TO TRUE.                                     ELELPPML
00483                                                                   ELELPPML
00484                                                                   ELELPPML
00485 ************************************************************      ELELPPML
00486 *                                                          *      ELELPPML
00487 *        MOVE THE DETAIL LINES                             *      ELELPPML
00488 *                                                          *      ELELPPML
00489 ************************************************************      ELELPPML
00490  00131-MOVE-THE-DETAIL-LINES.                                     ELELPPML
00491      MOVE PQ-PAGE-LINE (WS-LINE-SUB) TO WS-TEXT-WORK-AREA-LINE.   ELELPPML
00492      SKIP1                                                        ELELPPML
00493 *                                                          *      ELELPPML
00494 *        TRUNCATE TRAILING SPACES                          *      ELELPPML
00495 *                                                          *      ELELPPML
00496          PERFORM 00138-BYPASS-TRAILING-SPACES                     ELELPPML
00497          VARYING WS-LINE-LENGTH                                   ELELPPML
00498                  FROM LENGTH OF WS-TEXT-WORK-AREA BY -1           ELELPPML
00499                  UNTIL WS-LINE-LENGTH = 0 OR                      ELELPPML
00500                        WS-TEXT-WORK-CHAR (WS-LINE-LENGTH) NOT     ELELPPML
00501              = SPACE.                                             ELELPPML
00502      SKIP1                                                        ELELPPML
00503      IF WS-LINE-LENGTH > ZERO                                     ELELPPML
00504          PERFORM 00140-MOVE-TRUNCATED-LINE-TO-P.                  ELELPPML
00505      PERFORM 00182-APPEND-END-OF-LINE-CHARA.                      ELELPPML
00506                                                                   ELELPPML
00507                                                                   ELELPPML
00508 ************************************************************      ELELPPML
00509 *                                                          *      ELELPPML
00510 *        BYPASS TRAILING SPACES                            *      ELELPPML
00511 *                                                          *      ELELPPML
00512 ************************************************************      ELELPPML
00513  00138-BYPASS-TRAILING-SPACES.                                    ELELPPML
00514      CONTINUE.                                                    ELELPPML
00515                                                                   ELELPPML
00516                                                                   ELELPPML
00517 ************************************************************      ELELPPML
00518 *                                                          *      ELELPPML
00519 *        MOVE TRUNCATED LINE TO PRINT AREA                 *      ELELPPML
00520 *                                                          *      ELELPPML
00521 ************************************************************      ELELPPML
00522  00140-MOVE-TRUNCATED-LINE-TO-P.                                  ELELPPML
00523      CALL 'ELUMVCL' USING WS-TEXT-WORK-AREA                       ELELPPML
00524                           WS-LINE-LENGTH                          ELELPPML
00525                           WS-PRINT-BYTES (WS-PRINT-SUB)           ELELPPML
00526                           WS-LINE-LENGTH                          ELELPPML
00527                           WS-A-SPACE.                             ELELPPML
00528      ADD WS-LINE-LENGTH TO WS-PRINT-SUB.                          ELELPPML
00529                                                                   ELELPPML
00530                                                                   ELELPPML
00531 ************************************************************      ELELPPML
00532 *                                                          *      ELELPPML
00533 *        PRINT THE PAGE                                    *      ELELPPML
00534 *                                                          *      ELELPPML
00535 ************************************************************      ELELPPML
00536  00147-PRINT-THE-PAGE.                                            ELELPPML
00537      PERFORM 00150-APPEND-THE-TRAILER-TEXT.                       ELELPPML
00538      PERFORM 00172-SEND-THE-PRINT-AREA-TO-T.                      ELELPPML
00539                                                                   ELELPPML
00540                                                                   ELELPPML
00541 ************************************************************      ELELPPML
00542 *                                                          *      ELELPPML
00543 *        APPEND THE TRAILER TEXT                           *      ELELPPML
00544 *                                                          *      ELELPPML
00545 ************************************************************      ELELPPML
00546  00150-APPEND-THE-TRAILER-TEXT.                                   ELELPPML
00547      PERFORM 00182-APPEND-END-OF-LINE-CHARA                       ELELPPML
00548          UNTIL WS-LINE-COUNT > 27.                                ELELPPML
00549      SKIP1                                                        ELELPPML
00550 *                                                          *      ELELPPML
00551 *        APPEND TRAILER LINE                               *      ELELPPML
00552 *                                                          *      ELELPPML
00553          MOVE LENGTH OF WS-TRAILER-LINE-1 TO WS-MOVE-LENGTH       ELELPPML
00554          CALL 'ELUMVCL' USING WS-TRAILER-LINE-1                   ELELPPML
00555                           WS-MOVE-LENGTH                          ELELPPML
00556                           WS-PRINT-BYTES (WS-PRINT-SUB)           ELELPPML
00557                           WS-MOVE-LENGTH                          ELELPPML
00558                           WS-A-SPACE                              ELELPPML
00559          ADD WS-MOVE-LENGTH TO WS-PRINT-SUB                       ELELPPML
00560          ADD 1 TO WS-LINE-COUNT.                                  ELELPPML
00561      SKIP1                                                        ELELPPML
00562                                                                   ELELPPML
00563                                                                   ELELPPML
00564 ************************************************************      ELELPPML
00565 *                                                          *      ELELPPML
00566 *        GET NEXT PAGE TO PROCESS                          *      ELELPPML
00567 *                                                          *      ELELPPML
00568 ************************************************************      ELELPPML
00569  00162-GET-NEXT-PAGE-TO-PROCESS.                                  ELELPPML
00570      EXEC CICS READQ TS                                           ELELPPML
00571                QUEUE(PPB-TSQ-NAME)                                ELELPPML
00572                SET(PQ-POINTER)                                    ELELPPML
00573                LENGTH(PQ-LENGTH)                                  ELELPPML
00574                NEXT                                               ELELPPML
00575                SYSID(PPB-OWNER-SYSID)                             ELELPPML
00576          END-EXEC.                                                ELELPPML
00577      IF EIBRCODE NOT = LOW-VALUES                                 ELELPPML
00578          PERFORM 00196-TERMINATION.                               ELELPPML
00579      SET ADDRESS OF PQ-PAGE-QUEUE TO PQ-POINTER.                  ELELPPML
00580                                                                   ELELPPML
00581                                                                   ELELPPML
00582 ************************************************************      ELELPPML
00583 *                                                          *      ELELPPML
00584 *        SEND THE PRINT AREA TO THE PRINTER                *      ELELPPML
00585 *                                                          *      ELELPPML
00586 ************************************************************      ELELPPML
00587  00172-SEND-THE-PRINT-AREA-TO-T.                                  ELELPPML
00588      IF WS-PRINT-SUB > 1                                          ELELPPML
00589          PERFORM 00187-PRINT-PARTIAL-PAGE.                        ELELPPML
00590      PERFORM 00182-APPEND-END-OF-LINE-CHARA                       ELELPPML
00591          UNTIL WS-LINE-COUNT > 50.                                ELELPPML
00592      MOVE DFHBMPEM TO WS-PRINT-BYTES (WS-PRINT-SUB).              ELELPPML
00593      EXEC CICS SEND FROM(WS-PRINT-AREA)                           ELELPPML
00594                LENGTH(WS-PRINT-SUB)                               ELELPPML
00595                DEST(PPB-PRINTER-ID)                               ELELPPML
00596                WAIT                                               ELELPPML
00597                CTLCHAR(DFHBMBRY)                                  ELELPPML
00598           END-EXEC.                                               ELELPPML
00599                                                                   ELELPPML
00600                                                                   ELELPPML
00601 ************************************************************      ELELPPML
00602 *                                                          *      ELELPPML
00603 *        APPEND END OF LINE CHARACTER                      *      ELELPPML
00604 *                                                          *      ELELPPML
00605 ************************************************************      ELELPPML
00606  00182-APPEND-END-OF-LINE-CHARA.                                  ELELPPML
00607      MOVE DFHBMPNL TO WS-PRINT-BYTES (WS-PRINT-SUB).              ELELPPML
00608      ADD 1 TO WS-PRINT-SUB.                                       ELELPPML
00609      ADD 1 TO WS-LINE-COUNT.                                      ELELPPML
00610      IF WS-PRINT-SUB > 1799                                       ELELPPML
00611          PERFORM 00187-PRINT-PARTIAL-PAGE.                        ELELPPML
00612                                                                   ELELPPML
00613                                                                   ELELPPML
00614 ************************************************************      ELELPPML
00615 *                                                          *      ELELPPML
00616 *        PRINT PARTIAL PAGE                                *      ELELPPML
00617 *                                                          *      ELELPPML
00618 ************************************************************      ELELPPML
00619  00187-PRINT-PARTIAL-PAGE.                                        ELELPPML
00620      MOVE DFHBMPEM TO WS-PRINT-BYTES (WS-PRINT-SUB).              ELELPPML
00621      EXEC CICS SEND FROM(WS-PRINT-AREA)                           ELELPPML
00622                LENGTH(WS-PRINT-SUB)                               ELELPPML
00623                DEST(PPB-PRINTER-ID)                               ELELPPML
00624                CTLCHAR(DFHBMBRY)                                  ELELPPML
00625           END-EXEC.                                               ELELPPML
00626      MOVE SPACES TO WS-PRINT-AREA.                                ELELPPML
00627      MOVE 1 TO WS-PRINT-SUB.                                      ELELPPML
00628                                                                   ELELPPML
00629                                                                   ELELPPML
00630 ************************************************************      ELELPPML
00631 *                                                          *      ELELPPML
00632 *        TERMINATION                                       *      ELELPPML
00633 *                                                          *      ELELPPML
00634 ************************************************************      ELELPPML
00635  00196-TERMINATION.                                               ELELPPML
00636      EXEC CICS DELETEQ TS                                         ELELPPML
00637                QUEUE(PPB-TSQ-NAME)                                ELELPPML
00638                SYSID(PPB-OWNER-SYSID)                             ELELPPML
00639           END-EXEC.                                               ELELPPML
00640      EXEC CICS RETURN                                             ELELPPML
00641           END-EXEC.                                               ELELPPML
