00001 *      LAST MAINTENANCE TIME: 10.40.31  DATE: 02/01/89            09/03/03
00002 * GENERATED BY STRUCTURE(S) CODE GENERATOR V2.0                   ELGGXXD 
00003 *     ON 89/02/01 AT 10:40:16.32                                     LV002
00004 * STRUCTURE(S) MEMBER ELGGXXDPW  - LEVEL 033 AS OF 02/01/89       ELGGXXD 
00005 * FROM PANLIB R360059.STRUCTPL.PANLIB                             ELGGXXD 
00006 *                                                                 ELGGXXD 
00007  IDENTIFICATION DIVISION.                                         ELGGXXD 
00008 *                                                                 ELGGXXD 
00009  PROGRAM-ID.         ELGGXXD.                                     ELGGXXD 
00010 *                                                                 ELGGXXD 
00011 *                                                                 ELGGXXD 
00012  AUTHOR.             DAVID SECOR  OF  A.C.I.                      ELGGXXD 
00013 *                                                                 ELGGXXD 
00014  INSTALLATION.       HEALTH CARE SERVICE CORPORATION              ELGGXXD 
00015                      A MUTUAL LEGAL RESERVE COMPANY               ELGGXXD 
00016                      BLUE CROSS/BLUE SHIELD OF ILLINOIS           ELGGXXD 
00017                      233 N. MICHIGAN AVE                          ELGGXXD 
00018                      CHICAGO, ILLINOIS 60601                      ELGGXXD 
00019 *                                                                 ELGGXXD 
00020  DATE-WRITTEN.       30-JUL-1987.                                 ELGGXXD 
00021 *                                                                 ELGGXXD 
00022  DATE-COMPILED.                                                   ELGGXXD 
00023 *                                                                 ELGGXXD 
00024  SECURITY.           COPYRIGHT 1987,                              ELGGXXD 
00025                      HEALTH CARE SERVICE CORPORATION              ELGGXXD 
00026 *                                                                 ELGGXXD 
00027 ******************************************************************ELGGXXD 
00028 *   ELGGXXD                                                       ELGGXXD 
00029 *                                                                 ELGGXXD 
00030 *                        PROGRAM ABSTRACT                         ELGGXXD 
00031 *                                                                 ELGGXXD 
00032 *   PROGRAM NAME:   E.L.S. GROUP SPECIFIC RELATED DIAGNOSIS       ELGGXXD 
00033 *                   COST CONTAINMENT SUBROUTINE                   ELGGXXD 
00034 *                                                                 ELGGXXD 
00035 *   PROGRAM I.D.:   ELGGXXD                                       ELGGXXD 
00036 *                                                                 ELGGXXD 
00037 *   PURPOSE:   TO DISPLAY ENGLISH VERBIAGE DESCRIBING THE FIELDS  ELGGXXD 
00038 *              FOR RELATED DIAGNOSIS COST CONTAINMENT PROGRAMS.   ELGGXXD 
00039 *              SINCE THE RECORD FORMATS FOR THESE COST            ELGGXXD 
00040 *              CONTAINMENT RECORDS ARE IDENTICAL ONLY ONE         ELGGXXD 
00041 *              FORMAT HAS BEEN USED IN THIS PROGRAM.              ELGGXXD 
00042 *                                                                 ELGGXXD 
00043 *   RECORDS                                                       ELGGXXD 
00044 *   ACCESSED:  GPAD, GRID, AND GWCD ALL GROUP SPECIFIC            ELGGXXD 
00045 *              COST CONTAINMENT RECORDS.                          ELGGXXD 
00046 *                                                                 ELGGXXD 
00047 ******************************************************************ELGGXXD 
00048 *       *-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*       ELGGXXD 
00049 *       *-*         U P D A T E   H I S T O R Y         *-*       ELGGXXD 
00050 *       *-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*       ELGGXXD 
00051 **-CHG-NUM-* *-DATE-* *WHO* *---------DESCRIPTION----------------*ELGGXXD 
00052 *                                                                 ELGGXXD 
00053 *  ELS 2.0   07/30/87  DES  INCEPTION.                            ELGGXXD 
00054 *                                                                 ELGGXXD 
00055 *  ELS 2.0   08/19/87  DES  CHANGED DBPIOPMC REQUEST TO NEW FORMATELGGXXD 
00056 *                                                                 ELGGXXD 
00057 *  ELS 2.0   09/01/87  DES  FIXED INVALID ACCESS OF DBPIOPMC      ELGGXXD 
00058 *                                                                 ELGGXXD 
00059 *  ELS 2.1   01/04/89  AKK  CHANGED PLELITCOMP TO ELITCOMPL       ELGGXXD 
00060 *                                                                 ELGGXXD 
00061 *  ELS 2.2   01/17/89  AKK  MADE CHANGES TO ACCOMODATE STORAGE    ELGGXXD 
00062 *                           MANAGEMENT ENHANCEMENTS AND ADDED     ELGGXXD 
00063 *                           LOGIC TO INCLUDE THE READING OF THE   ELGGXXD 
00064 *                           COPORATE LIST OVERRIDE FOR THE GPAD   ELGGXXD 
00065 *                           TABULAR.                              ELGGXXD 
00066 *  ELS 3.0   05/07/03  AKK  RECOMPILE FOR PROCED/DIAG EXPANSION   ELGGXXD 
00067 *                                                                 ELGGXXD 
00068 *  ELS 3.0   05/13/03  AKK  ADD WORKING STORAGE FIELD TO MOVE     ELGGXXD 
00069 *                           ONLY 5 CHARS THRU DBPOIC AS           ELGGXXD 
00070 *                           THEY ARE NOT CHANGE TO 10 YET.        ELGGXXD 
00071 ******************************************************************ELGGXXD 
00072 /                                                                 ELGGXXD 
00073  ENVIRONMENT DIVISION.                                            ELGGXXD 
00074  CONFIGURATION SECTION.                                           ELGGXXD 
00075  SOURCE-COMPUTER.    IBM-3081.                                    ELGGXXD 
00076  OBJECT-COMPUTER.    IBM-3090.                                    ELGGXXD 
00077 /                                                                 ELGGXXD 
00078  DATA DIVISION.                                                   ELGGXXD 
00079  WORKING-STORAGE SECTION.                                         ELGGXXD 
00080  01  WS-BEGIN               PIC X(24)  VALUE                      ELGGXXD 
00081      'ELGGXXD WORKING STORAGE*'.                                  ELGGXXD 
00082 /     W O R K F I E L D S   A N D   S W I T C H E S               ELGGXXD 
00083  01  WS-MISC-WORK.                                                ELGGXXD 
00084      05  WS-DIAGNOSIS-ARGUMENT.                                   ELGGXXD 
00085          10 WS-DIAGNOSIS-ARGUMENT-5    PIC X(05).                 ELGGXXD 
00086          10 FILLER                     PIC X(05).                 ELGGXXD 
00087      05  WS-SUB             PIC S9999  COMP SYNC VALUE ZEROES.    ELGGXXD 
00088      05  WS-I-E-IND         PIC X.                                ELGGXXD 
00089      05  WS-TAB-SLOT-NO     PIC 9(7).                             ELGGXXD 
00090      05  WS-FIRST-TIME-IND-VAL   PIC X VALUE SPACE.               ELGGXXD 
00091        88  WS-FIRST-TIME-THIS-IND    VALUE 'Y'.                   ELGGXXD 
00092      05  WS-DID-GETMAIN-SWITCH  PIC X  VALUE SPACE.               ELGGXXD 
00093        88  WS-DID-GETMAIN            VALUE 'Y'.                   ELGGXXD 
00094      05  WS-TAB-TYPE-DEF.                                         ELGGXXD 
00095        10  WS-GPAD          PIC X(6)   VALUE '#GPAD '.            ELGGXXD 
00096        10  WS-GRID          PIC X(6)   VALUE '#GRID '.            ELGGXXD 
00097        10  WS-GWCD          PIC X(6)   VALUE '#GWCD '.            ELGGXXD 
00098      05  WS-TAB-ID-TABLE   REDEFINES   WS-TAB-TYPE-DEF.           ELGGXXD 
00099        10  WS-TAB-TYPE      PIC X(6) OCCURS  3  TIMES             ELGGXXD 
00100                             INDEXED BY  WS-IDX.                   ELGGXXD 
00101  01  WS-RELATED-DIAGNOSES   PIC X(57) VALUE                       ELGGXXD 
00102      'PROGRAM HAS THE FOLLOWING RELATED DIAGNOSES (IN PLACE OF '. ELGGXXD 
00103                                                                   ELGGXXD 
00104  01  WS-RELATED-DIAGNOSESA  PIC X(22) VALUE                       ELGGXXD 
00105      'THE CORPORATE LIST):  '.                                    ELGGXXD 
00106                                                                   ELGGXXD 
00107  01  WS-END                 PIC X(24)  VALUE                      ELGGXXD 
00108      '*** ELGGXXD W/S ENDS ***'.                                  ELGGXXD 
00109 /             L I N K A G E   S E C T I O N                       ELGGXXD 
00110  LINKAGE SECTION.                                                 ELGGXXD 
00111  01  DFHCOMMAREA.                                                 ELGGXXD 
00112      COPY ELSCOMMC.                                               ELGGXXD 
00113 /    C O M M O N   I N T E R F A C E   A R E A                    ELGGXXD 
00114      COPY ELSCIA2C.                                               ELGGXXD 
00115 /    C O D E S   M A N U A L   D E S C R I P T I O N   L I N E S  ELGGXXD 
00116      COPY ELSCMDSC.                                               ELGGXXD 
00117 /    C O D E S   M A N U A L   C N T L .   B L O C K              ELGGXXD 
00118      COPY ELSCMIFC.                                               ELGGXXD 
00119 /    I / O   P A R A M E T E R   B L O C K                        ELGGXXD 
00120      COPY ELSIOPMC.                                               ELGGXXD 
00121 /    W O R K   A R E A   T O   B U I L D   K E Y S                ELGGXXD 
00122      COPY ELSKEYSC.                                               ELGGXXD 
00123 /    C N T L   B L O C K   -   O U T P U T   P A G E   B L D R    ELGGXXD 
00124      COPY ELSOUTPC.                                               ELGGXXD 
00125 /    T E X T   C O M P R E S S I O N   W O R K   A R E A          ELGGXXD 
00126      COPY ELSTCWAC.                                               ELGGXXD 
00127 /    S E L E C T O R   S T A T U S   C O N T R O L   B L O C K    ELGGXXD 
00128      COPY ELSSSCBC.                                               ELGGXXD 
00129 /    S U B R O U T I N E   P A R A M E T E R   L I S T            ELGGXXD 
00130      COPY ELSSRTPC.                                               ELGGXXD 
00131 /    G R O U P   S P E C I F I C   # G P A D   T A B U L A R      ELGGXXD 
00132  01  GSC-TABULAR-REC-AREA.                                        ELGGXXD 
00133      COPY GCTGPADC.                                               ELGGXXD 
00134 /    G R O U P   S P E C I F I C   # G R I D   T A B U L A R      ELGGXXD 
00135  01  GSD-TABULAR-REC-AREA.                                        ELGGXXD 
00136      COPY GCTGRIDC.                                               ELGGXXD 
00137 /    P R O V I D E R   N O .   T O   N A M E   D B   P A R M S    ELGGXXD 
00138  01  PDB-IO-AREA.                                                 ELGGXXD 
00139      COPY DBPIOPMC.                                               ELGGXXD 
00140 /    D I A G N O S I S   M A S T E R   R E C O R D   R D W        ELGGXXD 
00141  01  DIAGNOSIS-MSTR-REC.                                          ELGGXXD 
00142      COPY CR8200.                                                 ELGGXXD 
00143      EJECT                                                        ELGGXXD 
00144  PROCEDURE DIVISION.                                              ELGGXXD 
00145 ************************************************************      ELGGXXD 
00146 *                                                          *      ELGGXXD 
00147 *                    PROCEDURE DIVISION                    *      ELGGXXD 
00148 *                                                          *      ELGGXXD 
00149 ************************************************************      ELGGXXD 
00150                                                                   ELGGXXD 
00151                                                                   ELGGXXD 
00152 ************************************************************      ELGGXXD 
00153 *                                                          *      ELGGXXD 
00154 *        GXXD TABULAR MAINLINE                             *      ELGGXXD 
00155 *                                                          *      ELGGXXD 
00156 ************************************************************      ELGGXXD 
00157  00001-GXXD-TABULAR-MAINLINE.                                     ELGGXXD 
00158      PERFORM 00005-INITIALIZATION-ROUTINE.                        ELGGXXD 
00159      PERFORM 00039-MAIN-ROUTINE.                                  ELGGXXD 
00160      PERFORM 00044-TERMINATION-ROUTINE.                           ELGGXXD 
00161      EJECT                                                        ELGGXXD 
00162                                                                   ELGGXXD 
00163                                                                   ELGGXXD 
00164 ************************************************************      ELGGXXD 
00165 *                                                          *      ELGGXXD 
00166 *        INITIALIZATION ROUTINE                            *      ELGGXXD 
00167 *                                                          *      ELGGXXD 
00168 ************************************************************      ELGGXXD 
00169  00005-INITIALIZATION-ROUTINE.                                    ELGGXXD 
00170      IF EIBCALEN  NOT =  LENGTH OF DFHCOMMAREA                    ELGGXXD 
00171          PERFORM 00278-COMMAREA-LENGTH-ERROR.                     ELGGXXD 
00172      CALL 'ELUINISM' USING DFHCOMMAREA                            ELGGXXD 
00173          ADDRESS OF CIA-ELS-COMMON-INTERFACE-AREA.                ELGGXXD 
00174      SET CIA-ELSOUTP-DDN TO TRUE.                                 ELGGXXD 
00175      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELGGXXD 
00176          ADDRESS OF COF-OUTPUT-INTERFACE.                         ELGGXXD 
00177      SET CIA-ELSCMIF-DDN TO TRUE.                                 ELGGXXD 
00178      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELGGXXD 
00179          ADDRESS OF CMF-CODES-MANUAL-INTERFACE.                   ELGGXXD 
00180      SET CIA-ELSKEYS-DDN TO TRUE.                                 ELGGXXD 
00181      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELGGXXD 
00182          ADDRESS OF KWA-FILE-KEY-WORK-AREA.                       ELGGXXD 
00183      SET CIA-ELSSRTP-DDN TO TRUE.                                 ELGGXXD 
00184      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELGGXXD 
00185          ADDRESS OF SRP-SUBROUTINE-PARAMETERS.                    ELGGXXD 
00186      SET CIA-ELSSSCB-DDN TO TRUE.                                 ELGGXXD 
00187      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELGGXXD 
00188          ADDRESS OF SSB-SELECTOR-STATUS-CTL-BLK.                  ELGGXXD 
00189      SET CIA-ELSTCWA-DDN TO TRUE.                                 ELGGXXD 
00190      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELGGXXD 
00191          ADDRESS OF TCAR-COMPRESSION-WORK-AREA.                   ELGGXXD 
00192      INITIALIZE CMF-CODES-MANUAL-INTERFACE                        ELGGXXD 
00193                 TCAR-FROM-AREA.                                   ELGGXXD 
00194      SET CIA-DBPIOPM-DDN  TO TRUE.                                ELGGXXD 
00195      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELGGXXD 
00196          ADDRESS OF PDB-IO-AREA.                                  ELGGXXD 
00197      IF CIA-RC-PTR-NULL                                           ELGGXXD 
00198          PERFORM 00067-GETMAIN-IO-PARM-AREA.                      ELGGXXD 
00199      IF WS-DID-GETMAIN                                            ELGGXXD 
00200          PERFORM 00035-DO-ADDRESS-OF-PDB.                         ELGGXXD 
00201      MOVE 'Y'  TO  WS-FIRST-TIME-IND-VAL.                         ELGGXXD 
00202      EJECT                                                        ELGGXXD 
00203                                                                   ELGGXXD 
00204                                                                   ELGGXXD 
00205 ************************************************************      ELGGXXD 
00206 *                                                          *      ELGGXXD 
00207 *        DO ADDRESS OF PDB                                 *      ELGGXXD 
00208 *                                                          *      ELGGXXD 
00209 ************************************************************      ELGGXXD 
00210  00035-DO-ADDRESS-OF-PDB.                                         ELGGXXD 
00211      SET CIA-DBPIOPM-DDN  TO TRUE.                                ELGGXXD 
00212      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELGGXXD 
00213          ADDRESS OF PDB-IO-AREA.                                  ELGGXXD 
00214                                                                   ELGGXXD 
00215                                                                   ELGGXXD 
00216 ************************************************************      ELGGXXD 
00217 *                                                          *      ELGGXXD 
00218 *        MAIN ROUTINE                                      *      ELGGXXD 
00219 *                                                          *      ELGGXXD 
00220 ************************************************************      ELGGXXD 
00221  00039-MAIN-ROUTINE.                                              ELGGXXD 
00222      SKIP1                                                        ELGGXXD 
00223 *                                                          *      ELGGXXD 
00224 *        SEARCH COST CONTAINMENT TABLE                     *      ELGGXXD 
00225 *                                                          *      ELGGXXD 
00226          SET WS-IDX  TO  1                                        ELGGXXD 
00227          SEARCH WS-TAB-TYPE                                       ELGGXXD 
00228            VARYING WS-IDX                                         ELGGXXD 
00229            AT END                                                 ELGGXXD 
00230               SET CIA-AB-TAB-UNDEF  TO  TRUE                      ELGGXXD 
00231               EXEC CICS  ABEND  ABCODE(CIA-ABCODE) END-EXEC       ELGGXXD 
00232            WHEN WS-TAB-TYPE(WS-IDX)  =  SRP-TABULAR-ID            ELGGXXD 
00233                NEXT SENTENCE                                      ELGGXXD 
00234         END-SEARCH.                                               ELGGXXD 
00235      SKIP1                                                        ELGGXXD 
00236      PERFORM 00046-READ-INTERNAL-TABULAR-RE.                      ELGGXXD 
00237      IF SRP-TABULAR-ID  =  WS-GPAD                                ELGGXXD 
00238          PERFORM 00086-PROCESS-GPAD-RECORD.                       ELGGXXD 
00239      IF SRP-TABULAR-ID  =  WS-GRID OR  WS-GWCD                    ELGGXXD 
00240          PERFORM 00177-PROCESS-OTHER-RECORDS.                     ELGGXXD 
00241                                                                   ELGGXXD 
00242                                                                   ELGGXXD 
00243 ************************************************************      ELGGXXD 
00244 *                                                          *      ELGGXXD 
00245 *        TERMINATION ROUTINE                               *      ELGGXXD 
00246 *                                                          *      ELGGXXD 
00247 ************************************************************      ELGGXXD 
00248  00044-TERMINATION-ROUTINE.                                       ELGGXXD 
00249      GOBACK.                                                      ELGGXXD 
00250      EJECT                                                        ELGGXXD 
00251                                                                   ELGGXXD 
00252                                                                   ELGGXXD 
00253 ************************************************************      ELGGXXD 
00254 *                                                          *      ELGGXXD 
00255 *        READ INTERNAL TABULAR RECORD                      *      ELGGXXD 
00256 *                                                          *      ELGGXXD 
00257 ************************************************************      ELGGXXD 
00258  00046-READ-INTERNAL-TABULAR-RE.                                  ELGGXXD 
00259      SET CIA-GCTABULR-DDN TO TRUE.                                ELGGXXD 
00260      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELGGXXD 
00261          ADDRESS OF IOP-INPUT-OUTPUT-PARAMETERS.                  ELGGXXD 
00262      IF CIA-RC-PTR-NULL                                           ELGGXXD 
00263          PERFORM 00067-GETMAIN-IO-PARM-AREA.                      ELGGXXD 
00264      SET CIA-GCTABULR-DDN TO TRUE.                                ELGGXXD 
00265      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELGGXXD 
00266          ADDRESS OF IOP-INPUT-OUTPUT-PARAMETERS.                  ELGGXXD 
00267      SET IOP-RD                                                   ELGGXXD 
00268          IOP-FCQ-NONE                                             ELGGXXD 
00269          IOP-KVQ-EQ                                               ELGGXXD 
00270          IOP-STG-MODE-MOVE  TO  TRUE.                             ELGGXXD 
00271      MOVE SRP-INTERNAL-TAB  TO  KWA-GCTABULR-KEY                  ELGGXXD 
00272                             IOP-FILE-KEY.                         ELGGXXD 
00273      MOVE SPACES  TO  IOP-AIX-DDNAME.                             ELGGXXD 
00274      SET IOP-REC-PTR  TO  NULL.                                   ELGGXXD 
00275      EXEC CICS  LINK  PROGRAM('ELUIOPGM')                         ELGGXXD 
00276                       COMMAREA(DFHCOMMAREA) END-EXEC.             ELGGXXD 
00277      IF NOT IOP-RC-OK                                             ELGGXXD 
00278          PERFORM 00259-TABULAR-NOT-FOUND.                         ELGGXXD 
00279      IF SRP-TABULAR-ID  =  WS-GPAD                                ELGGXXD 
00280          PERFORM 00072-ADDRESS-GPAD-TABULAR-ARE.                  ELGGXXD 
00281      IF SRP-TABULAR-ID  =  WS-GRID OR  WS-GWCD                    ELGGXXD 
00282          PERFORM 00074-ADDRESS-OTHER-TABULAR-AR.                  ELGGXXD 
00283      EJECT                                                        ELGGXXD 
00284                                                                   ELGGXXD 
00285                                                                   ELGGXXD 
00286 ************************************************************      ELGGXXD 
00287 *                                                          *      ELGGXXD 
00288 *        GETMAIN IO PARM AREA                              *      ELGGXXD 
00289 *                                                          *      ELGGXXD 
00290 ************************************************************      ELGGXXD 
00291  00067-GETMAIN-IO-PARM-AREA.                                      ELGGXXD 
00292      SET CIA-STG-GETMAIN  TO  TRUE.                               ELGGXXD 
00293      EXEC CICS  LINK  PROGRAM('ELUSTGMG')                         ELGGXXD 
00294                       COMMAREA(DFHCOMMAREA)   END-EXEC.           ELGGXXD 
00295      SET WS-DID-GETMAIN TO TRUE.                                  ELGGXXD 
00296      EJECT                                                        ELGGXXD 
00297                                                                   ELGGXXD 
00298                                                                   ELGGXXD 
00299 ************************************************************      ELGGXXD 
00300 *                                                          *      ELGGXXD 
00301 *        ADDRESS GPAD TABULAR AREA                         *      ELGGXXD 
00302 *                                                          *      ELGGXXD 
00303 ************************************************************      ELGGXXD 
00304  00072-ADDRESS-GPAD-TABULAR-ARE.                                  ELGGXXD 
00305      SET ADDRESS OF GSC-TABULAR-REC-AREA  TO  IOP-REC-PTR.        ELGGXXD 
00306      EJECT                                                        ELGGXXD 
00307                                                                   ELGGXXD 
00308                                                                   ELGGXXD 
00309 ************************************************************      ELGGXXD 
00310 *                                                          *      ELGGXXD 
00311 *        ADDRESS OTHER TABULAR AREA                        *      ELGGXXD 
00312 *                                                          *      ELGGXXD 
00313 ************************************************************      ELGGXXD 
00314  00074-ADDRESS-OTHER-TABULAR-AR.                                  ELGGXXD 
00315      SET ADDRESS OF GSD-TABULAR-REC-AREA  TO  IOP-REC-PTR.        ELGGXXD 
00316      EJECT                                                        ELGGXXD 
00317                                                                   ELGGXXD 
00318                                                                   ELGGXXD 
00319 ************************************************************      ELGGXXD 
00320 *                                                          *      ELGGXXD 
00321 *        PROCESS GPAD RECORD                               *      ELGGXXD 
00322 *                                                          *      ELGGXXD 
00323 ************************************************************      ELGGXXD 
00324  00086-PROCESS-GPAD-RECORD.                                       ELGGXXD 
00325      IF GSC-DIAGNOSIS-ARGUMENT(1)  NOT =  HIGH-VALUES             ELGGXXD 
00326          PERFORM 00095-SAVE-GPADS-FIRST-I-E-IND                   ELGGXXD 
00327      ELSE PERFORM 00267-EMPTY-COST-CONTAINMENT-T.                 ELGGXXD 
00328      PERFORM 00243-INSERT-BLANK-LINE.                             ELGGXXD 
00329      PERFORM 00097-SEARCH-GPAD-TABLE-FOR-FI                       ELGGXXD 
00330          VARYING GSC-INDEX  FROM  1  BY  1                        ELGGXXD 
00331             UNTIL GSC-INDEX  =  GSC-ENTRY-COUNT OR                ELGGXXD 
00332             GSC-DIAGNOSIS-ARGUMENT(GSC-INDEX)  =  HIGH-VALUES.    ELGGXXD 
00333      PERFORM 00243-INSERT-BLANK-LINE.                             ELGGXXD 
00334      MOVE 'Y'  TO  WS-FIRST-TIME-IND-VAL.                         ELGGXXD 
00335      PERFORM 00099-SEARCH-GPAD-TABLE-FOR-OT                       ELGGXXD 
00336          VARYING GSC-INDEX  FROM  1  BY  1                        ELGGXXD 
00337             UNTIL GSC-INDEX  =  GSC-ENTRY-COUNT OR                ELGGXXD 
00338             GSC-DIAGNOSIS-ARGUMENT(GSC-INDEX)  =  HIGH-VALUES.    ELGGXXD 
00339      PERFORM 00243-INSERT-BLANK-LINE.                             ELGGXXD 
00340      EJECT                                                        ELGGXXD 
00341                                                                   ELGGXXD 
00342                                                                   ELGGXXD 
00343 ************************************************************      ELGGXXD 
00344 *                                                          *      ELGGXXD 
00345 *        SAVE GPADS FIRST I-E IND                          *      ELGGXXD 
00346 *                                                          *      ELGGXXD 
00347 ************************************************************      ELGGXXD 
00348  00095-SAVE-GPADS-FIRST-I-E-IND.                                  ELGGXXD 
00349      MOVE GSC-INCLUDE-EXCLUDE-IND(1)  TO  WS-I-E-IND.             ELGGXXD 
00350      EJECT                                                        ELGGXXD 
00351                                                                   ELGGXXD 
00352                                                                   ELGGXXD 
00353 ************************************************************      ELGGXXD 
00354 *                                                          *      ELGGXXD 
00355 *        SEARCH GPAD TABLE FOR FIRST                       *      ELGGXXD 
00356 *                                                          *      ELGGXXD 
00357 ************************************************************      ELGGXXD 
00358  00097-SEARCH-GPAD-TABLE-FOR-FI.                                  ELGGXXD 
00359      IF GSC-INCLUDE-EXCLUDE-IND(GSC-INDEX)  =  WS-I-E-IND         ELGGXXD 
00360          PERFORM 00101-LIST-GPADS-SERVICE-RELAT.                  ELGGXXD 
00361      EJECT                                                        ELGGXXD 
00362                                                                   ELGGXXD 
00363                                                                   ELGGXXD 
00364 ************************************************************      ELGGXXD 
00365 *                                                          *      ELGGXXD 
00366 *        SEARCH GPAD TABLE FOR OTHER THAN FIRST            *      ELGGXXD 
00367 *                                                          *      ELGGXXD 
00368 ************************************************************      ELGGXXD 
00369  00099-SEARCH-GPAD-TABLE-FOR-OT.                                  ELGGXXD 
00370      IF GSC-INCLUDE-EXCLUDE-IND(GSC-INDEX)  NOT =  WS-I-E-IND     ELGGXXD 
00371          PERFORM 00101-LIST-GPADS-SERVICE-RELAT.                  ELGGXXD 
00372      EJECT                                                        ELGGXXD 
00373                                                                   ELGGXXD 
00374                                                                   ELGGXXD 
00375 ************************************************************      ELGGXXD 
00376 *                                                          *      ELGGXXD 
00377 *        LIST GPADS SERVICE RELATED DIAGNOSIS              *      ELGGXXD 
00378 *                                                          *      ELGGXXD 
00379 ************************************************************      ELGGXXD 
00380  00101-LIST-GPADS-SERVICE-RELAT.                                  ELGGXXD 
00381      IF WS-FIRST-TIME-THIS-IND                                    ELGGXXD 
00382          PERFORM 00113-DETERMINE-IF-CONTRACT-US.                  ELGGXXD 
00383      MOVE '9'  TO  PDB-I-SERVICE-CODE-SYSTEM-ID.                  ELGGXXD 
00384      MOVE GSC-DIAGNOSIS-ARGUMENT(GSC-INDEX)  TO                   ELGGXXD 
00385           WS-DIAGNOSIS-ARGUMENT                                   ELGGXXD 
00386      MOVE WS-DIAGNOSIS-ARGUMENT-5 TO                              ELGGXXD 
00387          PDB-I-SERVICE-CODE.                                      ELGGXXD 
00388      MOVE 'PRCDR'  TO  PDB-I-REQUEST-TYPE-N.                      ELGGXXD 
00389      MOVE '00'  TO  PDB-I-VERSION.                                ELGGXXD 
00390      MOVE 'D'  TO  PDB-I-ACCESS-MODE.                             ELGGXXD 
00391      EXEC CICS  LINK  PROGRAM('DBPIOC') COMMAREA(PDB-IO-AREA)     ELGGXXD 
00392           END-EXEC.                                               ELGGXXD 
00393      IF PDB-O-RC-SUCCESSFUL                                       ELGGXXD 
00394          PERFORM 00164-STRING-GPADS-DIAGNOSIS-A                   ELGGXXD 
00395      ELSE PERFORM 00262-DIAGNOSIS-FILE-PROBLEM.                   ELGGXXD 
00396      PERFORM 00255-CALL-OUTPUT.                                   ELGGXXD 
00397      EJECT                                                        ELGGXXD 
00398                                                                   ELGGXXD 
00399                                                                   ELGGXXD 
00400 ************************************************************      ELGGXXD 
00401 *                                                          *      ELGGXXD 
00402 *        DETERMINE IF CONTRACT USES CORPORATE LIST         *      ELGGXXD 
00403 *                                                          *      ELGGXXD 
00404 ************************************************************      ELGGXXD 
00405  00113-DETERMINE-IF-CONTRACT-US.                                  ELGGXXD 
00406      IF GSC-CORP-LIST-OVERIDE-IND = 'N'                           ELGGXXD 
00407          PERFORM 00116-DISPLAY-CONTRACT-USES-CO                   ELGGXXD 
00408      SKIP1                                                        ELGGXXD 
00409 *                                                          *      ELGGXXD 
00410 *        DISPLAY EXCEPTION FROM CORPORATE LIST             *      ELGGXXD 
00411 *                                                          *      ELGGXXD 
00412      ELSE                                                         ELGGXXD 
00413          MOVE 'N' TO WS-FIRST-TIME-IND-VAL                        ELGGXXD 
00414          PERFORM 00247-DO-INITIALIZE-TEXT-COMPR                   ELGGXXD 
00415          STRING 'THIS ', SRP-CCP-NAME DELIMITED BY SIZE           ELGGXXD 
00416          WS-RELATED-DIAGNOSES DELIMITED BY SIZE                   ELGGXXD 
00417          WS-RELATED-DIAGNOSESA DELIMITED BY SIZE                  ELGGXXD 
00418         INTO TCAR-FROM-AREA                                       ELGGXXD 
00419          PERFORM 00281-DO-TEXT-COMPRESSION                        ELGGXXD 
00420          MOVE TCAR-TO-SUB  TO  TCAR-L                             ELGGXXD 
00421          MOVE +04  TO  TCAR-OUTPUT-FIELD-COUNT                    ELGGXXD 
00422          MOVE +79  TO  TCAR-OUTPUT-FIELD-1-LEN                    ELGGXXD 
00423                    TCAR-OUTPUT-FIELD-2-LEN                        ELGGXXD 
00424                    TCAR-OUTPUT-FIELD-3-LEN                        ELGGXXD 
00425                    TCAR-OUTPUT-FIELD-4-LEN                        ELGGXXD 
00426          PERFORM 00283-DO-TEXT-UNSTRING                           ELGGXXD 
00427          PERFORM 00252-MOVE-COMPRESSED-PHRASE                     ELGGXXD 
00428          VARYING WS-SUB  FROM  1  BY  1                           ELGGXXD 
00429          UNTIL WS-SUB  GREATER THAN  TCAR-OUTPUT-FIELDS-USED      ELGGXXD 
00430          PERFORM 00255-CALL-OUTPUT.                               ELGGXXD 
00431      SKIP1                                                        ELGGXXD 
00432      EJECT                                                        ELGGXXD 
00433                                                                   ELGGXXD 
00434                                                                   ELGGXXD 
00435 ************************************************************      ELGGXXD 
00436 *                                                          *      ELGGXXD 
00437 *        DISPLAY CONTRACT USES CORPORATE LIST              *      ELGGXXD 
00438 *                                                          *      ELGGXXD 
00439 ************************************************************      ELGGXXD 
00440  00116-DISPLAY-CONTRACT-USES-CO.                                  ELGGXXD 
00441      PERFORM 00247-DO-INITIALIZE-TEXT-COMPR.                      ELGGXXD 
00442      IF WS-FIRST-TIME-THIS-IND                                    ELGGXXD 
00443          PERFORM 00153-TRANSLATE-GPADS-INCLUDEX.                  ELGGXXD 
00444      STRING 'THIS' , SRP-CCP-NAME DELIMITED BY SIZE               ELGGXXD 
00445          ' CONTRACT USES THE CORPORATE ' DELIMITED BY SIZE        ELGGXXD 
00446          SRP-CCP-NAME DELIMITED BY '  '                           ELGGXXD 
00447         ' LIST AND IN ADDITION ' DELIMITED BY SIZE                ELGGXXD 
00448         CMF-DESCR-LINE(1) DELIMITED BY '  '                       ELGGXXD 
00449         ' THE FOLLOWING DIAGNOSES:  ' DELIMITED BY SIZE           ELGGXXD 
00450         INTO TCAR-FROM-AREA.                                      ELGGXXD 
00451      PERFORM 00281-DO-TEXT-COMPRESSION.                           ELGGXXD 
00452      MOVE TCAR-TO-SUB  TO  TCAR-L.                                ELGGXXD 
00453      MOVE +04  TO  TCAR-OUTPUT-FIELD-COUNT.                       ELGGXXD 
00454      MOVE +79  TO  TCAR-OUTPUT-FIELD-1-LEN                        ELGGXXD 
00455                    TCAR-OUTPUT-FIELD-2-LEN                        ELGGXXD 
00456                    TCAR-OUTPUT-FIELD-3-LEN                        ELGGXXD 
00457                    TCAR-OUTPUT-FIELD-4-LEN.                       ELGGXXD 
00458      PERFORM 00283-DO-TEXT-UNSTRING.                              ELGGXXD 
00459      PERFORM 00252-MOVE-COMPRESSED-PHRASE                         ELGGXXD 
00460          VARYING WS-SUB  FROM  1  BY  1                           ELGGXXD 
00461          UNTIL WS-SUB  GREATER THAN  TCAR-OUTPUT-FIELDS-USED.     ELGGXXD 
00462      PERFORM 00255-CALL-OUTPUT.                                   ELGGXXD 
00463      EJECT                                                        ELGGXXD 
00464                                                                   ELGGXXD 
00465                                                                   ELGGXXD 
00466 ************************************************************      ELGGXXD 
00467 *                                                          *      ELGGXXD 
00468 *        TRANSLATE GPADS INCLUDE-EXCLUDE IND               *      ELGGXXD 
00469 *                                                          *      ELGGXXD 
00470 ************************************************************      ELGGXXD 
00471  00153-TRANSLATE-GPADS-INCLUDEX.                                  ELGGXXD 
00472      MOVE 'N'  TO  WS-FIRST-TIME-IND-VAL.                         ELGGXXD 
00473      INITIALIZE TCAR-FROM-AREA.                                   ELGGXXD 
00474      MOVE SRP-TABULAR-ID  TO  CMF-RECORD-PREFIX.                  ELGGXXD 
00475      MOVE 'INCLUDE-EXCLUDE-IND'  TO  CMF-ELEMENT-SYSTEM-NAME.     ELGGXXD 
00476      MOVE GSC-INCLUDE-EXCLUDE-IND(GSC-INDEX)  TO                  ELGGXXD 
00477          CMF-CODE-VALUE.                                          ELGGXXD 
00478      EXEC CICS  LINK  PROGRAM('ELUCMIF')                          ELGGXXD 
00479                       COMMAREA(DFHCOMMAREA)  END-EXEC.            ELGGXXD 
00480      SET CIA-ELSCMDSC-DDN TO TRUE.                                ELGGXXD 
00481      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELGGXXD 
00482          ADDRESS OF CMF-DESCR.                                    ELGGXXD 
00483      EJECT                                                        ELGGXXD 
00484                                                                   ELGGXXD 
00485                                                                   ELGGXXD 
00486 ************************************************************      ELGGXXD 
00487 *                                                          *      ELGGXXD 
00488 *        STRING GPADS DIAGNOSIS AND DESCRIPTION            *      ELGGXXD 
00489 *                                                          *      ELGGXXD 
00490 ************************************************************      ELGGXXD 
00491  00164-STRING-GPADS-DIAGNOSIS-A.                                  ELGGXXD 
00492      SET ADDRESS OF DIAGNOSIS-MSTR-REC TO                         ELGGXXD 
00493                                      ADDRESS OF                   ELGGXXD 
00494          PDB-O-RECORD-AREA.                                       ELGGXXD 
00495      STRING GSC-DIAGNOSIS-ARGUMENT(GSC-INDEX),                    ELGGXXD 
00496             ' ',  DELIMITED BY SIZE,                              ELGGXXD 
00497             DP-DESCRIPT,  DELIMITED BY ' ',                       ELGGXXD 
00498             INTO  TCAR-FROM-AREA.                                 ELGGXXD 
00499      PERFORM 00281-DO-TEXT-COMPRESSION.                           ELGGXXD 
00500      MOVE +74  TO  TCAR-OUTPUT-FIELD-1-LEN                        ELGGXXD 
00501                    TCAR-OUTPUT-FIELD-2-LEN.                       ELGGXXD 
00502      MOVE +2  TO  TCAR-OUTPUT-FIELD-COUNT.                        ELGGXXD 
00503      PERFORM 00283-DO-TEXT-UNSTRING.                              ELGGXXD 
00504      PERFORM 00252-MOVE-COMPRESSED-PHRASE                         ELGGXXD 
00505          VARYING WS-SUB  FROM  1  BY  1                           ELGGXXD 
00506          UNTIL WS-SUB  GREATER THAN  TCAR-OUTPUT-FIELDS-USED.     ELGGXXD 
00507      EJECT                                                        ELGGXXD 
00508                                                                   ELGGXXD 
00509                                                                   ELGGXXD 
00510 ************************************************************      ELGGXXD 
00511 *                                                          *      ELGGXXD 
00512 *        PROCESS OTHER RECORDS                             *      ELGGXXD 
00513 *                                                          *      ELGGXXD 
00514 ************************************************************      ELGGXXD 
00515  00177-PROCESS-OTHER-RECORDS.                                     ELGGXXD 
00516      IF GSD-DIAGNOSIS-ARGUMENT(1)  NOT =  HIGH-VALUES             ELGGXXD 
00517          PERFORM 00186-SAVE-OTHERS-FIRST-I-E-IN                   ELGGXXD 
00518      ELSE PERFORM 00267-EMPTY-COST-CONTAINMENT-T.                 ELGGXXD 
00519      PERFORM 00243-INSERT-BLANK-LINE.                             ELGGXXD 
00520      PERFORM 00188-SEARCH-OTHER-TABLE-FOR-F                       ELGGXXD 
00521          VARYING GSD-INDEX  FROM  1  BY  1                        ELGGXXD 
00522             UNTIL GSD-INDEX  =  GSD-ENTRY-COUNT OR                ELGGXXD 
00523             GSD-DIAGNOSIS-ARGUMENT(GSD-INDEX)  =  HIGH-VALUES.    ELGGXXD 
00524      PERFORM 00243-INSERT-BLANK-LINE.                             ELGGXXD 
00525      MOVE 'Y'  TO  WS-FIRST-TIME-IND-VAL.                         ELGGXXD 
00526      PERFORM 00190-SEARCH-OTHER-TABLE-FOR-O                       ELGGXXD 
00527          VARYING GSD-INDEX  FROM  1  BY  1                        ELGGXXD 
00528             UNTIL GSD-INDEX  =  GSD-ENTRY-COUNT OR                ELGGXXD 
00529             GSD-DIAGNOSIS-ARGUMENT(GSD-INDEX)  =  HIGH-VALUES.    ELGGXXD 
00530      PERFORM 00243-INSERT-BLANK-LINE.                             ELGGXXD 
00531      EJECT                                                        ELGGXXD 
00532                                                                   ELGGXXD 
00533                                                                   ELGGXXD 
00534 ************************************************************      ELGGXXD 
00535 *                                                          *      ELGGXXD 
00536 *        SAVE OTHERS FIRST I-E IND                         *      ELGGXXD 
00537 *                                                          *      ELGGXXD 
00538 ************************************************************      ELGGXXD 
00539  00186-SAVE-OTHERS-FIRST-I-E-IN.                                  ELGGXXD 
00540      MOVE GSD-INCLUDE-EXCLUDE-IND(1)  TO  WS-I-E-IND.             ELGGXXD 
00541      EJECT                                                        ELGGXXD 
00542                                                                   ELGGXXD 
00543                                                                   ELGGXXD 
00544 ************************************************************      ELGGXXD 
00545 *                                                          *      ELGGXXD 
00546 *        SEARCH OTHER TABLE FOR FIRST                      *      ELGGXXD 
00547 *                                                          *      ELGGXXD 
00548 ************************************************************      ELGGXXD 
00549  00188-SEARCH-OTHER-TABLE-FOR-F.                                  ELGGXXD 
00550      IF GSD-INCLUDE-EXCLUDE-IND(GSD-INDEX)  =  WS-I-E-IND         ELGGXXD 
00551          PERFORM 00192-LIST-OTHERS-SERVICE-RELA.                  ELGGXXD 
00552      EJECT                                                        ELGGXXD 
00553                                                                   ELGGXXD 
00554                                                                   ELGGXXD 
00555 ************************************************************      ELGGXXD 
00556 *                                                          *      ELGGXXD 
00557 *        SEARCH OTHER TABLE FOR OTHER THAN FIRST           *      ELGGXXD 
00558 *                                                          *      ELGGXXD 
00559 ************************************************************      ELGGXXD 
00560  00190-SEARCH-OTHER-TABLE-FOR-O.                                  ELGGXXD 
00561      IF GSD-INCLUDE-EXCLUDE-IND(GSD-INDEX)  NOT =  WS-I-E-IND     ELGGXXD 
00562          PERFORM 00192-LIST-OTHERS-SERVICE-RELA.                  ELGGXXD 
00563      EJECT                                                        ELGGXXD 
00564                                                                   ELGGXXD 
00565                                                                   ELGGXXD 
00566 ************************************************************      ELGGXXD 
00567 *                                                          *      ELGGXXD 
00568 *        LIST OTHERS SERVICE RELATED DIAGNOSIS             *      ELGGXXD 
00569 *                                                          *      ELGGXXD 
00570 ************************************************************      ELGGXXD 
00571  00192-LIST-OTHERS-SERVICE-RELA.                                  ELGGXXD 
00572      IF WS-FIRST-TIME-THIS-IND                                    ELGGXXD 
00573          PERFORM 00204-TRANSLATE-OTHERS-INCLUDE.                  ELGGXXD 
00574      MOVE '9'  TO  PDB-I-SERVICE-CODE-SYSTEM-ID.                  ELGGXXD 
00575      MOVE GSD-DIAGNOSIS-ARGUMENT(GSD-INDEX)  TO                   ELGGXXD 
00576           WS-DIAGNOSIS-ARGUMENT.                                  ELGGXXD 
00577      MOVE WS-DIAGNOSIS-ARGUMENT-5 TO                              ELGGXXD 
00578          PDB-I-SERVICE-CODE.                                      ELGGXXD 
00579      MOVE 'PRCDR'  TO  PDB-I-REQUEST-TYPE-N.                      ELGGXXD 
00580      MOVE '00'  TO  PDB-I-VERSION.                                ELGGXXD 
00581      MOVE 'D'  TO  PDB-I-ACCESS-MODE.                             ELGGXXD 
00582      EXEC CICS  LINK  PROGRAM('DBPIOC') COMMAREA(PDB-IO-AREA)     ELGGXXD 
00583          END-EXEC.                                                ELGGXXD 
00584      IF PDB-O-RC-SUCCESSFUL                                       ELGGXXD 
00585          PERFORM 00230-STRING-OTHERS-DIAGNOSISX                   ELGGXXD 
00586      ELSE PERFORM 00262-DIAGNOSIS-FILE-PROBLEM.                   ELGGXXD 
00587      PERFORM 00255-CALL-OUTPUT.                                   ELGGXXD 
00588      EJECT                                                        ELGGXXD 
00589                                                                   ELGGXXD 
00590                                                                   ELGGXXD 
00591 ************************************************************      ELGGXXD 
00592 *                                                          *      ELGGXXD 
00593 *        TRANSLATE OTHERS INCLUDE-EXCLUDE IND              *      ELGGXXD 
00594 *                                                          *      ELGGXXD 
00595 ************************************************************      ELGGXXD 
00596  00204-TRANSLATE-OTHERS-INCLUDE.                                  ELGGXXD 
00597      MOVE 'N'  TO  WS-FIRST-TIME-IND-VAL.                         ELGGXXD 
00598      INITIALIZE TCAR-FROM-AREA.                                   ELGGXXD 
00599      MOVE SRP-TABULAR-ID  TO  CMF-RECORD-PREFIX.                  ELGGXXD 
00600      MOVE 'INCLUDE-EXCLUDE-IND'  TO  CMF-ELEMENT-SYSTEM-NAME.     ELGGXXD 
00601      MOVE GSD-INCLUDE-EXCLUDE-IND(GSD-INDEX)  TO                  ELGGXXD 
00602          CMF-CODE-VALUE.                                          ELGGXXD 
00603      EXEC CICS  LINK  PROGRAM('ELUCMIF')                          ELGGXXD 
00604                       COMMAREA(DFHCOMMAREA)  END-EXEC.            ELGGXXD 
00605      SET CIA-ELSCMDSC-DDN TO TRUE.                                ELGGXXD 
00606      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELGGXXD 
00607          ADDRESS OF CMF-DESCR.                                    ELGGXXD 
00608      STRING 'THIS ',  SRP-CCP-NAME DELIMITED BY '  '              ELGGXXD 
00609             ' PROGRAM  '  DELIMITED BY SIZE                       ELGGXXD 
00610             CMF-DESCR-LINE(1)  DELIMITED BY '  '                  ELGGXXD 
00611             ' THE FOLLOWING DIAGNOSIS CODES:'  DELIMITED BY       ELGGXXD 
00612          SIZE                                                     ELGGXXD 
00613             INTO TCAR-FROM-AREA.                                  ELGGXXD 
00614      PERFORM 00281-DO-TEXT-COMPRESSION.                           ELGGXXD 
00615      MOVE TCAR-TO-SUB  TO  TCAR-L.                                ELGGXXD 
00616      MOVE +04  TO  TCAR-OUTPUT-FIELD-COUNT.                       ELGGXXD 
00617      MOVE +79  TO  TCAR-OUTPUT-FIELD-1-LEN                        ELGGXXD 
00618                    TCAR-OUTPUT-FIELD-2-LEN                        ELGGXXD 
00619                    TCAR-OUTPUT-FIELD-3-LEN                        ELGGXXD 
00620                    TCAR-OUTPUT-FIELD-4-LEN.                       ELGGXXD 
00621      PERFORM 00283-DO-TEXT-UNSTRING.                              ELGGXXD 
00622      PERFORM 00252-MOVE-COMPRESSED-PHRASE                         ELGGXXD 
00623          VARYING WS-SUB  FROM  1  BY  1                           ELGGXXD 
00624          UNTIL WS-SUB  GREATER THAN  TCAR-OUTPUT-FIELDS-USED.     ELGGXXD 
00625      PERFORM 00255-CALL-OUTPUT.                                   ELGGXXD 
00626      EJECT                                                        ELGGXXD 
00627                                                                   ELGGXXD 
00628                                                                   ELGGXXD 
00629 ************************************************************      ELGGXXD 
00630 *                                                          *      ELGGXXD 
00631 *        STRING OTHERS DIAGNOSIS AND DESCRIPTION           *      ELGGXXD 
00632 *                                                          *      ELGGXXD 
00633 ************************************************************      ELGGXXD 
00634  00230-STRING-OTHERS-DIAGNOSISX.                                  ELGGXXD 
00635      SET ADDRESS OF DIAGNOSIS-MSTR-REC TO                         ELGGXXD 
00636                                      ADDRESS OF                   ELGGXXD 
00637          PDB-O-RECORD-AREA.                                       ELGGXXD 
00638      STRING GSD-DIAGNOSIS-ARGUMENT(GSD-INDEX),                    ELGGXXD 
00639             ' ',  DELIMITED BY SIZE,                              ELGGXXD 
00640             DP-DESCRIPT,  DELIMITED BY ' ',                       ELGGXXD 
00641             INTO  TCAR-FROM-AREA.                                 ELGGXXD 
00642      PERFORM 00281-DO-TEXT-COMPRESSION.                           ELGGXXD 
00643      MOVE +74  TO  TCAR-OUTPUT-FIELD-1-LEN                        ELGGXXD 
00644                    TCAR-OUTPUT-FIELD-2-LEN.                       ELGGXXD 
00645      MOVE +2  TO  TCAR-OUTPUT-FIELD-COUNT.                        ELGGXXD 
00646      PERFORM 00283-DO-TEXT-UNSTRING.                              ELGGXXD 
00647      PERFORM 00252-MOVE-COMPRESSED-PHRASE                         ELGGXXD 
00648          VARYING WS-SUB  FROM  1  BY  1                           ELGGXXD 
00649          UNTIL WS-SUB  GREATER THAN  TCAR-OUTPUT-FIELDS-USED.     ELGGXXD 
00650      EJECT                                                        ELGGXXD 
00651                                                                   ELGGXXD 
00652                                                                   ELGGXXD 
00653 ************************************************************      ELGGXXD 
00654 *                                                          *      ELGGXXD 
00655 *        INSERT BLANK LINE                                 *      ELGGXXD 
00656 *                                                          *      ELGGXXD 
00657 ************************************************************      ELGGXXD 
00658  00243-INSERT-BLANK-LINE.                                         ELGGXXD 
00659      ADD  1  TO  COF-NBR-DTL-LINES.                               ELGGXXD 
00660      MOVE SPACES  TO  COF-DTL-LINE(COF-NBR-DTL-LINES).            ELGGXXD 
00661      PERFORM 00255-CALL-OUTPUT.                                   ELGGXXD 
00662      EJECT                                                        ELGGXXD 
00663                                                                   ELGGXXD 
00664                                                                   ELGGXXD 
00665 ************************************************************      ELGGXXD 
00666 *                                                          *      ELGGXXD 
00667 *        DO INITIALIZE TEXT COMPRESSION                    *      ELGGXXD 
00668 *                                                          *      ELGGXXD 
00669 ************************************************************      ELGGXXD 
00670  00247-DO-INITIALIZE-TEXT-COMPR.                                  ELGGXXD 
00671      INITIALIZE TCAR-FROM-LENGTH                                  ELGGXXD 
00672                 TCAR-AREA-LENGTH                                  ELGGXXD 
00673                 TCAR-FROM-SUB                                     ELGGXXD 
00674                 TCAR-FROM-SUB.                                    ELGGXXD 
00675                                                                   ELGGXXD 
00676                                                                   ELGGXXD 
00677 ************************************************************      ELGGXXD 
00678 *                                                          *      ELGGXXD 
00679 *        MOVE COMPRESSED PHRASE                            *      ELGGXXD 
00680 *                                                          *      ELGGXXD 
00681 ************************************************************      ELGGXXD 
00682  00252-MOVE-COMPRESSED-PHRASE.                                    ELGGXXD 
00683      ADD 1  TO  COF-NBR-DTL-LINES.                                ELGGXXD 
00684      MOVE TCAR-OPF-DATA(WS-SUB)  TO                               ELGGXXD 
00685          COF-DTL-LINE(COF-NBR-DTL-LINES).                         ELGGXXD 
00686                                                                   ELGGXXD 
00687                                                                   ELGGXXD 
00688 ************************************************************      ELGGXXD 
00689 *                                                          *      ELGGXXD 
00690 *        CALL OUTPUT                                       *      ELGGXXD 
00691 *                                                          *      ELGGXXD 
00692 ************************************************************      ELGGXXD 
00693  00255-CALL-OUTPUT.                                               ELGGXXD 
00694      EXEC CICS  LINK  PROGRAM('ELUOUTPT')                         ELGGXXD 
00695                       COMMAREA(DFHCOMMAREA)  END-EXEC.            ELGGXXD 
00696      INITIALIZE TCAR-FROM-AREA.                                   ELGGXXD 
00697      EJECT                                                        ELGGXXD 
00698                                                                   ELGGXXD 
00699                                                                   ELGGXXD 
00700 ************************************************************      ELGGXXD 
00701 *                                                          *      ELGGXXD 
00702 *        TABULAR NOT FOUND                                 *      ELGGXXD 
00703 *                                                          *      ELGGXXD 
00704 ************************************************************      ELGGXXD 
00705  00259-TABULAR-NOT-FOUND.                                         ELGGXXD 
00706      SET CIA-AB-NOTFND-GCTABULR  TO  TRUE.                        ELGGXXD 
00707      EXEC CICS  ABEND  ABCODE(CIA-ABCODE)  END-EXEC.              ELGGXXD 
00708      EJECT                                                        ELGGXXD 
00709                                                                   ELGGXXD 
00710                                                                   ELGGXXD 
00711 ************************************************************      ELGGXXD 
00712 *                                                          *      ELGGXXD 
00713 *        DIAGNOSIS FILE PROBLEM                            *      ELGGXXD 
00714 *                                                          *      ELGGXXD 
00715 ************************************************************      ELGGXXD 
00716  00262-DIAGNOSIS-FILE-PROBLEM.                                    ELGGXXD 
00717      MOVE 1  TO  COF-NBR-DTL-LINES.                               ELGGXXD 
00718      STRING 'DIAGNOSIS CODE ''',  PDB-I-SERVICE-CODE,             ELGGXXD 
00719             ''' IS NOT ON FILE'   DELIMITED BY SIZE               ELGGXXD 
00720                            INTO                                   ELGGXXD 
00721          COF-DTL-LINE(COF-NBR-DTL-LINES).                         ELGGXXD 
00722      EJECT                                                        ELGGXXD 
00723                                                                   ELGGXXD 
00724                                                                   ELGGXXD 
00725 ************************************************************      ELGGXXD 
00726 *                                                          *      ELGGXXD 
00727 *        EMPTY COST CONTAINMENT TAB                        *      ELGGXXD 
00728 *                                                          *      ELGGXXD 
00729 ************************************************************      ELGGXXD 
00730  00267-EMPTY-COST-CONTAINMENT-T.                                  ELGGXXD 
00731      MOVE 1  TO  COF-NBR-DTL-LINES.                               ELGGXXD 
00732      MOVE SPACES  TO  COF-DTL-LINE(COF-NBR-DTL-LINES).            ELGGXXD 
00733      MOVE SRP-TABULAR-SLOT-NO  TO  WS-TAB-SLOT-NO.                ELGGXXD 
00734      MOVE 1  TO  COF-NBR-DTL-LINES.                               ELGGXXD 
00735      STRING 'THIS ',  SRP-CCP-NAME DELIMITED BY '  '              ELGGXXD 
00736             ' WITH TABULAR SLOT NO. ', WS-TAB-SLOT-NO,            ELGGXXD 
00737             ' HAS AN EMPTY TABULAR RECORD '  DELIMITED BY SIZE    ELGGXXD 
00738             INTO  COF-DTL-LINE(COF-NBR-DTL-LINES).                ELGGXXD 
00739      PERFORM 00255-CALL-OUTPUT.                                   ELGGXXD 
00740      PERFORM 00044-TERMINATION-ROUTINE.                           ELGGXXD 
00741      EJECT                                                        ELGGXXD 
00742                                                                   ELGGXXD 
00743                                                                   ELGGXXD 
00744 ************************************************************      ELGGXXD 
00745 *                                                          *      ELGGXXD 
00746 *        COMMAREA LENGTH ERROR                             *      ELGGXXD 
00747 *                                                          *      ELGGXXD 
00748 ************************************************************      ELGGXXD 
00749  00278-COMMAREA-LENGTH-ERROR.                                     ELGGXXD 
00750      SET CIA-AB-DFHCOMMAREA  TO  TRUE.                            ELGGXXD 
00751      EXEC CICS  ABEND  ABCODE(CIA-ABCODE) END-EXEC.               ELGGXXD 
00752                                                                   ELGGXXD 
00753                                                                   ELGGXXD 
00754 ************************************************************      ELGGXXD 
00755 *                                                          *      ELGGXXD 
00756 *        DO TEXT COMPRESSION                               *      ELGGXXD 
00757 *                                                          *      ELGGXXD 
00758 ************************************************************      ELGGXXD 
00759  00281-DO-TEXT-COMPRESSION.                                       ELGGXXD 
00760      CALL 'ELUTCOMP' USING TCAR-COMPRESSION-WORK-AREA.            ELGGXXD 
00761                                                                   ELGGXXD 
00762                                                                   ELGGXXD 
00763 ************************************************************      ELGGXXD 
00764 *                                                          *      ELGGXXD 
00765 *        DO TEXT UNSTRING                                  *      ELGGXXD 
00766 *                                                          *      ELGGXXD 
00767 ************************************************************      ELGGXXD 
00768  00283-DO-TEXT-UNSTRING.                                          ELGGXXD 
00769      CALL 'ELUTUNST' USING TCAR-COMPRESSION-WORK-AREA.            ELGGXXD 
