00001 *      LAST MAINTENANCE TIME: 10.29.17  DATE: 05/04/88            06/29/02
00002 * GENERATED BY STRUCTURE(S) CODE GENERATOR V2.0                   ELTMEDCA
00003 *     ON 88/05/04 AT 10:29:02.74                                     LV001
00004 * STRUCTURE(S) MEMBER ELTMEDCAPW - LEVEL 040 AS OF 05/04/88       ELTMEDCA
00005 * FROM PANLIB R360059.STRUCTPL.PANLIB                             ELTMEDCA
00006 *                                                                 ELTMEDCA
00007  IDENTIFICATION DIVISION.                                         ELTMEDCA
00008                                                                   ELTMEDCA
00009  PROGRAM-ID.         ELTMEDCA.                                    ELTMEDCA
00010                                                                   ELTMEDCA
00011  AUTHOR.             EDWARD G LISS                                ELTMEDCA
00012                                                                   ELTMEDCA
00013  INSTALLATION.       HEALTH CARE SERVICE CORPORATION              ELTMEDCA
00014                      A MUTUAL LEGAL RESERVE COMPANY               ELTMEDCA
00015                      BLUE CROSS/BLUE SHIELD OF ILLINOIS           ELTMEDCA
00016                      233 N. MICHIGAN AVE                          ELTMEDCA
00017                      CHICAGO, ILLINOIS 60601                      ELTMEDCA
00018                                                                   ELTMEDCA
00019  DATE-WRITTEN.       09-APR-1987.                                 ELTMEDCA
00020                                                                   ELTMEDCA
00021  DATE-COMPILED.                                                   ELTMEDCA
00022                                                                   ELTMEDCA
00023  SECURITY.           COPYRIGHT 1987,                              ELTMEDCA
00024                      HEALTH CARE SERVICE CORPORATION              ELTMEDCA
00025      SKIP3                                                        ELTMEDCA
00026  ENVIRONMENT DIVISION.                                            ELTMEDCA
00027                                                                   ELTMEDCA
00028  CONFIGURATION SECTION.                                           ELTMEDCA
00029  SOURCE-COMPUTER.    IBM-3033.                                    ELTMEDCA
00030  OBJECT-COMPUTER.    IBM-3033.                                    ELTMEDCA
00031      EJECT                                                        ELTMEDCA
00032 ******************************************************************ELTMEDCA
00033 *                                                                *ELTMEDCA
00034 *    PROGRAM:    ELTMEDCA                                        *ELTMEDCA
00035 *    DATE:       09-APR-1987                                     *ELTMEDCA
00036 *    AUTHOR:     EDWARD G LISS                                   *ELTMEDCA
00037 *    FUNCTION:                                                   *ELTMEDCA
00038 *      THIS MODULE WILL CREATE TRANSLATED SCREEN RECORDS FOR     *ELTMEDCA
00039 *      THE MEDICATE TOPIC DISPLAY.                               *ELTMEDCA
00040 *                                                                *ELTMEDCA
00041 ******************************************************************ELTMEDCA
00042 *                                                                *ELTMEDCA
00043 *                      MAINTENANCE HISTORY                       *ELTMEDCA
00044 *                                                                *ELTMEDCA
00045 *  MOD     DATE     BY  DRPT                ACTION               *ELTMEDCA
00046 * ----- ----------- --- ----- ---------------------------------- *ELTMEDCA
00047 * 01.00 09-APR-1987 EGL       CREATED                            *ELTMEDCA
00048 *                                                                *ELTMEDCA
00049 * 01.01 02-MAY-1988 REB       RENAMED THE INCLUDE MEMBER IN HERE *ELTMEDCA
00050 *                                                                *ELTMEDCA
00051 * 01.02 03-MAY-1988 REB       CONVERTING TOPIC'S OUTPUT TO A TWO *ELTMEDCA
00052 *                             COLUMN FORMAT WITH A BAR DIVIDING  *ELTMEDCA
00053 *                             IT.                                *ELTMEDCA
00054 *                                                                *ELTMEDCA
00055 * 01.03 03-MAY-1988 REB       FIXED THE TERMINATE SECTION ALSO   *ELTMEDCA
00056 *                             ADDED NEEDED PUNCTUATION.          *ELTMEDCA
00057 *                                                                *ELTMEDCA
00058 * 01.04 04-MAY-1988 REB       CHANGED NAME OF A HEADING          *ELTMEDCA
00059 *                                                                *ELTMEDCA
00060 * 01.05 09-NOV-1992 GEM       STORAGE MANAGEMENT ENHANCEMENTS    *ELTMEDCA
00061 *                                                                *ELTMEDCA
00062 * 01.06 27-APR-1994 AKK       CHANGE PLACEMENT OF NEW PAGE, WHEN *ELTMEDCA
00063 *                             THERE ARE NO GRP SPECIFIC MEDICARE *ELTMEDCA
00064 *                             ELEMENTS CODED.                    *ELTMEDCA
00065 *                                                                *ELTMEDCA
00066 * 01.07 24-AUG-1994 AKK       GETTING EL12 ABEND WHEN A PROFESS  *ELTMEDCA
00067 *                             IONAL PROVIDER IS CHOSEN AND NO    *ELTMEDCA
00068 *                             BS CONTRACT EXSISTS.  CORRECTED.   *ELTMEDCA
00069 ******************************************************************ELTMEDCA
00070      EJECT                                                        ELTMEDCA
00071  DATA DIVISION.                                                   ELTMEDCA
00072  WORKING-STORAGE SECTION.                                         ELTMEDCA
00073  01  WS-MISC.                                                     ELTMEDCA
00074      05  FILLER                   PIC X(24) VALUE                 ELTMEDCA
00075      'WORKING STORAGE ELTMEDCA'.                                  ELTMEDCA
00076      05  WS-RETURN-CODE           PIC X.                          ELTMEDCA
00077 ******** IN BLOCK BELOW, CODE STUCTURE MUST BE SAME ********      ELTMEDCA
00078      05  WS-INSTITUTIONAL-SW      PIC X VALUE 'N'.                ELTMEDCA
00079          88  INST-ONLY                  VALUE 'Y'.                ELTMEDCA
00080          88  NOT-INST-ONLY              VALUE 'N'.                ELTMEDCA
00081      05  WS-ACCEPT-CONTRACT-SW    PIC X VALUE 'N'.                ELTMEDCA
00082          88  WS-ACCEPT-CONTRACT         VALUE 'Y'.                ELTMEDCA
00083          88  WS-REJECT-CONTRACT         VALUE 'N'.                ELTMEDCA
00084      05  WS-GS-MCARE-SW           PIC X VALUE 'N'.                ELTMEDCA
00085          88  GS-MCARE-EXIST             VALUE 'Y'.                ELTMEDCA
00086          88  GS-MCARE-NOT-EXIST         VALUE 'N'.                ELTMEDCA
00087      05  WS-IB-CON-MCARE-SW       PIC X VALUE 'N'.                ELTMEDCA
00088          88  IB-CON-MCARE-EXIST         VALUE 'Y'.                ELTMEDCA
00089          88  IB-CON-MCARE-NOT-EXIST     VALUE 'N'.                ELTMEDCA
00090      05  WS-PB-CON-MCARE-SW       PIC X VALUE 'N'.                ELTMEDCA
00091          88  PB-CON-MCARE-EXIST         VALUE 'Y'.                ELTMEDCA
00092          88  PB-CON-MCARE-NOT-EXIST     VALUE 'N'.                ELTMEDCA
00093      05  WS-IS-CON-MCARE-SW       PIC X VALUE 'N'.                ELTMEDCA
00094          88  IS-CON-MCARE-EXIST         VALUE 'Y'.                ELTMEDCA
00095          88  IS-CON-MCARE-NOT-EXIST     VALUE 'N'.                ELTMEDCA
00096      05  WS-PS-CON-MCARE-SW       PIC X VALUE 'N'.                ELTMEDCA
00097          88  PS-CON-MCARE-EXIST         VALUE 'Y'.                ELTMEDCA
00098          88  PS-CON-MCARE-NOT-EXIST     VALUE 'N'.                ELTMEDCA
00099 ******** IN BLOCK ABOVE, CODE STUCTURE MUST BE SAME ********      ELTMEDCA
00100      05  WS-PROGRAM-STATUS        PIC X VALUE 'N'.                ELTMEDCA
00101          88  WS-TERMINATE-PGM           VALUE 'Y'.                ELTMEDCA
00102          88  WS-CONTINUE-PGM            VALUE 'N'.                ELTMEDCA
00103      05  WS-PROVIDER-TYPE-TABLE.                                  ELTMEDCA
00104          10  WS-INST-BASIC        PIC X(28) VALUE                 ELTMEDCA
00105                         'INSTITUTIONAL BASIC :'.                  ELTMEDCA
00106          10  WS-INST-SUPP         PIC X(28) VALUE                 ELTMEDCA
00107                         'INSTITUTIONAL SUPPLEMENTAL :'.           ELTMEDCA
00108          10  WS-PROF-BASIC        PIC X(28) VALUE                 ELTMEDCA
00109                         'PROFESSIONAL BASIC :'.                   ELTMEDCA
00110          10  WS-PROF-SUPP         PIC X(28) VALUE                 ELTMEDCA
00111                         'PROFESSIONAL SUPPLEMENTAL :'.            ELTMEDCA
00112      05  WS-NO-MCARE-VAR-1.                                       ELTMEDCA
00113          10  FILLER               PIC X(37) VALUE                 ELTMEDCA
00114            'THIS CONTRACT DOES NOT HAVE MEDICARE'.                ELTMEDCA
00115      05  WS-NO-MCARE-VAR-2.                                       ELTMEDCA
00116          10  FILLER               PIC X(15) VALUE                 ELTMEDCA
00117            'CONSIDERATIONS.'.                                     ELTMEDCA
00118      05  WS-NON-MCARE-ERR-1.                                      ELTMEDCA
00119          10  FILLER               PIC X(51) VALUE                 ELTMEDCA
00120            'NON-MEDICARE CONTRACT WAS SPECIFIED FOR DISPLAYING '. ELTMEDCA
00121          10  FILLER               PIC X(20) VALUE                 ELTMEDCA
00122            'MEDICARE BENEFITS. '.                                 ELTMEDCA
00123      05  WS-NON-MCARE-ERR-2.                                      ELTMEDCA
00124          10  FILLER               PIC X(50) VALUE                 ELTMEDCA
00125             'PRESS PF9 AND RE-SELECT FAMILY RELATIONSHIP OF MED'. ELTMEDCA
00126          10  FILLER               PIC X(23) VALUE                 ELTMEDCA
00127             'ICARE ELIGIBLE AND NOT '.                            ELTMEDCA
00128      05  WS-NON-MCARE-ERR-3.                                      ELTMEDCA
00129          10  FILLER               PIC X(50) VALUE                 ELTMEDCA
00130             'T.E.F.R.A. TO DISPLAY MEDICARE BENEFITS.          '. ELTMEDCA
00131      05  WS-INST-ONLY.                                            ELTMEDCA
00132          10  FILLER               PIC X(47) VALUE                 ELTMEDCA
00133          'THE GROUP/CONTRACT DOES NOT COVER PROFESSIONAL'.        ELTMEDCA
00134      05  WS-INST-ONLY1.                                           ELTMEDCA
00135          10  FILLER               PIC X(09) VALUE                 ELTMEDCA
00136          'SERVICES.'.                                             ELTMEDCA
00137      05  WS-NO-PROF.                                              ELTMEDCA
00138          10  FILLER               PIC X(58) VALUE                 ELTMEDCA
00139       'THE GROUP/CONTRACT DOES NOT COVER PROFESSIONAL SERVICES.'. ELTMEDCA
00140 ***************************************************************   ELTMEDCA
00141 **** H E A D E R  L I N E S                                       ELTMEDCA
00142 ***************************************************************   ELTMEDCA
00143  01  WS-HEADER-LINES.                                             ELTMEDCA
00144                                                                   ELTMEDCA
00145      05  WS-HDR-LIN-3.                                            ELTMEDCA
00146        10  FILLER                 PIC X(43) VALUE                 ELTMEDCA
00147            'THE FOLLOWING DISPLAYED BENEFITS ARE FOR: '.          ELTMEDCA
00148        10  FILLER                 PIC X(09) VALUE                 ELTMEDCA
00149            'MEDICARE '.                                           ELTMEDCA
00150        10  WS-HDRLIN3-IP-PP-AP    PIC X(23) VALUE SPACES.         ELTMEDCA
00151        10  FILLER                 PIC X(04) VALUE SPACES.         ELTMEDCA
00152 **************************************************************    ELTMEDCA
00153 *** SCREEN BODY LINES                                             ELTMEDCA
00154 **************************************************************    ELTMEDCA
00155  01  WS-SCRN-LINS-AREA.                                           ELTMEDCA
00156      05  WS-BENEFITS-MUST         PIC X(30) VALUE                 ELTMEDCA
00157             'BENEFITS MUST '.                                     ELTMEDCA
00158      05  WS-MCARE-EXP-1           PIC X(30) VALUE                 ELTMEDCA
00159           'MEDICARE EXPLANATION OF '.                             ELTMEDCA
00160      05  WS-MCARE-EXP-2           PIC X(30) VALUE                 ELTMEDCA
00161           'BENEFITS REQUIREMENT '.                                ELTMEDCA
00162      05  WS-RESERVE-DAYS-1        PIC X(30) VALUE                 ELTMEDCA
00163           'MEDICARE LIFETIME RESERVE '.                           ELTMEDCA
00164      05  WS-RESERVE-DAYS-2        PIC X(30) VALUE                 ELTMEDCA
00165           'DAY REQUIREMENTS       '.                              ELTMEDCA
00166      05  WS-DRG-1                 PIC X(30) VALUE                 ELTMEDCA
00167          'MEDICARE DIAGNOSIS RELATED '.                           ELTMEDCA
00168      05  WS-DRG-2                 PIC X(30) VALUE                 ELTMEDCA
00169          'GROUP (DRG) '.                                          ELTMEDCA
00170                                                                   ELTMEDCA
00171      05  WS-MCARE-SUPL.                                           ELTMEDCA
00172          10  FILLER               PIC X(27) VALUE                 ELTMEDCA
00173              'WHEN SUPPLEMENTING MEDICARE'.                       ELTMEDCA
00174          10  WS-QUOTE             PIC X     VALUE QUOTE.          ELTMEDCA
00175          10  WS-PAYMENT           PIC X(11) VALUE                 ELTMEDCA
00176              'S PAYMENT. '.                                       ELTMEDCA
00177                                                                   ELTMEDCA
00178      05  WS-HCSC-CVRGE.                                           ELTMEDCA
00179          10  WS-HCSC-1            PIC X(43) VALUE                 ELTMEDCA
00180          'THE TYPE OF HCSC COVERAGE THAT COORDINATES '.           ELTMEDCA
00181          10  WS-HCSC-2            PIC X(17) VALUE                 ELTMEDCA
00182          'WITH MEDICARE IS '.                                     ELTMEDCA
00183          10  WS-MCARE-TYPE-MSG1   PIC X(19) VALUE SPACES.         ELTMEDCA
00184                                                                   ELTMEDCA
00185      05  WS-PERIOD                PIC X(01) VALUE '.'.            ELTMEDCA
00186      05  WS-BAR                   PIC X(01) VALUE '|'.            ELTMEDCA
00187      05  WS-MASK-LINE.                                            ELTMEDCA
00188          10  FILLER               PIC X(30) VALUE SPACES.         ELTMEDCA
00189          10  FILLER               PIC X(01) VALUE '|'.            ELTMEDCA
00190                                                                   ELTMEDCA
00191  01  WS-SWITCH.                                                   ELTMEDCA
00192      05  WS-PERIOD-SW             PIC X(01)   VALUE 'P'.          ELTMEDCA
00193          88  INSERT-PERIOD                    VALUE 'P'.          ELTMEDCA
00194          88  NO-PERIOD-NEEDED                 VALUE 'N'.          ELTMEDCA
00195                                                                   ELTMEDCA
00196  01  WS-OUTPUT-AREA.                                              ELTMEDCA
00197      05  WS-HEADINGS-CNT          PIC S9(04)  VALUE +0  COMP-3.   ELTMEDCA
00198      05  WS-LINE-CNT              PIC S9(04)  VALUE +0  COMP-3.   ELTMEDCA
00199      05  WS-OUTPUT                PIC X(1580) VALUE SPACES.       ELTMEDCA
00200      05  WS-OUTPUT-ENTRY REDEFINES WS-OUTPUT                      ELTMEDCA
00201                                   OCCURS 20 TIMES                 ELTMEDCA
00202                                   INDEXED BY WS-OUTPUT-IDX.       ELTMEDCA
00203          10  WS-OUTPUT-LINE.                                      ELTMEDCA
00204              15  WS-HEADING       PIC X(30).                      ELTMEDCA
00205              15  WS-DIVIDER       PIC X(01).                      ELTMEDCA
00206              15  FILLER           PIC X(02).                      ELTMEDCA
00207              15  WS-TEXT          PIC X(46).                      ELTMEDCA
00208                                                                   ELTMEDCA
00209 /                                                                 ELTMEDCA
00210  LINKAGE SECTION.                                                 ELTMEDCA
00211  01  DFHCOMMAREA.                                                 ELTMEDCA
00212      COPY ELSCOMMC.                                               ELTMEDCA
00213 /                                                                 ELTMEDCA
00214      COPY ELSCIA2C.                                               ELTMEDCA
00215 /                                                                 ELTMEDCA
00216      COPY ELSCMDSC.                                               ELTMEDCA
00217 /                                                                 ELTMEDCA
00218      COPY ELSCMIFC.                                               ELTMEDCA
00219 /                                                                 ELTMEDCA
00220      COPY ELSKEYSC.                                               ELTMEDCA
00221 /                                                                 ELTMEDCA
00222      COPY ELSOUTPC.                                               ELTMEDCA
00223 /                                                                 ELTMEDCA
00224      COPY ELSSRTPC.                                               ELTMEDCA
00225 /                                                                 ELTMEDCA
00226      COPY ELSSSCBC.                                               ELTMEDCA
00227 /                                                                 ELTMEDCA
00228      COPY ELSTCWAC.                                               ELTMEDCA
00229 /                                                                 ELTMEDCA
00230  01  GROUP-SPECIFIC-REC.                                          ELTMEDCA
00231      COPY GCGROUPC.                                               ELTMEDCA
00232 /                                                                 ELTMEDCA
00233  01  CONTRACT-RECORD-AREA.                                        ELTMEDCA
00234      COPY GCCONTRC.                                               ELTMEDCA
00235 /                                                                 ELTMEDCA
00236      EJECT                                                        ELTMEDCA
00237  PROCEDURE DIVISION.                                              ELTMEDCA
00238 ************************************************************      ELTMEDCA
00239 *                                                          *      ELTMEDCA
00240 *                    PROCEDURE DIVISION                    *      ELTMEDCA
00241 *                                                          *      ELTMEDCA
00242 ************************************************************      ELTMEDCA
00243                                                                   ELTMEDCA
00244                                                                   ELTMEDCA
00245 ************************************************************      ELTMEDCA
00246 *                                                          *      ELTMEDCA
00247 *        PROCESS MEDICARE TOPIC                            *      ELTMEDCA
00248 *                                                          *      ELTMEDCA
00249 ************************************************************      ELTMEDCA
00250  00001-PROCESS-MEDICARE-TOPIC.                                    ELTMEDCA
00251      PERFORM 00006-INITIALIZE-PROGRAM.                            ELTMEDCA
00252      IF WS-CONTINUE-PGM                                           ELTMEDCA
00253          PERFORM 00109-MAIN-PROCESSING.                           ELTMEDCA
00254      IF GCG-L-O-B-CONTRACT-LEVEL-IND = '01'                       ELTMEDCA
00255         SET INST-ONLY TO TRUE                                     ELTMEDCA
00256      END-IF.                                                      ELTMEDCA
00257      IF INST-ONLY AND                                             ELTMEDCA
00258           SSB-PROV-CLASS-PROF                                     ELTMEDCA
00259         PERFORM 00299-TRMNT-INST-ONLY-TYPE                        ELTMEDCA
00260      ELSE                                                         ELTMEDCA
00261          PERFORM 00286-TERMINATE-TEXT-DISPLAYED                   ELTMEDCA
00262      END-IF.                                                      ELTMEDCA
00263      SKIP1                                                        ELTMEDCA
00264 *                                                          *      ELTMEDCA
00265 *        ISSUE THE RETURN                                  *      ELTMEDCA
00266 *                                                          *      ELTMEDCA
00267          EXEC CICS RETURN                                         ELTMEDCA
00268        END-EXEC                                                   ELTMEDCA
00269          GOBACK.                                                  ELTMEDCA
00270      SKIP1                                                        ELTMEDCA
00271                                                                   ELTMEDCA
00272                                                                   ELTMEDCA
00273 ************************************************************      ELTMEDCA
00274 *                                                          *      ELTMEDCA
00275 *        INITIALIZE PROGRAM                                *      ELTMEDCA
00276 *                                                          *      ELTMEDCA
00277 ************************************************************      ELTMEDCA
00278  00006-INITIALIZE-PROGRAM.                                        ELTMEDCA
00279      IF EIBCALEN = LENGTH OF DFHCOMMAREA                          ELTMEDCA
00280          PERFORM 00012-ESTABLISH-ADDRESSABILITY                   ELTMEDCA
00281      SKIP1                                                        ELTMEDCA
00282 *                                                          *      ELTMEDCA
00283 *        ABEND DUE TO INVALID COMMAREA                     *      ELTMEDCA
00284 *                                                          *      ELTMEDCA
00285      ELSE                                                         ELTMEDCA
00286          EXEC CICS ABEND                                          ELTMEDCA
00287                ABCODE('EL01')                                     ELTMEDCA
00288         END-EXEC.                                                 ELTMEDCA
00289      SKIP1                                                        ELTMEDCA
00290      IF INST-ONLY                                                 ELTMEDCA
00291         SET WS-TERMINATE-PGM TO TRUE                              ELTMEDCA
00292      ELSE                                                         ELTMEDCA
00293         PERFORM 00029-DETERMINE-PROVIDER-CLASS                    ELTMEDCA
00294         MOVE WS-MASK-LINE        TO COF-MASK-LINE                 ELTMEDCA
00295         PERFORM 00040-VERIFY-MEDICARE-REQUEST                     ELTMEDCA
00296      END-IF.                                                      ELTMEDCA
00297      EJECT                                                        ELTMEDCA
00298                                                                   ELTMEDCA
00299                                                                   ELTMEDCA
00300 ************************************************************      ELTMEDCA
00301 *                                                          *      ELTMEDCA
00302 *        ESTABLISH ADDRESSABILITY                          *      ELTMEDCA
00303 *                                                          *      ELTMEDCA
00304 ************************************************************      ELTMEDCA
00305  00012-ESTABLISH-ADDRESSABILITY.                                  ELTMEDCA
00306      CALL 'ELUINISM' USING DFHCOMMAREA                            ELTMEDCA
00307          ADDRESS OF CIA-ELS-COMMON-INTERFACE-AREA.                ELTMEDCA
00308      IF NOT CIA-RC-OK                                             ELTMEDCA
00309         SET CIA-AB-ELSCIA-PTR TO TRUE                             ELTMEDCA
00310         EXEC CICS ABEND ABCODE (CIA-ABCODE) END-EXEC.             ELTMEDCA
00311                                                                   ELTMEDCA
00312      SET CIA-ELSGRPSP-DDN TO TRUE.                                ELTMEDCA
00313      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELTMEDCA
00314          ADDRESS OF GROUP-SPECIFIC-REC.                           ELTMEDCA
00315      IF NOT CIA-RC-OK                                             ELTMEDCA
00316         PERFORM 00999-SIGNAL-UNALL-AREA-ERROR.                    ELTMEDCA
00317                                                                   ELTMEDCA
00318      SET CIA-ELSSSCB-DDN TO TRUE.                                 ELTMEDCA
00319      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELTMEDCA
00320          ADDRESS OF SSB-SELECTOR-STATUS-CTL-BLK.                  ELTMEDCA
00321      IF NOT CIA-RC-OK                                             ELTMEDCA
00322         PERFORM 00999-SIGNAL-UNALL-AREA-ERROR.                    ELTMEDCA
00323                                                                   ELTMEDCA
00324      SET CIA-ELSCMIF-DDN TO TRUE.                                 ELTMEDCA
00325      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELTMEDCA
00326          ADDRESS OF CMF-CODES-MANUAL-INTERFACE.                   ELTMEDCA
00327      IF NOT CIA-RC-OK                                             ELTMEDCA
00328         PERFORM 00999-SIGNAL-UNALL-AREA-ERROR.                    ELTMEDCA
00329                                                                   ELTMEDCA
00330      SET CIA-ELSOUTP-DDN TO TRUE.                                 ELTMEDCA
00331      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELTMEDCA
00332          ADDRESS OF COF-OUTPUT-INTERFACE.                         ELTMEDCA
00333      IF NOT CIA-RC-OK                                             ELTMEDCA
00334         PERFORM 00999-SIGNAL-UNALL-AREA-ERROR.                    ELTMEDCA
00335                                                                   ELTMEDCA
00336 *    SET CIA-ELSCMDSC-DDN TO TRUE.                                ELTMEDCA
00337 *    CALL 'ELUSETAD' USING DFHCOMMAREA                            ELTMEDCA
00338 *        ADDRESS OF CMF-DESCR.                                    ELTMEDCA
00339 *    IF NOT CIA-RC-OK                                             ELTMEDCA
00340         IF GCG-L-O-B-CONTRACT-LEVEL-IND = '01'                    ELTMEDCA
00341            AND SSB-PROV-CLASS-PROF                                ELTMEDCA
00342              PERFORM 1999-SIGNAL-INST-ONLY-COVERAGE               ELTMEDCA
00343              SET INST-ONLY TO TRUE                                ELTMEDCA
00344 *       ELSE                                                      ELTMEDCA
00345 *          PERFORM 00999-SIGNAL-UNALL-AREA-ERROR                  ELTMEDCA
00346 *       END-IF                                                    ELTMEDCA
00347         ELSE                                                      ELTMEDCA
00348            PERFORM 0014-FINISH-ADDRESSING                         ELTMEDCA
00349         END-IF.                                                   ELTMEDCA
00350                                                                   ELTMEDCA
00351  0014-FINISH-ADDRESSING.                                          ELTMEDCA
00352      SET CIA-ELSKEYS-DDN TO TRUE.                                 ELTMEDCA
00353      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELTMEDCA
00354          ADDRESS OF KWA-FILE-KEY-WORK-AREA.                       ELTMEDCA
00355      IF NOT CIA-RC-OK                                             ELTMEDCA
00356         PERFORM 00999-SIGNAL-UNALL-AREA-ERROR.                    ELTMEDCA
00357                                                                   ELTMEDCA
00358      SET CIA-ELSTCWA-DDN TO TRUE.                                 ELTMEDCA
00359      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELTMEDCA
00360          ADDRESS OF TCAR-COMPRESSION-WORK-AREA.                   ELTMEDCA
00361      IF NOT CIA-RC-OK                                             ELTMEDCA
00362         PERFORM 00999-SIGNAL-UNALL-AREA-ERROR.                    ELTMEDCA
00363                                                                   ELTMEDCA
00364      EJECT                                                        ELTMEDCA
00365                                                                   ELTMEDCA
00366                                                                   ELTMEDCA
00367 ************************************************************      ELTMEDCA
00368 *                                                          *      ELTMEDCA
00369 *        DETERMINE PROVIDER CLASS TITLE                    *      ELTMEDCA
00370 *                                                          *      ELTMEDCA
00371 ************************************************************      ELTMEDCA
00372  00029-DETERMINE-PROVIDER-CLASS.                                  ELTMEDCA
00373      IF  SSB-PROV-CLASS-INST                                      ELTMEDCA
00374          PERFORM 00034-USE-PROV-CLASS-INST                        ELTMEDCA
00375      ELSE IF SSB-PROV-CLASS-BOTH                                  ELTMEDCA
00376          PERFORM 00036-USE-PROV-CLASS-BOTH                        ELTMEDCA
00377      ELSE IF  SSB-PROV-CLASS-PROF                                 ELTMEDCA
00378          PERFORM 00038-USE-PROV-CLASS-PROF                        ELTMEDCA
00379      SKIP1                                                        ELTMEDCA
00380 *                                                          *      ELTMEDCA
00381 *        ABEND DUE TO INVALID PROV CLASS                   *      ELTMEDCA
00382 *                                                          *      ELTMEDCA
00383      ELSE                                                         ELTMEDCA
00384          SET CIA-AB-UNDEF TO TRUE                                 ELTMEDCA
00385          EXEC CICS ABEND                                          ELTMEDCA
00386                ABCODE(CIA-ABCODE)                                 ELTMEDCA
00387         END-EXEC.                                                 ELTMEDCA
00388      SKIP1                                                        ELTMEDCA
00389                                                                   ELTMEDCA
00390                                                                   ELTMEDCA
00391 ************************************************************      ELTMEDCA
00392 *                                                          *      ELTMEDCA
00393 *        USE PROV CLASS INST                               *      ELTMEDCA
00394 *                                                          *      ELTMEDCA
00395 ************************************************************      ELTMEDCA
00396  00034-USE-PROV-CLASS-INST.                                       ELTMEDCA
00397      MOVE 'INSTITUTIONAL PROVIDERS'    TO WS-HDRLIN3-IP-PP-AP.    ELTMEDCA
00398                                                                   ELTMEDCA
00399                                                                   ELTMEDCA
00400 ************************************************************      ELTMEDCA
00401 *                                                          *      ELTMEDCA
00402 *        USE PROV CLASS BOTH                               *      ELTMEDCA
00403 *                                                          *      ELTMEDCA
00404 ************************************************************      ELTMEDCA
00405  00036-USE-PROV-CLASS-BOTH.                                       ELTMEDCA
00406      IF GCG-L-O-B-CONTRACT-LEVEL-IND = '01'                       ELTMEDCA
00407          MOVE 'INSTITUTIONAL PROVIDERS'   TO WS-HDRLIN3-IP-PP-AP  ELTMEDCA
00408      ELSE                                                         ELTMEDCA
00409         MOVE 'ALL PROVIDERS'              TO WS-HDRLIN3-IP-PP-AP  ELTMEDCA
00410      END-IF.                                                      ELTMEDCA
00411                                                                   ELTMEDCA
00412                                                                   ELTMEDCA
00413 ************************************************************      ELTMEDCA
00414 *                                                          *      ELTMEDCA
00415 *        USE PROV CLASS PROF                               *      ELTMEDCA
00416 *                                                          *      ELTMEDCA
00417 ************************************************************      ELTMEDCA
00418  00038-USE-PROV-CLASS-PROF.                                       ELTMEDCA
00419      MOVE 'PROFESSIONAL PROVIDERS'     TO WS-HDRLIN3-IP-PP-AP.    ELTMEDCA
00420      EJECT                                                        ELTMEDCA
00421                                                                   ELTMEDCA
00422                                                                   ELTMEDCA
00423 ************************************************************      ELTMEDCA
00424 *                                                          *      ELTMEDCA
00425 *        VERIFY MEDICARE REQUEST                           *      ELTMEDCA
00426 *                                                          *      ELTMEDCA
00427 ************************************************************      ELTMEDCA
00428  00040-VERIFY-MEDICARE-REQUEST.                                   ELTMEDCA
00429      IF SSB-MEDCA-INELIG                                          ELTMEDCA
00430          PERFORM 00043-REJECT-INELIGABLE-REQUES.                  ELTMEDCA
00431      IF WS-CONTINUE-PGM                                           ELTMEDCA
00432          PERFORM 00056-VERIFY-MEDICARE-EXISTANC.                  ELTMEDCA
00433                                                                   ELTMEDCA
00434                                                                   ELTMEDCA
00435 ************************************************************      ELTMEDCA
00436 *                                                          *      ELTMEDCA
00437 *        REJECT INELIGABLE REQUEST                         *      ELTMEDCA
00438 *                                                          *      ELTMEDCA
00439 ************************************************************      ELTMEDCA
00440  00043-REJECT-INELIGABLE-REQUES.                                  ELTMEDCA
00441      SKIP1                                                        ELTMEDCA
00442 *                                                          *      ELTMEDCA
00443 *        ISSUE REJECT INELIGABLE PAGE                      *      ELTMEDCA
00444 *                                                          *      ELTMEDCA
00445          SET COF-NEW-PAGE        TO TRUE                          ELTMEDCA
00446          MOVE +3                 TO COF-NBR-HDR-LINES             ELTMEDCA
00447          MOVE WS-HDR-LIN-3       TO COF-HDR-LINE (2)              ELTMEDCA
00448          MOVE ALL '-'            TO COF-HDR-LINE (3)              ELTMEDCA
00449          MOVE WS-NON-MCARE-ERR-1 TO COF-DTL-LINE (1)              ELTMEDCA
00450          MOVE WS-NON-MCARE-ERR-2 TO COF-DTL-LINE (2)              ELTMEDCA
00451          MOVE WS-NON-MCARE-ERR-3 TO COF-DTL-LINE (3)              ELTMEDCA
00452          MOVE +3                 TO COF-NBR-DTL-LINES             ELTMEDCA
00453          PERFORM 00296-WRITE-PAGE-FILE.                           ELTMEDCA
00454      SKIP1                                                        ELTMEDCA
00455      SET WS-TERMINATE-PGM    TO TRUE.                             ELTMEDCA
00456      EJECT                                                        ELTMEDCA
00457                                                                   ELTMEDCA
00458                                                                   ELTMEDCA
00459 ************************************************************      ELTMEDCA
00460 *                                                          *      ELTMEDCA
00461 *        VERIFY MEDICARE EXISTANCE                         *      ELTMEDCA
00462 *                                                          *      ELTMEDCA
00463 ************************************************************      ELTMEDCA
00464  00056-VERIFY-MEDICARE-EXISTANC.                                  ELTMEDCA
00465      IF (GCG-COORD-MCARE-IND NOT = ZERO AND                       ELTMEDCA
00466                   GCG-COORD-MCARE-IND NOT = SPACE)                ELTMEDCA
00467               OR (GCG-EOMB-REQRD-IND NOT = ZERO AND               ELTMEDCA
00468                   GCG-EOMB-REQRD-IND NOT = SPACE)                 ELTMEDCA
00469               OR (GCG-MCARE-LIFET-RSRV-DAYS-IND NOT = ZERO AND    ELTMEDCA
00470                   GCG-MCARE-LIFET-RSRV-DAYS-IND NOT = SPACE)      ELTMEDCA
00471               OR (GCG-MCARE-DRG-PROCS-IND NOT = ZERO AND          ELTMEDCA
00472                   GCG-MCARE-DRG-PROCS-IND NOT = SPACE)            ELTMEDCA
00473          PERFORM 00105-ACCEPT-GROUP-MEDICARE.                     ELTMEDCA
00474      PERFORM 00060-VERIFY-ALL-MEDICARE-CONT.                      ELTMEDCA
00475      IF GS-MCARE-NOT-EXIST                                        ELTMEDCA
00476                   AND IB-CON-MCARE-NOT-EXIST                      ELTMEDCA
00477                   AND PB-CON-MCARE-NOT-EXIST                      ELTMEDCA
00478                   AND IS-CON-MCARE-NOT-EXIST                      ELTMEDCA
00479                   AND PS-CON-MCARE-NOT-EXIST                      ELTMEDCA
00480          PERFORM 00092-REJECT-REQUEST-DUE-TO-NO.                  ELTMEDCA
00481      EJECT                                                        ELTMEDCA
00482                                                                   ELTMEDCA
00483                                                                   ELTMEDCA
00484 ************************************************************      ELTMEDCA
00485 *                                                          *      ELTMEDCA
00486 *        VERIFY ALL MEDICARE CONTRACTS                     *      ELTMEDCA
00487 *                                                          *      ELTMEDCA
00488 ************************************************************      ELTMEDCA
00489  00060-VERIFY-ALL-MEDICARE-CONT.                                  ELTMEDCA
00490      IF SSB-PROV-CLASS-INST OR SSB-PROV-CLASS-BOTH                ELTMEDCA
00491          PERFORM 00065-VERIFY-MEDICARE-INST-BAS.                  ELTMEDCA
00492      IF SSB-PROV-CLASS-INST OR SSB-PROV-CLASS-BOTH                ELTMEDCA
00493          PERFORM 00071-VERIFY-MEDICARE-INST-SUP.                  ELTMEDCA
00494      IF SSB-PROV-CLASS-PROF OR SSB-PROV-CLASS-BOTH                ELTMEDCA
00495          PERFORM 00077-VERIFY-MEDICARE-PROF-BAS.                  ELTMEDCA
00496      IF SSB-PROV-CLASS-PROF OR SSB-PROV-CLASS-BOTH                ELTMEDCA
00497          PERFORM 00083-VERIFY-MEDICARE-PROF-SUP.                  ELTMEDCA
00498                                                                   ELTMEDCA
00499                                                                   ELTMEDCA
00500 ************************************************************      ELTMEDCA
00501 *                                                          *      ELTMEDCA
00502 *        VERIFY MEDICARE INST BASIC CONTRACT               *      ELTMEDCA
00503 *                                                          *      ELTMEDCA
00504 ************************************************************      ELTMEDCA
00505  00065-VERIFY-MEDICARE-INST-BAS.                                  ELTMEDCA
00506      SET WS-REJECT-CONTRACT   TO   TRUE.                          ELTMEDCA
00507      SET CIA-ELSCONIB-DDN TO TRUE.                                ELTMEDCA
00508      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELTMEDCA
00509            ADDRESS OF CONTRACT-RECORD-AREA.                       ELTMEDCA
00510      IF CIA-RC-PTR-NULL                                           ELTMEDCA
00511         CONTINUE                                                  ELTMEDCA
00512      ELSE                                                         ELTMEDCA
00513         PERFORM 00089-VERIFY-MEDICARE-CONTRACT.                   ELTMEDCA
00514      MOVE WS-ACCEPT-CONTRACT-SW TO WS-IB-CON-MCARE-SW.            ELTMEDCA
00515      EJECT                                                        ELTMEDCA
00516                                                                   ELTMEDCA
00517                                                                   ELTMEDCA
00518 ************************************************************      ELTMEDCA
00519 *                                                          *      ELTMEDCA
00520 *        VERIFY MEDICARE INST SUPL CONTRACT                *      ELTMEDCA
00521 *                                                          *      ELTMEDCA
00522 ************************************************************      ELTMEDCA
00523  00071-VERIFY-MEDICARE-INST-SUP.                                  ELTMEDCA
00524      SET WS-REJECT-CONTRACT   TO   TRUE.                          ELTMEDCA
00525      SET CIA-ELSCONIS-DDN TO TRUE.                                ELTMEDCA
00526      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELTMEDCA
00527            ADDRESS OF CONTRACT-RECORD-AREA.                       ELTMEDCA
00528      IF CIA-RC-PTR-NULL                                           ELTMEDCA
00529         CONTINUE                                                  ELTMEDCA
00530      ELSE                                                         ELTMEDCA
00531          PERFORM 00089-VERIFY-MEDICARE-CONTRACT.                  ELTMEDCA
00532      MOVE WS-ACCEPT-CONTRACT-SW TO WS-IS-CON-MCARE-SW.            ELTMEDCA
00533      EJECT                                                        ELTMEDCA
00534                                                                   ELTMEDCA
00535                                                                   ELTMEDCA
00536 ************************************************************      ELTMEDCA
00537 *                                                          *      ELTMEDCA
00538 *        VERIFY MEDICARE PROF BASIC CONTRACT               *      ELTMEDCA
00539 *                                                          *      ELTMEDCA
00540 ************************************************************      ELTMEDCA
00541  00077-VERIFY-MEDICARE-PROF-BAS.                                  ELTMEDCA
00542      SET WS-REJECT-CONTRACT   TO   TRUE.                          ELTMEDCA
00543      SET CIA-ELSCONPB-DDN TO TRUE.                                ELTMEDCA
00544      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELTMEDCA
00545           ADDRESS OF CONTRACT-RECORD-AREA.                        ELTMEDCA
00546      IF CIA-RC-PTR-NULL                                           ELTMEDCA
00547         CONTINUE                                                  ELTMEDCA
00548      ELSE                                                         ELTMEDCA
00549          PERFORM 00089-VERIFY-MEDICARE-CONTRACT.                  ELTMEDCA
00550      MOVE WS-ACCEPT-CONTRACT-SW TO WS-PB-CON-MCARE-SW.            ELTMEDCA
00551      EJECT                                                        ELTMEDCA
00552                                                                   ELTMEDCA
00553                                                                   ELTMEDCA
00554 ************************************************************      ELTMEDCA
00555 *                                                          *      ELTMEDCA
00556 *        VERIFY MEDICARE PROF SUPL CONTRACT                *      ELTMEDCA
00557 *                                                          *      ELTMEDCA
00558 ************************************************************      ELTMEDCA
00559  00083-VERIFY-MEDICARE-PROF-SUP.                                  ELTMEDCA
00560      SET WS-REJECT-CONTRACT   TO   TRUE.                          ELTMEDCA
00561      SET CIA-ELSCONPS-DDN TO TRUE.                                ELTMEDCA
00562      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELTMEDCA
00563           ADDRESS OF CONTRACT-RECORD-AREA.                        ELTMEDCA
00564      IF CIA-RC-PTR-NULL                                           ELTMEDCA
00565         CONTINUE                                                  ELTMEDCA
00566      ELSE                                                         ELTMEDCA
00567          PERFORM 00089-VERIFY-MEDICARE-CONTRACT.                  ELTMEDCA
00568      MOVE WS-ACCEPT-CONTRACT-SW TO WS-PS-CON-MCARE-SW.            ELTMEDCA
00569      EJECT                                                        ELTMEDCA
00570                                                                   ELTMEDCA
00571                                                                   ELTMEDCA
00572 ************************************************************      ELTMEDCA
00573 *                                                          *      ELTMEDCA
00574 *        VERIFY MEDICARE CONTRACT                          *      ELTMEDCA
00575 *                                                          *      ELTMEDCA
00576 ************************************************************      ELTMEDCA
00577  00089-VERIFY-MEDICARE-CONTRACT.                                  ELTMEDCA
00578      IF GCT-MCARE-ELIG-PROCS-IND NOT = ZERO AND NOT = SPACE       ELTMEDCA
00579          PERFORM 00107-ACCEPT-CONTRACT.                           ELTMEDCA
00580      IF GCT-MCARE-TYPE-IND NOT = ZERO AND NOT = SPACE             ELTMEDCA
00581          PERFORM 00107-ACCEPT-CONTRACT.                           ELTMEDCA
00582                                                                   ELTMEDCA
00583                                                                   ELTMEDCA
00584 ************************************************************      ELTMEDCA
00585 *                                                          *      ELTMEDCA
00586 *        REJECT REQUEST DUE TO NO CONTRACT OR GROUP        *      ELTMEDCA
00587 *                                                          *      ELTMEDCA
00588 ************************************************************      ELTMEDCA
00589  00092-REJECT-REQUEST-DUE-TO-NO.                                  ELTMEDCA
00590      SKIP1                                                        ELTMEDCA
00591 *                                                          *      ELTMEDCA
00592 *        DISPLAY NO CONTRACT OR GROUP MESSAGE              *      ELTMEDCA
00593 *                                                          *      ELTMEDCA
00594          SET COF-NEW-PAGE        TO TRUE                          ELTMEDCA
00595          MOVE +3                 TO COF-NBR-HDR-LINES             ELTMEDCA
00596          MOVE WS-HDR-LIN-3       TO COF-HDR-LINE (2)              ELTMEDCA
00597          MOVE ALL '-'            TO COF-HDR-LINE (3)              ELTMEDCA
00598          MOVE +1                 TO COF-NBR-DTL-LINES             ELTMEDCA
00599          STRING WS-NO-MCARE-VAR-1      DELIMITED BY SIZE          ELTMEDCA
00600             WS-NO-MCARE-VAR-2      DELIMITED BY SIZE              ELTMEDCA
00601         INTO COF-DTL-LINE (1)                                     ELTMEDCA
00602          PERFORM 00296-WRITE-PAGE-FILE                            ELTMEDCA
00603          SET WS-TERMINATE-PGM    TO TRUE.                         ELTMEDCA
00604      SKIP1                                                        ELTMEDCA
00605                                                                   ELTMEDCA
00606                                                                   ELTMEDCA
00607 ************************************************************      ELTMEDCA
00608 *                                                          *      ELTMEDCA
00609 *        ACCEPT GROUP MEDICARE                             *      ELTMEDCA
00610 *                                                          *      ELTMEDCA
00611 ************************************************************      ELTMEDCA
00612  00105-ACCEPT-GROUP-MEDICARE.                                     ELTMEDCA
00613      SET GS-MCARE-EXIST     TO TRUE.                              ELTMEDCA
00614                                                                   ELTMEDCA
00615                                                                   ELTMEDCA
00616 ************************************************************      ELTMEDCA
00617 *                                                          *      ELTMEDCA
00618 *        ACCEPT CONTRACT                                   *      ELTMEDCA
00619 *                                                          *      ELTMEDCA
00620 ************************************************************      ELTMEDCA
00621  00107-ACCEPT-CONTRACT.                                           ELTMEDCA
00622      SET WS-ACCEPT-CONTRACT TO TRUE.                              ELTMEDCA
00623      EJECT                                                        ELTMEDCA
00624                                                                   ELTMEDCA
00625                                                                   ELTMEDCA
00626 ************************************************************      ELTMEDCA
00627 *                                                          *      ELTMEDCA
00628 *        MAIN PROCESSING                                   *      ELTMEDCA
00629 *                                                          *      ELTMEDCA
00630 ************************************************************      ELTMEDCA
00631  00109-MAIN-PROCESSING.                                           ELTMEDCA
00632      PERFORM 00309-INITIALIZE-WS-OUTPUT-ARE.                      ELTMEDCA
00633      SET COF-NEW-PAGE TO TRUE.                                    ELTMEDCA
00634      MOVE +3             TO COF-NBR-HDR-LINES.                    ELTMEDCA
00635      MOVE WS-HDR-LIN-3   TO COF-HDR-LINE (2).                     ELTMEDCA
00636      MOVE ALL '-'        TO COF-HDR-LINE (3).                     ELTMEDCA
00637      IF GS-MCARE-EXIST                                            ELTMEDCA
00638          PERFORM 00118-PROCESS-GROUP-SPECIFIC.                    ELTMEDCA
00639      IF IB-CON-MCARE-EXIST OR                                     ELTMEDCA
00640                  PB-CON-MCARE-EXIST OR                            ELTMEDCA
00641                  IS-CON-MCARE-EXIST OR                            ELTMEDCA
00642                  PS-CON-MCARE-EXIST                               ELTMEDCA
00643          PERFORM 00165-TRANSLATE-CONTRACTS.                       ELTMEDCA
00644      EJECT                                                        ELTMEDCA
00645                                                                   ELTMEDCA
00646                                                                   ELTMEDCA
00647 ************************************************************      ELTMEDCA
00648 *                                                          *      ELTMEDCA
00649 *        PROCESS GROUP SPECIFIC                            *      ELTMEDCA
00650 *                                                          *      ELTMEDCA
00651 ************************************************************      ELTMEDCA
00652  00118-PROCESS-GROUP-SPECIFIC.                                    ELTMEDCA
00653      SKIP1                                                        ELTMEDCA
00654      SKIP1                                                        ELTMEDCA
00655      MOVE 'GROUP'        TO CMF-RECORD-PREFIX.                    ELTMEDCA
00656      IF GCG-COORD-MCARE-IND NOT = ZERO AND NOT = SPACE            ELTMEDCA
00657          PERFORM 00125-GENERATE-BENEFITS-MUST-S.                  ELTMEDCA
00658      IF GCG-EOMB-REQRD-IND NOT = ZERO AND NOT = SPACE             ELTMEDCA
00659          PERFORM 00138-GENERATE-MEDICARE-EXPLAN.                  ELTMEDCA
00660      IF GCG-MCARE-LIFET-RSRV-DAYS-IND NOT = ZERO AND NOT =        ELTMEDCA
00661          SPACE                                                    ELTMEDCA
00662          PERFORM 00147-GENERATE-RESERVE-DAYS-SE.                  ELTMEDCA
00663      IF GCG-MCARE-DRG-PROCS-IND NOT = ZERO AND NOT = SPACE        ELTMEDCA
00664          PERFORM 00156-GENERATE-DRG-SENTENCE.                     ELTMEDCA
00665      EJECT                                                        ELTMEDCA
00666                                                                   ELTMEDCA
00667                                                                   ELTMEDCA
00668 ************************************************************      ELTMEDCA
00669 *                                                          *      ELTMEDCA
00670 *        GENERATE BENEFITS MUST SENTENCE                   *      ELTMEDCA
00671 *                                                          *      ELTMEDCA
00672 ************************************************************      ELTMEDCA
00673  00125-GENERATE-BENEFITS-MUST-S.                                  ELTMEDCA
00674      PERFORM 00133-INITIALIZE-TEXT-COMPRESS.                      ELTMEDCA
00675      MOVE WS-BENEFITS-MUST      TO WS-HEADING (1).                ELTMEDCA
00676      ADD  +1                    TO WS-HEADINGS-CNT.               ELTMEDCA
00677      MOVE GCG-COORD-MCARE-IND   TO CMF-CODE-VALUE.                ELTMEDCA
00678      MOVE   'COORD-MCARE-IND'   TO CMF-ELEMENT-SYSTEM-NAME.       ELTMEDCA
00679      PERFORM 00314-CALL-CODES-MANUAL.                             ELTMEDCA
00680      PERFORM 00230-FORMAT-SENTENCE.                               ELTMEDCA
00681                                                                   ELTMEDCA
00682                                                                   ELTMEDCA
00683 ************************************************************      ELTMEDCA
00684 *                                                          *      ELTMEDCA
00685 *        INITIALIZE TEXT COMPRESSION AREA                  *      ELTMEDCA
00686 *                                                          *      ELTMEDCA
00687 ************************************************************      ELTMEDCA
00688  00133-INITIALIZE-TEXT-COMPRESS.                                  ELTMEDCA
00689      INITIALIZE TCAR-FROM-SUB                                     ELTMEDCA
00690                 TCAR-FROM-AREA                                    ELTMEDCA
00691                 TCAR-FROM-LENGTH                                  ELTMEDCA
00692                 TCAR-X.                                           ELTMEDCA
00693      EJECT                                                        ELTMEDCA
00694                                                                   ELTMEDCA
00695                                                                   ELTMEDCA
00696 ************************************************************      ELTMEDCA
00697 *                                                          *      ELTMEDCA
00698 *        GENERATE MEDICARE EXPLANATION SENTENCE            *      ELTMEDCA
00699 *                                                          *      ELTMEDCA
00700 ************************************************************      ELTMEDCA
00701  00138-GENERATE-MEDICARE-EXPLAN.                                  ELTMEDCA
00702      PERFORM 00133-INITIALIZE-TEXT-COMPRESS.                      ELTMEDCA
00703      MOVE WS-MCARE-EXP-1      TO WS-HEADING (1).                  ELTMEDCA
00704      MOVE WS-MCARE-EXP-2      TO WS-HEADING (2).                  ELTMEDCA
00705      ADD  +2                  TO WS-HEADINGS-CNT.                 ELTMEDCA
00706      MOVE GCG-EOMB-REQRD-IND  TO CMF-CODE-VALUE.                  ELTMEDCA
00707      MOVE 'EOMB-REQRD-IND'    TO CMF-ELEMENT-SYSTEM-NAME.         ELTMEDCA
00708      PERFORM 00314-CALL-CODES-MANUAL.                             ELTMEDCA
00709      PERFORM 00230-FORMAT-SENTENCE.                               ELTMEDCA
00710      EJECT                                                        ELTMEDCA
00711                                                                   ELTMEDCA
00712                                                                   ELTMEDCA
00713 ************************************************************      ELTMEDCA
00714 *                                                          *      ELTMEDCA
00715 *        GENERATE RESERVE DAYS SENTENCE                    *      ELTMEDCA
00716 *                                                          *      ELTMEDCA
00717 ************************************************************      ELTMEDCA
00718  00147-GENERATE-RESERVE-DAYS-SE.                                  ELTMEDCA
00719      PERFORM 00133-INITIALIZE-TEXT-COMPRESS.                      ELTMEDCA
00720      MOVE WS-RESERVE-DAYS-1              TO WS-HEADING (1).       ELTMEDCA
00721      MOVE WS-RESERVE-DAYS-2              TO WS-HEADING (2).       ELTMEDCA
00722      ADD  +2                             TO WS-HEADINGS-CNT.      ELTMEDCA
00723      MOVE  GCG-MCARE-LIFET-RSRV-DAYS-IND TO CMF-CODE-VALUE.       ELTMEDCA
00724      MOVE   'MCARE-LIFET-RSRV-DAYS-IND'  TO                       ELTMEDCA
00725          CMF-ELEMENT-SYSTEM-NAME.                                 ELTMEDCA
00726      PERFORM 00314-CALL-CODES-MANUAL.                             ELTMEDCA
00727      PERFORM 00230-FORMAT-SENTENCE.                               ELTMEDCA
00728      EJECT                                                        ELTMEDCA
00729                                                                   ELTMEDCA
00730                                                                   ELTMEDCA
00731 ************************************************************      ELTMEDCA
00732 *                                                          *      ELTMEDCA
00733 *        GENERATE DRG SENTENCE                             *      ELTMEDCA
00734 *                                                          *      ELTMEDCA
00735 ************************************************************      ELTMEDCA
00736  00156-GENERATE-DRG-SENTENCE.                                     ELTMEDCA
00737      PERFORM 00133-INITIALIZE-TEXT-COMPRESS.                      ELTMEDCA
00738      MOVE WS-DRG-1                 TO WS-HEADING (1).             ELTMEDCA
00739      MOVE WS-DRG-2                 TO WS-HEADING (2).             ELTMEDCA
00740      ADD  +1                       TO WS-HEADINGS-CNT.            ELTMEDCA
00741      MOVE  GCG-MCARE-DRG-PROCS-IND TO CMF-CODE-VALUE.             ELTMEDCA
00742      MOVE   'MCARE-DRG-PROCS-IND'  TO CMF-ELEMENT-SYSTEM-NAME.    ELTMEDCA
00743      PERFORM 00314-CALL-CODES-MANUAL.                             ELTMEDCA
00744      PERFORM 00230-FORMAT-SENTENCE.                               ELTMEDCA
00745      EJECT                                                        ELTMEDCA
00746                                                                   ELTMEDCA
00747                                                                   ELTMEDCA
00748 ************************************************************      ELTMEDCA
00749 *                                                          *      ELTMEDCA
00750 *        TRANSLATE CONTRACTS                               *      ELTMEDCA
00751 *                                                          *      ELTMEDCA
00752 ************************************************************      ELTMEDCA
00753  00165-TRANSLATE-CONTRACTS.                                       ELTMEDCA
00754      IF IB-CON-MCARE-EXIST                                        ELTMEDCA
00755          PERFORM 00170-TRANSLATE-INST-BASIC-CON.                  ELTMEDCA
00756      IF IS-CON-MCARE-EXIST                                        ELTMEDCA
00757          PERFORM 00177-TRANSLATE-INST-SUPL-CONT.                  ELTMEDCA
00758      IF PB-CON-MCARE-EXIST                                        ELTMEDCA
00759          PERFORM 00184-TRANSLATE-PROF-BASIC-CON.                  ELTMEDCA
00760      IF NOT PB-CON-MCARE-EXIST AND                                ELTMEDCA
00761         (GCG-L-O-B-CONTRACT-LEVEL-IND = '01')                     ELTMEDCA
00762          AND SSB-PROV-CLASS-BOTH                                  ELTMEDCA
00763          PERFORM 00199-DISPLAY-NO-PROF-CVRG                       ELTMEDCA
00764      END-IF.                                                      ELTMEDCA
00765      IF PS-CON-MCARE-EXIST                                        ELTMEDCA
00766          PERFORM 00191-TRANSLATE-PROF-SUPL-CONT.                  ELTMEDCA
00767      EJECT                                                        ELTMEDCA
00768                                                                   ELTMEDCA
00769                                                                   ELTMEDCA
00770 ************************************************************      ELTMEDCA
00771 *                                                          *      ELTMEDCA
00772 *        TRANSLATE INST BASIC CONTRACT                     *      ELTMEDCA
00773 *                                                          *      ELTMEDCA
00774 ************************************************************      ELTMEDCA
00775  00170-TRANSLATE-INST-BASIC-CON.                                  ELTMEDCA
00776      MOVE WS-INST-BASIC TO WS-HEADING (1).                        ELTMEDCA
00777      ADD  +1            TO WS-HEADINGS-CNT.                       ELTMEDCA
00778      SET CIA-ELSCONIB-DDN TO TRUE.                                ELTMEDCA
00779      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELTMEDCA
00780          ADDRESS OF CONTRACT-RECORD-AREA.                         ELTMEDCA
00781      IF IB-CON-MCARE-EXIST                                        ELTMEDCA
00782          PERFORM 00207-TRANSLATE-CONTRACT-ITEMS                   ELTMEDCA
00783      ELSE PERFORM 00198-NO-MEDICARE-ON-CONTRACT.                  ELTMEDCA
00784      EJECT                                                        ELTMEDCA
00785                                                                   ELTMEDCA
00786                                                                   ELTMEDCA
00787 ************************************************************      ELTMEDCA
00788 *                                                          *      ELTMEDCA
00789 *        TRANSLATE INST SUPL CONTRACT                      *      ELTMEDCA
00790 *                                                          *      ELTMEDCA
00791 ************************************************************      ELTMEDCA
00792  00177-TRANSLATE-INST-SUPL-CONT.                                  ELTMEDCA
00793      MOVE WS-INST-SUPP  TO WS-HEADING (1).                        ELTMEDCA
00794      ADD  +1            TO WS-HEADINGS-CNT.                       ELTMEDCA
00795      SET CIA-ELSCONIS-DDN TO TRUE.                                ELTMEDCA
00796      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELTMEDCA
00797          ADDRESS OF CONTRACT-RECORD-AREA.                         ELTMEDCA
00798                                                                   ELTMEDCA
00799      IF IS-CON-MCARE-EXIST                                        ELTMEDCA
00800          PERFORM 00207-TRANSLATE-CONTRACT-ITEMS                   ELTMEDCA
00801      ELSE PERFORM 00198-NO-MEDICARE-ON-CONTRACT.                  ELTMEDCA
00802      EJECT                                                        ELTMEDCA
00803                                                                   ELTMEDCA
00804                                                                   ELTMEDCA
00805 ************************************************************      ELTMEDCA
00806 *                                                          *      ELTMEDCA
00807 *        TRANSLATE PROF BASIC CONTRACT                     *      ELTMEDCA
00808 *                                                          *      ELTMEDCA
00809 ************************************************************      ELTMEDCA
00810  00184-TRANSLATE-PROF-BASIC-CON.                                  ELTMEDCA
00811      MOVE WS-PROF-BASIC TO WS-HEADING (1).                        ELTMEDCA
00812      ADD  +1            TO WS-HEADINGS-CNT.                       ELTMEDCA
00813      SET CIA-ELSCONPB-DDN TO TRUE.                                ELTMEDCA
00814      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELTMEDCA
00815          ADDRESS OF CONTRACT-RECORD-AREA.                         ELTMEDCA
00816                                                                   ELTMEDCA
00817      IF PB-CON-MCARE-EXIST                                        ELTMEDCA
00818          PERFORM 00207-TRANSLATE-CONTRACT-ITEMS                   ELTMEDCA
00819      ELSE PERFORM 00198-NO-MEDICARE-ON-CONTRACT.                  ELTMEDCA
00820      EJECT                                                        ELTMEDCA
00821                                                                   ELTMEDCA
00822                                                                   ELTMEDCA
00823 ************************************************************      ELTMEDCA
00824 *                                                          *      ELTMEDCA
00825 *        TRANSLATE PROF SUPL CONTRACT                      *      ELTMEDCA
00826 *                                                          *      ELTMEDCA
00827 ************************************************************      ELTMEDCA
00828  00191-TRANSLATE-PROF-SUPL-CONT.                                  ELTMEDCA
00829      MOVE WS-PROF-SUPP  TO WS-HEADING (1).                        ELTMEDCA
00830      ADD  +1            TO WS-HEADINGS-CNT.                       ELTMEDCA
00831      SET CIA-ELSCONPS-DDN TO TRUE.                                ELTMEDCA
00832      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELTMEDCA
00833          ADDRESS OF CONTRACT-RECORD-AREA.                         ELTMEDCA
00834                                                                   ELTMEDCA
00835      IF PS-CON-MCARE-EXIST                                        ELTMEDCA
00836          PERFORM 00207-TRANSLATE-CONTRACT-ITEMS                   ELTMEDCA
00837      ELSE PERFORM 00198-NO-MEDICARE-ON-CONTRACT.                  ELTMEDCA
00838      EJECT                                                        ELTMEDCA
00839                                                                   ELTMEDCA
00840                                                                   ELTMEDCA
00841 ************************************************************      ELTMEDCA
00842 *                                                          *      ELTMEDCA
00843 *        NO MEDICARE ON CONTRACT                           *      ELTMEDCA
00844 *                                                          *      ELTMEDCA
00845 ************************************************************      ELTMEDCA
00846  00198-NO-MEDICARE-ON-CONTRACT.                                   ELTMEDCA
00847      SET COF-NEW-PAGE        TO TRUE.                             ELTMEDCA
00848      MOVE +3                 TO COF-NBR-HDR-LINES.                ELTMEDCA
00849      MOVE WS-HDR-LIN-3       TO COF-HDR-LINE (2).                 ELTMEDCA
00850      MOVE ALL '-'            TO COF-HDR-LINE (3).                 ELTMEDCA
00851      MOVE WS-NO-MCARE-VAR-1  TO WS-TEXT (1).                      ELTMEDCA
00852      MOVE WS-NO-MCARE-VAR-2  TO WS-TEXT (2).                      ELTMEDCA
00853      ADD  +2                 TO WS-LINE-CNT.                      ELTMEDCA
00854      PERFORM 00274-DISPLAY-INFORMATION-STOR.                      ELTMEDCA
00855                                                                   ELTMEDCA
00856 ************************************************************      ELTMEDCA
00857 *                                                          *      ELTMEDCA
00858 *        NO PROF COVERAGE                                  *      ELTMEDCA
00859 *                                                          *      ELTMEDCA
00860 ************************************************************      ELTMEDCA
00861  00199-DISPLAY-NO-PROF-CVRG.                                      ELTMEDCA
00862      MOVE WS-PROF-BASIC TO WS-HEADING (1).                        ELTMEDCA
00863      ADD  +1            TO WS-HEADINGS-CNT.                       ELTMEDCA
00864      MOVE WS-INST-ONLY TO WS-TEXT(1).                             ELTMEDCA
00865      MOVE SPACES TO WS-OUTPUT-LINE(2).                            ELTMEDCA
00866      MOVE WS-INST-ONLY1 TO WS-TEXT(2).                            ELTMEDCA
00867      ADD  +2                 TO WS-LINE-CNT.                      ELTMEDCA
00868      MOVE 0 TO               COF-NBR-DTL-LINES.                   ELTMEDCA
00869 *    SET COF-END TO TRUE.                                         ELTMEDCA
00870      PERFORM 00274-DISPLAY-INFORMATION-STOR.                      ELTMEDCA
00871                                                                   ELTMEDCA
00872                                                                   ELTMEDCA
00873 ************************************************************      ELTMEDCA
00874 *                                                          *      ELTMEDCA
00875 *        TRANSLATE CONTRACT ITEMS                          *      ELTMEDCA
00876 *                                                          *      ELTMEDCA
00877 ************************************************************      ELTMEDCA
00878  00207-TRANSLATE-CONTRACT-ITEMS.                                  ELTMEDCA
00879      MOVE 'CONTRACT'  TO CMF-RECORD-PREFIX.                       ELTMEDCA
00880      IF  GCT-MCARE-ELIG-PROCS-IND NOT = ZERO AND NOT = SPACE      ELTMEDCA
00881          PERFORM 00211-TRANSLATE-SUPLEMENTAL-ME.                  ELTMEDCA
00882      IF GCT-MCARE-TYPE-IND NOT = ZERO AND NOT = SPACE             ELTMEDCA
00883          PERFORM 00220-TRANSLATE-HCSC-COORDINAT.                  ELTMEDCA
00884      EJECT                                                        ELTMEDCA
00885                                                                   ELTMEDCA
00886                                                                   ELTMEDCA
00887 ************************************************************      ELTMEDCA
00888 *                                                          *      ELTMEDCA
00889 *        TRANSLATE SUPLEMENTAL MEDICARE                    *      ELTMEDCA
00890 *                                                          *      ELTMEDCA
00891 ************************************************************      ELTMEDCA
00892  00211-TRANSLATE-SUPLEMENTAL-ME.                                  ELTMEDCA
00893      PERFORM 00133-INITIALIZE-TEXT-COMPRESS.                      ELTMEDCA
00894      MOVE GCT-MCARE-ELIG-PROCS-IND TO CMF-CODE-VALUE.             ELTMEDCA
00895      MOVE  'MCARE-ELIG-PROCS-IND' TO CMF-ELEMENT-SYSTEM-NAME.     ELTMEDCA
00896      PERFORM 00314-CALL-CODES-MANUAL.                             ELTMEDCA
00897      MOVE WS-MCARE-SUPL           TO TCAR-FROM-LINE (19).         ELTMEDCA
00898      SET  NO-PERIOD-NEEDED        TO TRUE.                        ELTMEDCA
00899      PERFORM 00230-FORMAT-SENTENCE.                               ELTMEDCA
00900      SET  INSERT-PERIOD           TO TRUE.                        ELTMEDCA
00901      EJECT                                                        ELTMEDCA
00902                                                                   ELTMEDCA
00903                                                                   ELTMEDCA
00904 ************************************************************      ELTMEDCA
00905 *                                                          *      ELTMEDCA
00906 *        TRANSLATE HCSC COORDINATION                       *      ELTMEDCA
00907 *                                                          *      ELTMEDCA
00908 ************************************************************      ELTMEDCA
00909  00220-TRANSLATE-HCSC-COORDINAT.                                  ELTMEDCA
00910      PERFORM 00133-INITIALIZE-TEXT-COMPRESS.                      ELTMEDCA
00911      MOVE GCT-MCARE-TYPE-IND      TO CMF-CODE-VALUE.              ELTMEDCA
00912      MOVE  'MCARE-TYPE-IND'       TO CMF-ELEMENT-SYSTEM-NAME.     ELTMEDCA
00913      PERFORM 00314-CALL-CODES-MANUAL.                             ELTMEDCA
00914      ADD  +1                      TO TCAR-FROM-SUB.               ELTMEDCA
00915      MOVE WS-HCSC-1               TO TCAR-FROM-LINE               ELTMEDCA
00916          (TCAR-FROM-SUB).                                         ELTMEDCA
00917      ADD  +1                      TO TCAR-FROM-SUB.               ELTMEDCA
00918      MOVE WS-HCSC-2               TO TCAR-FROM-LINE               ELTMEDCA
00919          (TCAR-FROM-SUB).                                         ELTMEDCA
00920      PERFORM 00230-FORMAT-SENTENCE.                               ELTMEDCA
00921      EJECT                                                        ELTMEDCA
00922                                                                   ELTMEDCA
00923                                                                   ELTMEDCA
00924 ************************************************************      ELTMEDCA
00925 *                                                          *      ELTMEDCA
00926 *        FORMAT SENTENCE                                   *      ELTMEDCA
00927 *                                                          *      ELTMEDCA
00928 ************************************************************      ELTMEDCA
00929  00230-FORMAT-SENTENCE.                                           ELTMEDCA
00930      PERFORM 00236-MOVE-TEXT-FROM-CODES-MAN                       ELTMEDCA
00931          VARYING CMF-DESCR-IDX FROM 1 BY 1                        ELTMEDCA
00932                   UNTIL CMF-DESCR-IDX > CMF-NBR-DESCR-LINES.      ELTMEDCA
00933      IF INSERT-PERIOD                                             ELTMEDCA
00934          PERFORM 00240-INSERT-PERIOD-AT-END-OFX.                  ELTMEDCA
00935      PERFORM 00243-FORMAT-THE-RAW-TEXT.                           ELTMEDCA
00936      SKIP1                                                        ELTMEDCA
00937 *                                                          *      ELTMEDCA
00938 *        MOVE TEXT TO DISPLAY                              *      ELTMEDCA
00939 *                                                          *      ELTMEDCA
00940          PERFORM 00269-MOVE-TEXT-TO-DETAIL-LINE                   ELTMEDCA
00941          VARYING TCAR-X FROM 1 BY 1                               ELTMEDCA
00942                   UNTIL TCAR-X > TCAR-OUTPUT-FIELDS-USED OR       ELTMEDCA
00943                         TCAR-X > 20.                              ELTMEDCA
00944      SKIP1                                                        ELTMEDCA
00945      PERFORM 00274-DISPLAY-INFORMATION-STOR.                      ELTMEDCA
00946                                                                   ELTMEDCA
00947                                                                   ELTMEDCA
00948 ************************************************************      ELTMEDCA
00949 *                                                          *      ELTMEDCA
00950 *        MOVE TEXT FROM CODES MANUAL                       *      ELTMEDCA
00951 *                                                          *      ELTMEDCA
00952 ************************************************************      ELTMEDCA
00953  00236-MOVE-TEXT-FROM-CODES-MAN.                                  ELTMEDCA
00954      ADD +1                              TO TCAR-FROM-SUB.        ELTMEDCA
00955      MOVE CMF-DESCR-LINE (CMF-DESCR-IDX) TO                       ELTMEDCA
00956           TCAR-FROM-LINE (TCAR-FROM-SUB).                         ELTMEDCA
00957                                                                   ELTMEDCA
00958                                                                   ELTMEDCA
00959 ************************************************************      ELTMEDCA
00960 *                                                          *      ELTMEDCA
00961 *        INSERT PERIOD AT END OF TEXT                      *      ELTMEDCA
00962 *                                                          *      ELTMEDCA
00963 ************************************************************      ELTMEDCA
00964  00240-INSERT-PERIOD-AT-END-OFX.                                  ELTMEDCA
00965      ADD  +1      TO TCAR-FROM-SUB.                               ELTMEDCA
00966      MOVE '.'     TO TCAR-FROM-LINE-LAST-DIGIT (TCAR-FROM-SUB).   ELTMEDCA
00967      EJECT                                                        ELTMEDCA
00968                                                                   ELTMEDCA
00969                                                                   ELTMEDCA
00970 ************************************************************      ELTMEDCA
00971 *                                                          *      ELTMEDCA
00972 *        FORMAT THE RAW TEXT                               *      ELTMEDCA
00973 *                                                          *      ELTMEDCA
00974 ************************************************************      ELTMEDCA
00975  00243-FORMAT-THE-RAW-TEXT.                                       ELTMEDCA
00976      SKIP1                                                        ELTMEDCA
00977 *                                                          *      ELTMEDCA
00978 *        DO TEXT COMPRESSION                               *      ELTMEDCA
00979 *                                                          *      ELTMEDCA
00980          CALL 'ELUTCOMP' USING TCAR-COMPRESSION-WORK-AREA.        ELTMEDCA
00981      SKIP1                                                        ELTMEDCA
00982      MOVE +20 TO TCAR-OUTPUT-FIELD-COUNT.                         ELTMEDCA
00983      MOVE +46 TO TCAR-OUTPUT-FIELD-1-LEN                          ELTMEDCA
00984                  TCAR-OUTPUT-FIELD-2-LEN                          ELTMEDCA
00985                  TCAR-OUTPUT-FIELD-3-LEN                          ELTMEDCA
00986                  TCAR-OUTPUT-FIELD-4-LEN                          ELTMEDCA
00987                  TCAR-OUTPUT-FIELD-5-LEN                          ELTMEDCA
00988                  TCAR-OUTPUT-FIELD-6-LEN                          ELTMEDCA
00989                  TCAR-OUTPUT-FIELD-7-LEN                          ELTMEDCA
00990                  TCAR-OUTPUT-FIELD-8-LEN                          ELTMEDCA
00991                  TCAR-OUTPUT-FIELD-9-LEN                          ELTMEDCA
00992                  TCAR-OUTPUT-FIELD-10-LEN                         ELTMEDCA
00993                  TCAR-OUTPUT-FIELD-11-LEN                         ELTMEDCA
00994                  TCAR-OUTPUT-FIELD-12-LEN                         ELTMEDCA
00995                  TCAR-OUTPUT-FIELD-13-LEN                         ELTMEDCA
00996                  TCAR-OUTPUT-FIELD-14-LEN                         ELTMEDCA
00997                  TCAR-OUTPUT-FIELD-15-LEN                         ELTMEDCA
00998                  TCAR-OUTPUT-FIELD-16-LEN                         ELTMEDCA
00999                  TCAR-OUTPUT-FIELD-17-LEN                         ELTMEDCA
01000                  TCAR-OUTPUT-FIELD-18-LEN                         ELTMEDCA
01001                  TCAR-OUTPUT-FIELD-19-LEN                         ELTMEDCA
01002                  TCAR-OUTPUT-FIELD-20-LEN.                        ELTMEDCA
01003      SKIP1                                                        ELTMEDCA
01004 *                                                          *      ELTMEDCA
01005 *        DO TEXT UNSTRING                                  *      ELTMEDCA
01006 *                                                          *      ELTMEDCA
01007          CALL 'ELUTUNST' USING TCAR-COMPRESSION-WORK-AREA.        ELTMEDCA
01008      SKIP1                                                        ELTMEDCA
01009      EJECT                                                        ELTMEDCA
01010                                                                   ELTMEDCA
01011                                                                   ELTMEDCA
01012 ************************************************************      ELTMEDCA
01013 *                                                          *      ELTMEDCA
01014 *        MOVE TEXT TO DETAIL LINE                          *      ELTMEDCA
01015 *                                                          *      ELTMEDCA
01016 ************************************************************      ELTMEDCA
01017  00269-MOVE-TEXT-TO-DETAIL-LINE.                                  ELTMEDCA
01018      ADD 1                              TO WS-LINE-CNT.           ELTMEDCA
01019      MOVE TCAR-OPF-DATA (TCAR-X)        TO                        ELTMEDCA
01020           WS-TEXT (WS-OUTPUT-IDX).                                ELTMEDCA
01021      SET  WS-OUTPUT-IDX UP BY +1.                                 ELTMEDCA
01022      EJECT                                                        ELTMEDCA
01023                                                                   ELTMEDCA
01024                                                                   ELTMEDCA
01025 ************************************************************      ELTMEDCA
01026 *                                                          *      ELTMEDCA
01027 *        DISPLAY INFORMATION STORED IN WS OUTPUT AREA      *      ELTMEDCA
01028 *                                                          *      ELTMEDCA
01029 ************************************************************      ELTMEDCA
01030  00274-DISPLAY-INFORMATION-STOR.                                  ELTMEDCA
01031      IF WS-LINE-CNT < WS-HEADINGS-CNT                             ELTMEDCA
01032          PERFORM 00279-INCREMENT-LINE-COUNTER-F.                  ELTMEDCA
01033      PERFORM 00281-MOVE-WS-OUTPUT-INTO-OUTP                       ELTMEDCA
01034          VARYING WS-OUTPUT-IDX FROM 1 BY 1                        ELTMEDCA
01035                  UNTIL   WS-OUTPUT-IDX > WS-LINE-CNT + 1.         ELTMEDCA
01036      PERFORM 00296-WRITE-PAGE-FILE.                               ELTMEDCA
01037      PERFORM 00309-INITIALIZE-WS-OUTPUT-ARE.                      ELTMEDCA
01038                                                                   ELTMEDCA
01039                                                                   ELTMEDCA
01040 ************************************************************      ELTMEDCA
01041 *                                                          *      ELTMEDCA
01042 *        INCREMENT LINE COUNTER FOR TRAILING LINE          *      ELTMEDCA
01043 *                                                          *      ELTMEDCA
01044 ************************************************************      ELTMEDCA
01045  00279-INCREMENT-LINE-COUNTER-F.                                  ELTMEDCA
01046      ADD  +1                 TO WS-LINE-CNT.                      ELTMEDCA
01047                                                                   ELTMEDCA
01048                                                                   ELTMEDCA
01049 ************************************************************      ELTMEDCA
01050 *                                                          *      ELTMEDCA
01051 *        MOVE WS OUTPUT INTO OUTPUT INTERFACE AREA         *      ELTMEDCA
01052 *                                                          *      ELTMEDCA
01053 ************************************************************      ELTMEDCA
01054  00281-MOVE-WS-OUTPUT-INTO-OUTP.                                  ELTMEDCA
01055      ADD  +1                 TO COF-NBR-DTL-LINES.                ELTMEDCA
01056      MOVE WS-BAR             TO WS-DIVIDER (WS-OUTPUT-IDX).       ELTMEDCA
01057      MOVE WS-OUTPUT-LINE (WS-OUTPUT-IDX)                          ELTMEDCA
01058                              TO COF-DTL-LINE                      ELTMEDCA
01059          (COF-NBR-DTL-LINES).                                     ELTMEDCA
01060      EJECT                                                        ELTMEDCA
01061                                                                   ELTMEDCA
01062                                                                   ELTMEDCA
01063 ************************************************************      ELTMEDCA
01064 *                                                          *      ELTMEDCA
01065 *        TERMINATE TEXT DISPLAYED                          *      ELTMEDCA
01066 *                                                          *      ELTMEDCA
01067 ************************************************************      ELTMEDCA
01068  00286-TERMINATE-TEXT-DISPLAYED.                                  ELTMEDCA
01069      SKIP1                                                        ELTMEDCA
01070 *                                                          *      ELTMEDCA
01071 *        DISPLAY DASHED LINE AT END OF TEXT                *      ELTMEDCA
01072 *                                                          *      ELTMEDCA
01073          MOVE +1                 TO COF-NBR-DTL-LINES             ELTMEDCA
01074          MOVE ALL '-'            TO COF-DTL-LINE (1)              ELTMEDCA
01075          PERFORM 00296-WRITE-PAGE-FILE.                           ELTMEDCA
01076      SKIP1                                                        ELTMEDCA
01077      SET COF-END             TO TRUE.                             ELTMEDCA
01078      MOVE ZEROS              TO COF-NBR-HDR-LINES                 ELTMEDCA
01079                                 COF-NBR-DTL-LINES.                ELTMEDCA
01080      PERFORM 00296-WRITE-PAGE-FILE.                               ELTMEDCA
01081      EJECT                                                        ELTMEDCA
01082                                                                   ELTMEDCA
01083                                                                   ELTMEDCA
01084 ************************************************************      ELTMEDCA
01085 *                                                          *      ELTMEDCA
01086 *        WRITE PAGE FILE                                   *      ELTMEDCA
01087 *                                                          *      ELTMEDCA
01088 ************************************************************      ELTMEDCA
01089  00296-WRITE-PAGE-FILE.                                           ELTMEDCA
01090 *    IF INST-ONLY AND                                             ELTMEDCA
01091 *        SSB-PROV-CLASS-BOTH                                      ELTMEDCA
01092 *       SET COF-CONTINUE TO TRUE                                  ELTMEDCA
01093 *    END-IF.                                                      ELTMEDCA
01094      EXEC CICS LINK                                               ELTMEDCA
01095                PROGRAM ('ELUOUTPT')                               ELTMEDCA
01096                COMMAREA (DFHCOMMAREA)                             ELTMEDCA
01097                LENGTH (LENGTH OF DFHCOMMAREA)                     ELTMEDCA
01098        END-EXEC.                                                  ELTMEDCA
01099      SET COF-CONTINUE TO TRUE.                                    ELTMEDCA
01100      MOVE ZEROS TO COF-NBR-DTL-LINES                              ELTMEDCA
01101                    COF-NBR-HDR-LINES.                             ELTMEDCA
01102                                                                   ELTMEDCA
01103                                                                   ELTMEDCA
01104 ************************************************************      ELTMEDCA
01105 *                                                          *      ELTMEDCA
01106 *       TERMINATE INST ONLY TYPE                           *      ELTMEDCA
01107 *                                                          *      ELTMEDCA
01108 ************************************************************      ELTMEDCA
01109  00299-TRMNT-INST-ONLY-TYPE.                                      ELTMEDCA
01110      PERFORM 0299A-REDO-HEADER.                                   ELTMEDCA
01111      SET COF-END TO TRUE.                                         ELTMEDCA
01112      MOVE ZEROS TO COF-NBR-DTL-LINES                              ELTMEDCA
01113                    COF-NBR-HDR-LINES.                             ELTMEDCA
01114      EXEC CICS LINK                                               ELTMEDCA
01115                PROGRAM ('ELUOUTPT')                               ELTMEDCA
01116                COMMAREA (DFHCOMMAREA)                             ELTMEDCA
01117                LENGTH (LENGTH OF DFHCOMMAREA)                     ELTMEDCA
01118      END-EXEC.                                                    ELTMEDCA
01119                                                                   ELTMEDCA
01120                                                                   ELTMEDCA
01121 ************************************************************      ELTMEDCA
01122 *                                                          *      ELTMEDCA
01123 *        REDO HEADER                                       *      ELTMEDCA
01124 *                                                          *      ELTMEDCA
01125 ************************************************************      ELTMEDCA
01126  0299A-REDO-HEADER.                                               ELTMEDCA
01127      SET COF-NEW-PAGE TO TRUE.                                    ELTMEDCA
01128      MOVE SPACES TO WS-HDRLIN3-IP-PP-AP                           ELTMEDCA
01129                     COF-HDR-LINE (2).                             ELTMEDCA
01130      MOVE 'PROFESSIONAL PROVIDERS' TO WS-HDRLIN3-IP-PP-AP.        ELTMEDCA
01131      MOVE WS-HDR-LIN-3 TO COF-HDR-LINE(2).                        ELTMEDCA
01132      MOVE +3 TO COF-NBR-HDR-LINES.                                ELTMEDCA
01133      MOVE ALL '-' TO COF-HDR-LINE (COF-NBR-HDR-LINES).            ELTMEDCA
01134      MOVE +0 TO COF-NBR-DTL-LINES.                                ELTMEDCA
01135      ADD +1 TO COF-NBR-DTL-LINES.                                 ELTMEDCA
01136      MOVE SPACES TO COF-DTL-LINE(COF-NBR-DTL-LINES).              ELTMEDCA
01137      ADD +1 TO COF-NBR-DTL-LINES.                                 ELTMEDCA
01138      MOVE WS-NO-PROF TO COF-DTL-LINE(COF-NBR-DTL-LINES).          ELTMEDCA
01139      EXEC CICS LINK                                               ELTMEDCA
01140                PROGRAM ('ELUOUTPT')                               ELTMEDCA
01141                COMMAREA (DFHCOMMAREA)                             ELTMEDCA
01142                LENGTH (LENGTH OF DFHCOMMAREA)                     ELTMEDCA
01143        END-EXEC.                                                  ELTMEDCA
01144 *    SET COF-NEW-PAGE TO TRUE.                                    ELTMEDCA
01145                                                                   ELTMEDCA
01146 ************************************************************      ELTMEDCA
01147 *                                                          *      ELTMEDCA
01148 *        INITIALIZE WS OUTPUT AREA                         *      ELTMEDCA
01149 *                                                          *      ELTMEDCA
01150 ************************************************************      ELTMEDCA
01151  00309-INITIALIZE-WS-OUTPUT-ARE.                                  ELTMEDCA
01152      INITIALIZE WS-HEADINGS-CNT                                   ELTMEDCA
01153                 WS-LINE-CNT                                       ELTMEDCA
01154                 WS-OUTPUT.                                        ELTMEDCA
01155      SET  WS-OUTPUT-IDX TO +1.                                    ELTMEDCA
01156                                                                   ELTMEDCA
01157                                                                   ELTMEDCA
01158 ************************************************************      ELTMEDCA
01159 *                                                          *      ELTMEDCA
01160 *        CALL CODES MANUAL                                 *      ELTMEDCA
01161 *                                                          *      ELTMEDCA
01162 ************************************************************      ELTMEDCA
01163  00314-CALL-CODES-MANUAL.                                         ELTMEDCA
01164      EXEC CICS LINK                                               ELTMEDCA
01165                PROGRAM('ELUCMIF')                                 ELTMEDCA
01166                COMMAREA(DFHCOMMAREA)                              ELTMEDCA
01167        END-EXEC.                                                  ELTMEDCA
01168      SET CIA-ELSCMDSC-DDN TO TRUE.                                ELTMEDCA
01169      CALL 'ELUSETAD' USING DFHCOMMAREA                            ELTMEDCA
01170          ADDRESS OF CMF-DESCR.                                    ELTMEDCA
01171                                                                   ELTMEDCA
01172 ************************************************************      ELTMEDCA
01173 *                                                          *      ELTMEDCA
01174 *        SIGNAL UNALL AREA ERROR                           *      ELTMEDCA
01175 *                                                          *      ELTMEDCA
01176 ************************************************************      ELTMEDCA
01177  00999-SIGNAL-UNALL-AREA-ERROR.                                   ELTMEDCA
01178      SET CIA-AB-UNALLOC-AREA TO TRUE.                             ELTMEDCA
01179      EXEC CICS ABEND  ABCODE (CIA-ABCODE) END-EXEC.               ELTMEDCA
01180                                                                   ELTMEDCA
01181 ************************************************************      ELTMEDCA
01182 *                                                          *      ELTMEDCA
01183 *        SIGNAL UNALL AREA ERROR                           *      ELTMEDCA
01184 *                                                          *      ELTMEDCA
01185 ************************************************************      ELTMEDCA
01186  1999-SIGNAL-INST-ONLY-COVERAGE.                                  ELTMEDCA
01187      MOVE 1 TO COF-NBR-DTL-LINES.                                 ELTMEDCA
01188      MOVE SPACES TO COF-DTL-LINE (COF-NBR-DTL-LINES).             ELTMEDCA
01189      SET COF-NEW-PAGE TO TRUE.                                    ELTMEDCA
01190      MOVE WS-INST-ONLY TO COF-DTL-LINE (COF-NBR-DTL-LINES).       ELTMEDCA
01191                                                                   ELTMEDCA
