00001 *      LAST MAINTENANCE TIME: 12.43.20  DATE: 11/10/88            06/29/02
00002 * GENERATED BY STRUCTURE(S) CODE GENERATOR V2.0                   ELPARSE 
00003 *     ON 88/11/10 AT 12:43:04.09                                     LV001
00004 * STRUCTURE(S) MEMBER ELPARSEPW  - LEVEL 020 AS OF 11/10/88       ELPARSE 
00005 * FROM PANLIB R360059.STRUCTPL.PANLIB                             ELPARSE 
00006 *                                                                 ELPARSE 
00007  IDENTIFICATION DIVISION.                                         ELPARSE 
00008                                                                   ELPARSE 
00009  PROGRAM-ID.           ELPARSE.                                   ELPARSE 
00010                                                                   ELPARSE 
00011  AUTHOR.               RICK BARILEAU.                             ELPARSE 
00012                                                                   ELPARSE 
00013  INSTALLATION.         HEALTH CARE SERVICE CORPORATION            ELPARSE 
00014                        A MUTUAL LEGAL RESERVE COMPANY             ELPARSE 
00015                        BLUE CROSS/BLUE SHIELD OF ILLINOIS         ELPARSE 
00016                        233 N. MICHIGAN AVE                        ELPARSE 
00017                        CHICAGO, ILLINOIS 60601                    ELPARSE 
00018                                                                   ELPARSE 
00019  DATE-WRITTEN.         05-JUL-1988.                               ELPARSE 
00020                                                                   ELPARSE 
00021  ENVIRONMENT DIVISION.                                            ELPARSE 
00022  CONFIGURATION SECTION.                                           ELPARSE 
00023  SOURCE-COMPUTER. IBM-3033.                                       ELPARSE 
00024  OBJECT-COMPUTER. IBM-3033.                                       ELPARSE 
00025                                                                   ELPARSE 
00026 ****************************************************************  ELPARSE 
00027 *                                                              *  ELPARSE 
00028 *  ELPARSE : THIS BATCH SUBROUTINE WILL PARSE THE ENTIRE       *  ELPARSE 
00029 *            CONTROL RECORD PASSED TO IT BY 'ELP020' AND       *  ELPARSE 
00030 *            IDENTIFY ANY ERRORS DISCOVERED IN THE FIELDS      *  ELPARSE 
00031 *            REQUIRED FOR THAT TRANSACTION TYPE.               *  ELPARSE 
00032 *                                                              *  ELPARSE 
00033 ****************************************************************  ELPARSE 
00034 *                      MAINTENANCE HISTORY                     *  ELPARSE 
00035 *                                                              *  ELPARSE 
00036 *  MOD     DATE      BY  DRPT              ACTION              *  ELPARSE 
00037 * ----- ----------- --- ----- -------------------------------- *  ELPARSE 
00038 * 01.00 05-JUL-1988 REB       CREATED                          *  ELPARSE 
00039 *                                                              *  ELPARSE 
00040 * 02.00 21-SEP-1988 LET       ADDED SYNTAX CHECKING FOR A NEW  *  ELPARSE 
00041 *                             COMMAND '+AN' WHICH ALLOWS A     *  ELPARSE 
00042 *                             RANGE OF GROUP NUMBER KEY RECORDS*  ELPARSE 
00043 *                             TO BE ADDED TO SBM SUBSYSTEM.    *  ELPARSE 
00044 *                                                              *  ELPARSE 
00045 *                             ADDED SYNTAX CHECKING FOR A NEW  *  ELPARSE 
00046 *                             COMMAND '+AS' WHICH ALLOWS A     *  ELPARSE 
00047 *                             RANGE OF GROUP SECTION KEY       *  ELPARSE 
00048 *                             RECORDS TO BE ADDED TO THE SBM   *  ELPARSE 
00049 *                             SUBSYSTEM.                       *  ELPARSE 
00050 *                                                              *  ELPARSE 
00051 ****************************************************************  ELPARSE 
00052                                                                   ELPARSE 
00053  DATA DIVISION.                                                   ELPARSE 
00054  WORKING-STORAGE SECTION.                                         ELPARSE 
00055  01  WS-MISC.                                                     ELPARSE 
00056      05  WS-CHAR-SW                   PIC  X(01) VALUE 'V'.       ELPARSE 
00057          88  CHAR-VALID                          VALUE 'V'.       ELPARSE 
00058          88  CHAR-INVALID                        VALUE 'I'.       ELPARSE 
00059      05  WS-PROCESS-SW                PIC  X(01) VALUE ' '.       ELPARSE 
00060          88  STOP-PROCESSING                     VALUE 'S'.       ELPARSE 
00061      05  WS-RECORD-KEY-SW             PIC  X(01) VALUE 'N'.       ELPARSE 
00062          88  KEY-FOUND                           VALUE 'K'.       ELPARSE 
00063          88  KEY-NOT-FOUND                       VALUE 'N'.       ELPARSE 
00064      05  WS-TYPE-DATE-SW              PIC  X(01) VALUE ' '.       ELPARSE 
00065          88  EXTRACTING-EFF-DATE                 VALUE 'E'.       ELPARSE 
00066          88  EXTRACTING-TERMN-DATE               VALUE 'T'.       ELPARSE 
00067      05  WS-GROUP-RANGE-SW            PIC  X(01) VALUE ' '.       ELPARSE 
00068          88  END-GROUP-NBR                       VALUE '1'.       ELPARSE 
00069          88  NO-GROUP-RANGE                      VALUE ' '.       ELPARSE 
00070      05  WS-SECTION-RANGE-SW          PIC  X(01) VALUE ' '.       ELPARSE 
00071          88  END-SECTION-NBR                     VALUE '1'.       ELPARSE 
00072          88  NO-SECTION-RANGE                    VALUE ' '.       ELPARSE 
00073                                                                   ELPARSE 
00074      05  GREG-DATE                    PIC  9(06).                 ELPARSE 
00075      05  JULIAN-DATE                  PIC  9(05).                 ELPARSE 
00076      05  WS-HOLD-MSG-ACTION           PIC  X(01) VALUE ' '.       ELPARSE 
00077      05  WS-PROV-CNTL.                                            ELPARSE 
00078           10  WS-FIRST-DIGIT          PIC  X(01).                 ELPARSE 
00079           10  WS-SECOND-DIGIT         PIC  X(01).                 ELPARSE 
00080      05  WS-UNIQUE-MSG                PIC  X(05) VALUE 'X0000'.   ELPARSE 
00081      05  WS-COMMON-MSG                PIC  X(05) VALUE 'C0000'.   ELPARSE 
00082                                                                   ELPARSE 
00083  01  WS-LAST-INPUT-POS                PIC S9(04) VALUE +0   COMP. ELPARSE 
00084  01  WS-MOVE-POS                      PIC S9(04) VALUE +0   COMP. ELPARSE 
00085                                                                   ELPARSE 
00086  01  WS-CONTROL-RECORD                PIC  X(72).                 ELPARSE 
00087  01  CONTROL-RECORD-INPUT-TABLE REDEFINES WS-CONTROL-RECORD.      ELPARSE 
00088      05  CONTROL-RECORD-CHARS         OCCURS 72 TIMES             ELPARSE 
00089                                       INDEXED BY WS-CHAR-IDX      ELPARSE 
00090                                       PIC  X(01).                 ELPARSE 
00091                                                                   ELPARSE 
00092  01  WS-SIX-CHARS-FIELD.                                          ELPARSE 
00093      05  WS-SIX-CHARS                 OCCURS 7 TIMES              ELPARSE 
00094                                       INDEXED BY WS-SIX-IDX       ELPARSE 
00095                                       PIC  X(01).                 ELPARSE 
00096                                                                   ELPARSE 
00097  01  WS-MESSAGE-PTR.                                              ELPARSE 
00098      05  WS-PTR-CHARS                 OCCURS 6 TIMES              ELPARSE 
00099                                       INDEXED BY WS-PTR-IDX       ELPARSE 
00100                                       PIC  X(01).                 ELPARSE 
00101                                                                   ELPARSE 
00102  01  WS-SORT-POINTER.                                             ELPARSE 
00103      05  WS-POINTER-ENTRY             OCCURS 20 TIMES             ELPARSE 
00104                                       INDEXED BY SORT-IDX.        ELPARSE 
00105          10  WS-MSG-PTR               PIC  X(05).                 ELPARSE 
00106          10  WS-MSG-ACTION            PIC  X(01).                 ELPARSE 
00107                                                                   ELPARSE 
00108  01  SORT-POINTER-RED REDEFINES WS-SORT-POINTER.                  ELPARSE 
00109      05  SORT-ITEM                    OCCURS 20 TIMES             ELPARSE 
00110                                       INDEXED BY J K.             ELPARSE 
00111          10  SORT-KEY                 PIC  X(05).                 ELPARSE 
00112          10  FILLER                   PIC  X(01).                 ELPARSE 
00113                                                                   ELPARSE 
00114  01  SORT-WORK                        PIC  X(06) VALUE ZEROS.     ELPARSE 
00115                                                                   ELPARSE 
00116  LINKAGE SECTION.                                                 ELPARSE 
00117  01  WS-INPUT-DATA                    PIC  X(72).                 ELPARSE 
00118 /                                                                 ELPARSE 
00119      COPY ELSCTLRC.                                               ELPARSE 
00120                                                                   ELPARSE 
00121      EJECT                                                        ELPARSE 
00122  PROCEDURE DIVISION USING WS-INPUT-DATA,CONTROL-RECORD-SUMMARY.   ELPARSE 
00123 ************************************************************      ELPARSE 
00124 *                                                          *      ELPARSE 
00125 *                    PROCEDURE DIVISION                    *      ELPARSE 
00126 *                                                          *      ELPARSE 
00127 ************************************************************      ELPARSE 
00128                                                                   ELPARSE 
00129                                                                   ELPARSE 
00130 ************************************************************      ELPARSE 
00131 *                                                          *      ELPARSE 
00132 *        ELPARSE                                           *      ELPARSE 
00133 *                                                          *      ELPARSE 
00134 ************************************************************      ELPARSE 
00135  00001-ELPARSE.                                                   ELPARSE 
00136 ***************************************************************   ELPARSE 
00137 ** ALL THE FIELDS FOR THE GROUP/CONTRACT KEY ARE INITIALIZED **   ELPARSE 
00138 ** TO LOW-VALUES IN CASE THAT FIELD WAS DETERMINED NOT GIVEN **   ELPARSE 
00139 ** BY THE USER.                                              **   ELPARSE 
00140 ***************************************************************   ELPARSE 
00141      MOVE LOW-VALUES                 TO CR-GROUP-NUMBER           ELPARSE 
00142                                         CR-SECTION-NUMBER         ELPARSE 
00143                                         CR-LINE-OF-BUSINESS       ELPARSE 
00144                                         CR-PROVIDER-CONTROL       ELPARSE 
00145                                         CR-FAMILY-RELATION        ELPARSE 
00146                                         CR-EFFECTIVE-DATE.        ELPARSE 
00147      INITIALIZE                         WS-LAST-INPUT-POS         ELPARSE 
00148                                         WS-PROCESS-SW             ELPARSE 
00149                                         WS-TYPE-DATE-SW           ELPARSE 
00150                                         WS-GROUP-RANGE-SW         ELPARSE 
00151                                         WS-SECTION-RANGE-SW.      ELPARSE 
00152      MOVE WS-INPUT-DATA              TO WS-CONTROL-RECORD.        ELPARSE 
00153      MOVE CONTROL-RECORD-CHARS   (2) TO CR-TRANSACTION-TYPE.      ELPARSE 
00154      MOVE CONTROL-RECORD-CHARS   (3) TO CR-RECORD-TYPE.           ELPARSE 
00155      IF CONTROL-RECORD-CHARS (4) NOT = '/'                        ELPARSE 
00156          PERFORM 00025-SIGNAL-INVALID-DELIMITER                   ELPARSE 
00157      ELSE IF PROCESS-MESSAGE                                      ELPARSE 
00158          PERFORM 00027-CHECK-SYNTAX-FOR-COMMONX                   ELPARSE 
00159      SKIP1                                                        ELPARSE 
00160 *                                                          *      ELPARSE 
00161 *        CHECK SYNTAX FOR ALL OTHER TYPES                  *      ELPARSE 
00162 *                                                          *      ELPARSE 
00163      ELSE                                                         ELPARSE 
00164 ***************************************************************** ELPARSE 
00165 * SYNTAX CHECK FOR ALL OTHER COMMANDS WILL BEGIN HERE.          * ELPARSE 
00166 ***************************************************************** ELPARSE 
00167          PERFORM 00098-FIND-THE-END-OF-CONTROLX                   ELPARSE 
00168          VARYING WS-CHAR-IDX FROM 72 BY -1                        ELPARSE 
00169                  UNTIL   WS-LAST-INPUT-POS > ZERO                 ELPARSE 
00170          SET  WS-CHAR-IDX TO 4                                    ELPARSE 
00171          PERFORM 00105-DETERMINE-WHAT-KEY-ELEME.                  ELPARSE 
00172      SKIP1                                                        ELPARSE 
00173      GOBACK.                                                      ELPARSE 
00174      EJECT                                                        ELPARSE 
00175                                                                   ELPARSE 
00176                                                                   ELPARSE 
00177 ************************************************************      ELPARSE 
00178 *                                                          *      ELPARSE 
00179 *        SIGNAL INVALID DELIMITER                          *      ELPARSE 
00180 *                                                          *      ELPARSE 
00181 ************************************************************      ELPARSE 
00182  00025-SIGNAL-INVALID-DELIMITER.                                  ELPARSE 
00183      SET  DELIMITER-INVALID          TO TRUE.                     ELPARSE 
00184      EJECT                                                        ELPARSE 
00185                                                                   ELPARSE 
00186                                                                   ELPARSE 
00187 ************************************************************      ELPARSE 
00188 *                                                          *      ELPARSE 
00189 *        CHECK SYNTAX FOR COMMON MESSAGE TYPE              *      ELPARSE 
00190 *                                                          *      ELPARSE 
00191 ************************************************************      ELPARSE 
00192  00027-CHECK-SYNTAX-FOR-COMMONX.                                  ELPARSE 
00193 ***************************************************************** ELPARSE 
00194 *      REQUIRED SYNTAX FOR A MESSAGE COMMAND IS '+AM//1'        * ELPARSE 
00195 * THE 'A' CAN ALSO BE 'C' OR 'D' OR 'R'.  THE MESSAGE INDICATOR * ELPARSE 
00196 * 'M' MUST BE FOLLOWED BY A DOUBLE SLASH, '//', WHICH MUST THEN * ELPARSE 
00197 * BE FOLLOWED BY THE MESSAGE NUMBER.  IF THIS SYNTAX IS NOT     * ELPARSE 
00198 * FOLLOWED, THE MESSAGE COMMAND CANNOT BE PROCESSED.            * ELPARSE 
00199 ***************************************************************** ELPARSE 
00200      IF CONTROL-RECORD-CHARS (5) NOT = '/'                        ELPARSE 
00201          PERFORM 00025-SIGNAL-INVALID-DELIMITER                   ELPARSE 
00202      ELSE PERFORM 00037-CHECK-SYNTAX-FOR-MESSAGE.                 ELPARSE 
00203      EJECT                                                        ELPARSE 
00204                                                                   ELPARSE 
00205                                                                   ELPARSE 
00206 ************************************************************      ELPARSE 
00207 *                                                          *      ELPARSE 
00208 *        CHECK SYNTAX FOR MESSAGE POINTER                  *      ELPARSE 
00209 *                                                          *      ELPARSE 
00210 ************************************************************      ELPARSE 
00211  00037-CHECK-SYNTAX-FOR-MESSAGE.                                  ELPARSE 
00212 ***************************************************************** ELPARSE 
00213 * IF THE 6TH POSITION OF THE COMMAND IS AN 'X', THIS IS AN      * ELPARSE 
00214 * INVALID USE OF THE UNIQUE MESSAGE INDICATOR.                  * ELPARSE 
00215 ***************************************************************** ELPARSE 
00216      IF CONTROL-RECORD-CHARS (6) = 'X'                            ELPARSE 
00217          PERFORM 00044-SIGNAL-INVALID-USE-OF-UN                   ELPARSE 
00218      ELSE PERFORM 00046-EXTRACT-MESSAGE-POINTER.                  ELPARSE 
00219                                                                   ELPARSE 
00220                                                                   ELPARSE 
00221 ************************************************************      ELPARSE 
00222 *                                                          *      ELPARSE 
00223 *        SIGNAL INVALID USE OF UNIQUE MESSAGE INDICATOR    *      ELPARSE 
00224 *                                                          *      ELPARSE 
00225 ************************************************************      ELPARSE 
00226  00044-SIGNAL-INVALID-USE-OF-UN.                                  ELPARSE 
00227      SET  UNIQUE-IND-INVALID  TO  TRUE.                           ELPARSE 
00228      EJECT                                                        ELPARSE 
00229                                                                   ELPARSE 
00230                                                                   ELPARSE 
00231 ************************************************************      ELPARSE 
00232 *                                                          *      ELPARSE 
00233 *        EXTRACT MESSAGE POINTER                           *      ELPARSE 
00234 *                                                          *      ELPARSE 
00235 ************************************************************      ELPARSE 
00236  00046-EXTRACT-MESSAGE-POINTER.                                   ELPARSE 
00237      SET  WS-PTR-IDX                 TO 1.                        ELPARSE 
00238      SET  WS-CHAR-IDX                TO 6.                        ELPARSE 
00239      MOVE SPACES                     TO WS-MESSAGE-PTR.           ELPARSE 
00240      PERFORM 00068-HOLD-MESSAGE-POINTER-CHA                       ELPARSE 
00241          UNTIL CONTROL-RECORD-CHARS (WS-CHAR-IDX) = ',' OR        ELPARSE 
00242              'X' OR SPACE                                         ELPARSE 
00243                  OR    WS-PTR-IDX > 6                             ELPARSE 
00244                  OR    NOT ERROR-FREE.                            ELPARSE 
00245 ***********************************************                   ELPARSE 
00246 ** WE WILL FLAG THE POINTER AS INVALID IF:   **                   ELPARSE 
00247 ** 1.) NO MESSAGE NUMBER WAS ENTERED         **                   ELPARSE 
00248 ** 2.) A 'X' WAS GIVEN                       **                   ELPARSE 
00249 ** 3.) THE MESSAGE NUMBER  EXCEEDED 5 DIGITS **                   ELPARSE 
00250 ***********************************************                   ELPARSE 
00251      IF WS-PTR-IDX > 6  OR                                        ELPARSE 
00252                 WS-PTR-IDX = 1                                    ELPARSE 
00253          PERFORM 00076-SIGNAL-MESSAGE-POINTER-I                   ELPARSE 
00254      ELSE IF (CONTROL-RECORD-CHARS (WS-CHAR-IDX) = ',' OR         ELPARSE 
00255          SPACE)                                                   ELPARSE 
00256                                 AND                               ELPARSE 
00257                  ERROR-FREE                                       ELPARSE 
00258          PERFORM 00078-INSERT-VALID-MESSAGE-POI.                  ELPARSE 
00259 *************************************************************     ELPARSE 
00260 ** THERE IS A LIMIT OF ONLY ONE MESSAGE POINTER FOR ANY    **     ELPARSE 
00261 ** MESSAGE TRANSACTION. WE WILL PASS A MESSAGE COUNT OF 2  **     ELPARSE 
00262 ** SO MAINLINE CAN ISSUE A WARNING ABOUT TOO MANY POINTERS **     ELPARSE 
00263 ** EXISTING. HOWEVER, WE WILL PASS THE FIRST POINTER IF    **     ELPARSE 
00264 ** VALID SO IT MAY BE PROCESSED.                           **     ELPARSE 
00265 *************************************************************     ELPARSE 
00266      PERFORM 00171-INCREMENT-CHARACTER-INDE.                      ELPARSE 
00267      IF CONTROL-RECORD-CHARS (WS-CHAR-IDX) NOT = SPACE            ELPARSE 
00268          PERFORM 00089-BUMP-MESSAGE-COUNT-TO-IN.                  ELPARSE 
00269      EJECT                                                        ELPARSE 
00270                                                                   ELPARSE 
00271                                                                   ELPARSE 
00272 ************************************************************      ELPARSE 
00273 *                                                          *      ELPARSE 
00274 *        HOLD MESSAGE POINTER CHARACTERS                   *      ELPARSE 
00275 *                                                          *      ELPARSE 
00276 ************************************************************      ELPARSE 
00277  00068-HOLD-MESSAGE-POINTER-CHA.                                  ELPARSE 
00278      IF CONTROL-RECORD-CHARS (WS-CHAR-IDX) IS NUMERIC             ELPARSE 
00279          PERFORM 00072-STORE-MESSAGE-POINTER-CH                   ELPARSE 
00280      ELSE PERFORM 00076-SIGNAL-MESSAGE-POINTER-I.                 ELPARSE 
00281      PERFORM 00171-INCREMENT-CHARACTER-INDE.                      ELPARSE 
00282                                                                   ELPARSE 
00283                                                                   ELPARSE 
00284 ************************************************************      ELPARSE 
00285 *                                                          *      ELPARSE 
00286 *        STORE MESSAGE POINTER CHARACTER                   *      ELPARSE 
00287 *                                                          *      ELPARSE 
00288 ************************************************************      ELPARSE 
00289  00072-STORE-MESSAGE-POINTER-CH.                                  ELPARSE 
00290      MOVE CONTROL-RECORD-CHARS (WS-CHAR-IDX)   TO                 ELPARSE 
00291           WS-PTR-CHARS (WS-PTR-IDX).                              ELPARSE 
00292      SET  WS-PTR-IDX UP BY 1.                                     ELPARSE 
00293      EJECT                                                        ELPARSE 
00294                                                                   ELPARSE 
00295                                                                   ELPARSE 
00296 ************************************************************      ELPARSE 
00297 *                                                          *      ELPARSE 
00298 *        SIGNAL MESSAGE POINTER INVALID                    *      ELPARSE 
00299 *                                                          *      ELPARSE 
00300 ************************************************************      ELPARSE 
00301  00076-SIGNAL-MESSAGE-POINTER-I.                                  ELPARSE 
00302      SET MSG-PTR-INVALID                     TO TRUE.             ELPARSE 
00303      EJECT                                                        ELPARSE 
00304                                                                   ELPARSE 
00305                                                                   ELPARSE 
00306 ************************************************************      ELPARSE 
00307 *                                                          *      ELPARSE 
00308 *        INSERT VALID MESSAGE POINTER                      *      ELPARSE 
00309 *                                                          *      ELPARSE 
00310 ************************************************************      ELPARSE 
00311  00078-INSERT-VALID-MESSAGE-POI.                                  ELPARSE 
00312      SET     WS-MOVE-POS  TO WS-PTR-IDX.                          ELPARSE 
00313      COMPUTE WS-MOVE-POS  =  5 - WS-MOVE-POS + 2.                 ELPARSE 
00314      ADD     +1           TO CR-NUMBER-OF-MESSAGES.               ELPARSE 
00315      MOVE   WS-COMMON-MSG TO CR-MESSAGE-POINTER                   ELPARSE 
00316          (CR-NUMBER-OF-MESSAGES).                                 ELPARSE 
00317      STRING  WS-MESSAGE-PTR  DELIMITED BY SIZE                    ELPARSE 
00318              INTO            CR-MESSAGE-POINTER                   ELPARSE 
00319          (CR-NUMBER-OF-MESSAGES)                                  ELPARSE 
00320              POINTER         WS-MOVE-POS.                         ELPARSE 
00321      MOVE WS-HOLD-MSG-ACTION                                      ELPARSE 
00322                           TO CR-MESSAGE-ACTION                    ELPARSE 
00323          (CR-NUMBER-OF-MESSAGES).                                 ELPARSE 
00324      INITIALIZE WS-HOLD-MSG-ACTION.                               ELPARSE 
00325      EJECT                                                        ELPARSE 
00326                                                                   ELPARSE 
00327                                                                   ELPARSE 
00328 ************************************************************      ELPARSE 
00329 *                                                          *      ELPARSE 
00330 *        BUMP MESSAGE COUNT TO INDICATE TOO MANY POINTERS  *      ELPARSE 
00331 *                                                          *      ELPARSE 
00332 ************************************************************      ELPARSE 
00333  00089-BUMP-MESSAGE-COUNT-TO-IN.                                  ELPARSE 
00334      MOVE +2              TO CR-NUMBER-OF-MESSAGES.               ELPARSE 
00335                                                                   ELPARSE 
00336                                                                   ELPARSE 
00337 ************************************************************      ELPARSE 
00338 *                                                          *      ELPARSE 
00339 *        FIND THE END OF CONTROL RECORD INPUT              *      ELPARSE 
00340 *                                                          *      ELPARSE 
00341 ************************************************************      ELPARSE 
00342  00098-FIND-THE-END-OF-CONTROLX.                                  ELPARSE 
00343      IF CONTROL-RECORD-CHARS (WS-CHAR-IDX) NOT = SPACE  AND       ELPARSE 
00344                  LOW-VALUES                                       ELPARSE 
00345          PERFORM 00100-SAVE-POSITION-OF-LAST-CH.                  ELPARSE 
00346                                                                   ELPARSE 
00347                                                                   ELPARSE 
00348 ************************************************************      ELPARSE 
00349 *                                                          *      ELPARSE 
00350 *        SAVE POSITION OF LAST CHARACTER                   *      ELPARSE 
00351 *                                                          *      ELPARSE 
00352 ************************************************************      ELPARSE 
00353  00100-SAVE-POSITION-OF-LAST-CH.                                  ELPARSE 
00354      IF WS-CHAR-IDX < 72                                          ELPARSE 
00355          PERFORM 00103-BUMP-CHARACTER-INDEX.                      ELPARSE 
00356      SET WS-LAST-INPUT-POS        TO WS-CHAR-IDX.                 ELPARSE 
00357                                                                   ELPARSE 
00358                                                                   ELPARSE 
00359 ************************************************************      ELPARSE 
00360 *                                                          *      ELPARSE 
00361 *        BUMP CHARACTER INDEX                              *      ELPARSE 
00362 *                                                          *      ELPARSE 
00363 ************************************************************      ELPARSE 
00364  00103-BUMP-CHARACTER-INDEX.                                      ELPARSE 
00365      SET WS-CHAR-IDX UP BY 1.                                     ELPARSE 
00366      EJECT                                                        ELPARSE 
00367                                                                   ELPARSE 
00368                                                                   ELPARSE 
00369 ************************************************************      ELPARSE 
00370 *                                                          *      ELPARSE 
00371 *        DETERMINE WHAT KEY ELEMENTS ARE REQUIRED          *      ELPARSE 
00372 *                                                          *      ELPARSE 
00373 ************************************************************      ELPARSE 
00374  00105-DETERMINE-WHAT-KEY-ELEME.                                  ELPARSE 
00375      PERFORM 00124-EXTRACT-ALL-KEY-ELEMENTS.                      ELPARSE 
00376 *******************************************************           ELPARSE 
00377 *  IF THE COMMAND ENTERED WAS AN ADD GROUP, CONTRACT, *           ELPARSE 
00378 *  MULTIPLE GROUPS, OR MULTIPLE SECTIONS (+AG, +AC,   *           ELPARSE 
00379 *  +AN, +AS), MESSAGE NUMBERS MUST ALSO BE ENTERED OR *           ELPARSE 
00380 *  THIS IS FLAGGED AS AN ERROR.                       *           ELPARSE 
00381 *******************************************************           ELPARSE 
00382      IF  ADD-FUNCTION                                             ELPARSE 
00383              AND (PROCESS-GROUP OR PROCESS-CONTRACT OR            ELPARSE 
00384                   PROCESS-MULT-GROUPS OR PROCESS-MULT-SECTIONS)   ELPARSE 
00385              AND CR-NUMBER-OF-MESSAGES = ZERO                     ELPARSE 
00386              AND ERROR-FREE                                       ELPARSE 
00387          PERFORM 00076-SIGNAL-MESSAGE-POINTER-I.                  ELPARSE 
00388      IF ERROR-FREE AND CR-EFFECTIVE-DATE NOT = LOW-VALUES         ELPARSE 
00389          PERFORM 00371-CONVERT-INPUT-EFFECTIVEX.                  ELPARSE 
00390 ***********************************************************       ELPARSE 
00391 ** THE TERMINATION DATE IS NOT PART OF THE KEY AND IS AN **       ELPARSE 
00392 ** OPTIONAL FEATURE TO THE USER.  IF NO TERMINATION DATE **       ELPARSE 
00393 ** IS PROVIDED, A DEFAULT TERMINATION DATE OF 12/31/99   **       ELPARSE 
00394 ** WILL BE SUPPLIED BY THE SYSTEM.                       **       ELPARSE 
00395 ***********************************************************       ELPARSE 
00396      IF ERROR-FREE                               AND              ELPARSE 
00397                 CR-TERMINATION-DATE = SPACES             AND      ELPARSE 
00398                 ADD-FUNCTION                                      ELPARSE 
00399          PERFORM 00388-USE-DEFAULT-TERMINATIONX                   ELPARSE 
00400      ELSE IF ERROR-FREE                               AND         ELPARSE 
00401                 CR-TERMINATION-DATE NOT = SPACES                  ELPARSE 
00402          PERFORM 00379-CONVERT-INPUT-TERMINATIO.                  ELPARSE 
00403      IF ERROR-FREE                               AND              ELPARSE 
00404                 CR-NUMBER-OF-MESSAGES > 1                         ELPARSE 
00405          PERFORM 00391-SORT-MESSAGE-POINTERS-IN.                  ELPARSE 
00406      EJECT                                                        ELPARSE 
00407                                                                   ELPARSE 
00408                                                                   ELPARSE 
00409 ************************************************************      ELPARSE 
00410 *                                                          *      ELPARSE 
00411 *        EXTRACT ALL KEY ELEMENTS                          *      ELPARSE 
00412 *                                                          *      ELPARSE 
00413 ************************************************************      ELPARSE 
00414  00124-EXTRACT-ALL-KEY-ELEMENTS.                                  ELPARSE 
00415 **********************************************************        ELPARSE 
00416 * ALL OF THE FOLLOWING COMMANDS MUST HAVE AN EFFECTIVE   *        ELPARSE 
00417 * DATE, AND MESSAGE NUMBERS TO REFERENCE.  TERMINATION   *        ELPARSE 
00418 * DATE IS OPTIONAL.                                      *        ELPARSE 
00419 *                                                        *        ELPARSE 
00420 * GROUP COMMAND KEY FIELDS:  GROUP, SECTION, FAMILY      *        ELPARSE 
00421 *    RELATIONSHIP CODE.  THE LAST 2 MENTIONED FIELDS MAY *        ELPARSE 
00422 *    BE GENERIC.                                         *        ELPARSE 
00423 * CONTRACT COMMAND KEY FIELDS:  GROUP, SECTION, LINE OF  *        ELPARSE 
00424 *    BUSINESS, PROVIDER CONTROL, AND FAMILY RELATIONSHIP *        ELPARSE 
00425 *    CODE.  THE LAST 4 MENTIONED FIELDS MAY BE GENERIC.  *        ELPARSE 
00426 * MULTIPLE GROUP COMMAND KEY FIELDS: START GROUP AND END *        ELPARSE 
00427 *    GROUP.                                              *        ELPARSE 
00428 * MULTIPLE SECTIONS COMMAND KEY FIELDS: GROUP, START     *        ELPARSE 
00429 *    SECTION, AND END SECTION.                           *        ELPARSE 
00430 **********************************************************        ELPARSE 
00431      SET  CHAR-VALID                TO TRUE.                      ELPARSE 
00432      SET  KEY-NOT-FOUND             TO TRUE.                      ELPARSE 
00433      PERFORM 00150-EXTRACT-GROUP-NUMBER.                          ELPARSE 
00434      IF  ERROR-FREE  AND  ADD-FUNCTION                            ELPARSE 
00435              AND PROCESS-MULT-GROUPS                              ELPARSE 
00436          PERFORM 00160-EXTRACT-END-GROUP-NUMBER                   ELPARSE 
00437      ELSE PERFORM 00163-CONTINUE-EXTRACTING-OTHE.                 ELPARSE 
00438      IF ERROR-FREE                                                ELPARSE 
00439          PERFORM 00304-EXTRACT-EFFECTIVE-DATE.                    ELPARSE 
00440      IF   ERROR-FREE                                              ELPARSE 
00441              AND  KEY-NOT-FOUND                                   ELPARSE 
00442              AND  NOT STOP-PROCESSING                             ELPARSE 
00443          PERFORM 00320-EXTRACT-TERMINATION-DATE.                  ELPARSE 
00444      IF KEY-FOUND        AND                                      ELPARSE 
00445                 ERROR-FREE                                        ELPARSE 
00446          PERFORM 00330-EXTRACT-ALL-MESSAGE-POIN                   ELPARSE 
00447      ELSE IF (ADD-FUNCTION OR CHANGE-FUNCTION)  AND               ELPARSE 
00448                 PROCESS-GROUP AND ERROR-FREE                      ELPARSE 
00449          PERFORM 00025-SIGNAL-INVALID-DELIMITER.                  ELPARSE 
00450      EJECT                                                        ELPARSE 
00451                                                                   ELPARSE 
00452                                                                   ELPARSE 
00453 ************************************************************      ELPARSE 
00454 *                                                          *      ELPARSE 
00455 *        EXTRACT GROUP NUMBER                              *      ELPARSE 
00456 *                                                          *      ELPARSE 
00457 ************************************************************      ELPARSE 
00458  00150-EXTRACT-GROUP-NUMBER.                                      ELPARSE 
00459 **********************************************************        ELPARSE 
00460 * THE GROUP NUMBER CAN BE AT MOST 6 CHARACTERS IN LENGTH *        ELPARSE 
00461 **********************************************************        ELPARSE 
00462      SET  WS-SIX-IDX TO 1.                                        ELPARSE 
00463      INITIALIZE  WS-SIX-CHARS-FIELD.                              ELPARSE 
00464      PERFORM 00171-INCREMENT-CHARACTER-INDE.                      ELPARSE 
00465      PERFORM 00218-HOLD-CHARACTERS-IN-TABLE                       ELPARSE 
00466          UNTIL CONTROL-RECORD-CHARS (WS-CHAR-IDX) = '/'           ELPARSE 
00467                  OR    WS-SIX-IDX > 7                             ELPARSE 
00468                  OR    NOT ERROR-FREE.                            ELPARSE 
00469      IF  ERROR-FREE  AND  CONTROL-RECORD-CHARS (WS-CHAR-IDX)      ELPARSE 
00470          = '/'                                                    ELPARSE 
00471              AND WS-SIX-IDX > 1                                   ELPARSE 
00472          PERFORM 00182-INSERT-VALID-GROUP-NUMBE                   ELPARSE 
00473      SKIP1                                                        ELPARSE 
00474 *                                                          *      ELPARSE 
00475 *        SIGNAL GROUP NUMBER INVALID                       *      ELPARSE 
00476 *                                                          *      ELPARSE 
00477      ELSE                                                         ELPARSE 
00478          SET GRP-NBR-INVALID         TO TRUE.                     ELPARSE 
00479      SKIP1                                                        ELPARSE 
00480      EJECT                                                        ELPARSE 
00481                                                                   ELPARSE 
00482                                                                   ELPARSE 
00483 ************************************************************      ELPARSE 
00484 *                                                          *      ELPARSE 
00485 *        EXTRACT END GROUP NUMBER RANGE                    *      ELPARSE 
00486 *                                                          *      ELPARSE 
00487 ************************************************************      ELPARSE 
00488  00160-EXTRACT-END-GROUP-NUMBER.                                  ELPARSE 
00489      SET END-GROUP-NBR  TO  TRUE.                                 ELPARSE 
00490      PERFORM 00150-EXTRACT-GROUP-NUMBER.                          ELPARSE 
00491      EJECT                                                        ELPARSE 
00492                                                                   ELPARSE 
00493                                                                   ELPARSE 
00494 ************************************************************      ELPARSE 
00495 *                                                          *      ELPARSE 
00496 *        CONTINUE EXTRACTING OTHER FIELDS                  *      ELPARSE 
00497 *                                                          *      ELPARSE 
00498 ************************************************************      ELPARSE 
00499  00163-CONTINUE-EXTRACTING-OTHE.                                  ELPARSE 
00500      IF ERROR-FREE                                                ELPARSE 
00501          PERFORM 00198-EXTRACT-SECTION-NUMBER.                    ELPARSE 
00502      IF  ERROR-FREE  AND  ADD-FUNCTION                            ELPARSE 
00503              AND PROCESS-MULT-SECTIONS                            ELPARSE 
00504          PERFORM 00213-EXTRACT-END-SECTION-NUMB                   ELPARSE 
00505      ELSE PERFORM 00167-KEEP-EXTRACTING-OTHER-FI.                 ELPARSE 
00506                                                                   ELPARSE 
00507                                                                   ELPARSE 
00508 ************************************************************      ELPARSE 
00509 *                                                          *      ELPARSE 
00510 *        KEEP EXTRACTING OTHER FIELDS                      *      ELPARSE 
00511 *                                                          *      ELPARSE 
00512 ************************************************************      ELPARSE 
00513  00167-KEEP-EXTRACTING-OTHER-FI.                                  ELPARSE 
00514      IF  ERROR-FREE                                               ELPARSE 
00515              AND PROCESS-CONTRACT                                 ELPARSE 
00516          PERFORM 00257-EXTRACT-LINE-OF-BUSINESS.                  ELPARSE 
00517      IF ERROR-FREE                                                ELPARSE 
00518              AND PROCESS-CONTRACT                                 ELPARSE 
00519          PERFORM 00272-EXTRACT-PROVIDER-CONTROL.                  ELPARSE 
00520      IF ERROR-FREE                                                ELPARSE 
00521          PERFORM 00289-EXTRACT-FAMILY-RELATIONS.                  ELPARSE 
00522      EJECT                                                        ELPARSE 
00523                                                                   ELPARSE 
00524                                                                   ELPARSE 
00525 ************************************************************      ELPARSE 
00526 *                                                          *      ELPARSE 
00527 *        INCREMENT CHARACTER INDEX                         *      ELPARSE 
00528 *                                                          *      ELPARSE 
00529 ************************************************************      ELPARSE 
00530  00171-INCREMENT-CHARACTER-INDE.                                  ELPARSE 
00531      SET WS-CHAR-IDX UP BY 1.                                     ELPARSE 
00532      IF WS-CHAR-IDX = WS-LAST-INPUT-POS                           ELPARSE 
00533          PERFORM 00174-SIGNAL-STOP-PROCESSING.                    ELPARSE 
00534                                                                   ELPARSE 
00535                                                                   ELPARSE 
00536 ************************************************************      ELPARSE 
00537 *                                                          *      ELPARSE 
00538 *        SIGNAL STOP PROCESSING                            *      ELPARSE 
00539 *                                                          *      ELPARSE 
00540 ************************************************************      ELPARSE 
00541  00174-SIGNAL-STOP-PROCESSING.                                    ELPARSE 
00542      SET STOP-PROCESSING      TO TRUE.                            ELPARSE 
00543                                                                   ELPARSE 
00544                                                                   ELPARSE 
00545 ************************************************************      ELPARSE 
00546 *                                                          *      ELPARSE 
00547 *        STORE CHARACTER FOR SIX DIGIT FIELD               *      ELPARSE 
00548 *                                                          *      ELPARSE 
00549 ************************************************************      ELPARSE 
00550  00178-STORE-CHARACTER-FOR-SIXX.                                  ELPARSE 
00551      MOVE CONTROL-RECORD-CHARS (WS-CHAR-IDX)                      ELPARSE 
00552                                  TO WS-SIX-CHARS (WS-SIX-IDX).    ELPARSE 
00553      SET WS-SIX-IDX UP BY 1.                                      ELPARSE 
00554      EJECT                                                        ELPARSE 
00555                                                                   ELPARSE 
00556                                                                   ELPARSE 
00557 ************************************************************      ELPARSE 
00558 *                                                          *      ELPARSE 
00559 *        INSERT VALID GROUP NUMBER                         *      ELPARSE 
00560 *                                                          *      ELPARSE 
00561 ************************************************************      ELPARSE 
00562  00182-INSERT-VALID-GROUP-NUMBE.                                  ELPARSE 
00563      SET     WS-MOVE-POS         TO WS-SIX-IDX.                   ELPARSE 
00564      COMPUTE WS-MOVE-POS = LENGTH OF CR-GROUP-NUMBER -            ELPARSE 
00565                            WS-MOVE-POS + 2.                       ELPARSE 
00566      IF END-GROUP-NBR                                             ELPARSE 
00567          PERFORM 00188-SAVE-END-GROUP-NUMBER-RA                   ELPARSE 
00568      SKIP1                                                        ELPARSE 
00569 *                                                          *      ELPARSE 
00570 *        SAVE FIRST GROUP NUMBER                           *      ELPARSE 
00571 *                                                          *      ELPARSE 
00572      ELSE                                                         ELPARSE 
00573          MOVE ZEROS                  TO CR-GROUP-NUMBER           ELPARSE 
00574          STRING  WS-SIX-CHARS-FIELD     DELIMITED BY SIZE         ELPARSE 
00575              INTO                   CR-GROUP-NUMBER               ELPARSE 
00576              POINTER                WS-MOVE-POS.                  ELPARSE 
00577      SKIP1                                                        ELPARSE 
00578                                                                   ELPARSE 
00579                                                                   ELPARSE 
00580 ************************************************************      ELPARSE 
00581 *                                                          *      ELPARSE 
00582 *        SAVE END GROUP NUMBER RANGE                       *      ELPARSE 
00583 *                                                          *      ELPARSE 
00584 ************************************************************      ELPARSE 
00585  00188-SAVE-END-GROUP-NUMBER-RA.                                  ELPARSE 
00586      MOVE ZEROS                  TO CR-TO-GROUP-NUMBER-RANGE.     ELPARSE 
00587      STRING  WS-SIX-CHARS-FIELD     DELIMITED BY SIZE             ELPARSE 
00588              INTO                   CR-TO-GROUP-NUMBER-RANGE      ELPARSE 
00589              POINTER                WS-MOVE-POS.                  ELPARSE 
00590      EJECT                                                        ELPARSE 
00591                                                                   ELPARSE 
00592                                                                   ELPARSE 
00593 ************************************************************      ELPARSE 
00594 *                                                          *      ELPARSE 
00595 *        EXTRACT SECTION NUMBER                            *      ELPARSE 
00596 *                                                          *      ELPARSE 
00597 ************************************************************      ELPARSE 
00598  00198-EXTRACT-SECTION-NUMBER.                                    ELPARSE 
00599 ***************************************************************   ELPARSE 
00600 ** THE SECTION NUMBER IS AT MOST 4 CHARACTERS IN LENGTH OR   **   ELPARSE 
00601 ** IT IS THE GENERIC CHARACTER.                              **   ELPARSE 
00602 ** THE GENERIC INDICATOR ASTERISK (*), IS NOT ALLOWED WHEN   **   ELPARSE 
00603 ** THE MULTIPLE SECTIONS WITHIN A GROUP COMMAND IS USED, I.E.**   ELPARSE 
00604 ** '+AS'.                                                    **   ELPARSE 
00605 ***************************************************************   ELPARSE 
00606      SET  WS-SIX-IDX TO 1.                                        ELPARSE 
00607      MOVE SPACES     TO WS-SIX-CHARS-FIELD.                       ELPARSE 
00608      PERFORM 00171-INCREMENT-CHARACTER-INDE.                      ELPARSE 
00609      PERFORM 00218-HOLD-CHARACTERS-IN-TABLE                       ELPARSE 
00610          UNTIL CONTROL-RECORD-CHARS (WS-CHAR-IDX) = '/' OR '*'    ELPARSE 
00611                  OR    WS-SIX-IDX > 4                             ELPARSE 
00612                  OR    NOT ERROR-FREE.                            ELPARSE 
00613      IF  CONTROL-RECORD-CHARS (WS-CHAR-IDX) = '*'                 ELPARSE 
00614              AND WS-SIX-IDX = 1                                   ELPARSE 
00615              AND NOT END-SECTION-NBR                              ELPARSE 
00616          PERFORM 00171-INCREMENT-CHARACTER-INDE                   ELPARSE 
00617      ELSE IF  ERROR-FREE  AND  CONTROL-RECORD-CHARS               ELPARSE 
00618          (WS-CHAR-IDX) = '/'                                      ELPARSE 
00619              AND WS-SIX-IDX > 1                                   ELPARSE 
00620          PERFORM 00224-INSERT-VALID-SECTION-NUM                   ELPARSE 
00621      SKIP1                                                        ELPARSE 
00622 *                                                          *      ELPARSE 
00623 *        SIGNAL SECTION NUMBER INVALID                     *      ELPARSE 
00624 *                                                          *      ELPARSE 
00625      ELSE                                                         ELPARSE 
00626          SET SCT-NBR-INVALID         TO TRUE.                     ELPARSE 
00627      SKIP1                                                        ELPARSE 
00628                                                                   ELPARSE 
00629                                                                   ELPARSE 
00630 ************************************************************      ELPARSE 
00631 *                                                          *      ELPARSE 
00632 *        EXTRACT END SECTION NUMBER RANGE                  *      ELPARSE 
00633 *                                                          *      ELPARSE 
00634 ************************************************************      ELPARSE 
00635  00213-EXTRACT-END-SECTION-NUMB.                                  ELPARSE 
00636      SET END-SECTION-NBR  TO  TRUE.                               ELPARSE 
00637      PERFORM 00198-EXTRACT-SECTION-NUMBER.                        ELPARSE 
00638                                                                   ELPARSE 
00639                                                                   ELPARSE 
00640 ************************************************************      ELPARSE 
00641 *                                                          *      ELPARSE 
00642 *        INDICATE END OF KEY FOUND                         *      ELPARSE 
00643 *                                                          *      ELPARSE 
00644 ************************************************************      ELPARSE 
00645  00216-INDICATE-END-OF-KEY-FOUN.                                  ELPARSE 
00646      SET  KEY-FOUND         TO TRUE.                              ELPARSE 
00647      EJECT                                                        ELPARSE 
00648                                                                   ELPARSE 
00649                                                                   ELPARSE 
00650 ************************************************************      ELPARSE 
00651 *                                                          *      ELPARSE 
00652 *        HOLD CHARACTERS IN TABLE                          *      ELPARSE 
00653 *                                                          *      ELPARSE 
00654 ************************************************************      ELPARSE 
00655  00218-HOLD-CHARACTERS-IN-TABLE.                                  ELPARSE 
00656      IF (CONTROL-RECORD-CHARS (WS-CHAR-IDX) IS ALPHABETIC)        ELPARSE 
00657                                 OR                                ELPARSE 
00658                 (CONTROL-RECORD-CHARS (WS-CHAR-IDX) IS NUMERIC)   ELPARSE 
00659          PERFORM 00178-STORE-CHARACTER-FOR-SIXX                   ELPARSE 
00660      SKIP1                                                        ELPARSE 
00661 *                                                          *      ELPARSE 
00662 *        SIGNAL CHARACTER INVALID                          *      ELPARSE 
00663 *                                                          *      ELPARSE 
00664      ELSE                                                         ELPARSE 
00665          SET  CHAR-INVALID          TO TRUE.                      ELPARSE 
00666      SKIP1                                                        ELPARSE 
00667      PERFORM 00171-INCREMENT-CHARACTER-INDE.                      ELPARSE 
00668      EJECT                                                        ELPARSE 
00669                                                                   ELPARSE 
00670                                                                   ELPARSE 
00671 ************************************************************      ELPARSE 
00672 *                                                          *      ELPARSE 
00673 *        INSERT VALID SECTION NUMBER                       *      ELPARSE 
00674 *                                                          *      ELPARSE 
00675 ************************************************************      ELPARSE 
00676  00224-INSERT-VALID-SECTION-NUM.                                  ELPARSE 
00677      SET     WS-MOVE-POS         TO WS-SIX-IDX.                   ELPARSE 
00678      COMPUTE WS-MOVE-POS = LENGTH OF CR-SECTION-NUMBER -          ELPARSE 
00679                            WS-MOVE-POS + 2.                       ELPARSE 
00680      IF END-SECTION-NBR                                           ELPARSE 
00681          PERFORM 00230-SAVE-END-SECTION-NUMBERX                   ELPARSE 
00682      SKIP1                                                        ELPARSE 
00683 *                                                          *      ELPARSE 
00684 *        SAVE FIRST SECTION NUMBER                         *      ELPARSE 
00685 *                                                          *      ELPARSE 
00686      ELSE                                                         ELPARSE 
00687          MOVE ZEROS                  TO CR-SECTION-NUMBER         ELPARSE 
00688          STRING  WS-SIX-CHARS-FIELD     DELIMITED BY SIZE         ELPARSE 
00689              INTO                   CR-SECTION-NUMBER             ELPARSE 
00690              POINTER                WS-MOVE-POS.                  ELPARSE 
00691      SKIP1                                                        ELPARSE 
00692                                                                   ELPARSE 
00693                                                                   ELPARSE 
00694 ************************************************************      ELPARSE 
00695 *                                                          *      ELPARSE 
00696 *        SAVE END SECTION NUMBER RANGE                     *      ELPARSE 
00697 *                                                          *      ELPARSE 
00698 ************************************************************      ELPARSE 
00699  00230-SAVE-END-SECTION-NUMBERX.                                  ELPARSE 
00700      MOVE ZEROS                  TO CR-TO-SECT-NUMBER-RANGE.      ELPARSE 
00701      STRING  WS-SIX-CHARS-FIELD     DELIMITED BY SIZE             ELPARSE 
00702              INTO                   CR-TO-SECT-NUMBER-RANGE       ELPARSE 
00703              POINTER                WS-MOVE-POS.                  ELPARSE 
00704                                                                   ELPARSE 
00705                                                                   ELPARSE 
00706 ************************************************************      ELPARSE 
00707 *                                                          *      ELPARSE 
00708 *        INSERT VALID EFFECTIVE DATE                       *      ELPARSE 
00709 *                                                          *      ELPARSE 
00710 ************************************************************      ELPARSE 
00711  00242-INSERT-VALID-EFFECTIVE-D.                                  ELPARSE 
00712      MOVE WS-SIX-CHARS-FIELD     TO CR-EFFECTIVE-DATE.            ELPARSE 
00713      EJECT                                                        ELPARSE 
00714                                                                   ELPARSE 
00715                                                                   ELPARSE 
00716 ************************************************************      ELPARSE 
00717 *                                                          *      ELPARSE 
00718 *        CHECK FOR END OF RECORD KEY                       *      ELPARSE 
00719 *                                                          *      ELPARSE 
00720 ************************************************************      ELPARSE 
00721  00244-CHECK-FOR-END-OF-RECORDX.                                  ELPARSE 
00722 ***************************************************************   ELPARSE 
00723 ** WE WILL CHECK FOR END OF KEY IF NO ERRORS HAVE BEEN FOUND **   ELPARSE 
00724 ** AND THE CONTROL RECORD CHARACTER WE ARE SITTING ON IS '/' **   ELPARSE 
00725 ** BECAUSE THE USER WILL INDICATE END OF KEY WITH A '//'.    **   ELPARSE 
00726 ** HOWEVER THE USERS ARE ABLE TO ELIMINATE FIELDS IN THE     **   ELPARSE 
00727 ** KEY BY PUTTING A '*' IN THAT FIELD'S POSITION WHICH WE    **   ELPARSE 
00728 ** WILL TREAT AS LOW-VALUES FOR THAT FIELD VALUE. WE WILL    **   ELPARSE 
00729 ** SIGNAL AN ERROR IF MORE THAN ONE '*' WAS ENTERED.         **   ELPARSE 
00730 **                    REB ==> 08/10/88                       **   ELPARSE 
00731 ***************************************************************   ELPARSE 
00732      PERFORM 00171-INCREMENT-CHARACTER-INDE.                      ELPARSE 
00733      IF CONTROL-RECORD-CHARS (WS-CHAR-IDX) = '/'                  ELPARSE 
00734          PERFORM 00216-INDICATE-END-OF-KEY-FOUN.                  ELPARSE 
00735      EJECT                                                        ELPARSE 
00736                                                                   ELPARSE 
00737                                                                   ELPARSE 
00738 ************************************************************      ELPARSE 
00739 *                                                          *      ELPARSE 
00740 *        EXTRACT LINE OF BUSINESS                          *      ELPARSE 
00741 *                                                          *      ELPARSE 
00742 ************************************************************      ELPARSE 
00743  00257-EXTRACT-LINE-OF-BUSINESS.                                  ELPARSE 
00744 ***************************************************************   ELPARSE 
00745 ** LINE OF BUSINESS IS 1 CHARACTER IN LENGTH                 **   ELPARSE 
00746 ***************************************************************   ELPARSE 
00747      SET  WS-SIX-IDX TO 1.                                        ELPARSE 
00748      MOVE SPACES     TO WS-SIX-CHARS-FIELD.                       ELPARSE 
00749      PERFORM 00171-INCREMENT-CHARACTER-INDE.                      ELPARSE 
00750      PERFORM 00218-HOLD-CHARACTERS-IN-TABLE                       ELPARSE 
00751          UNTIL CONTROL-RECORD-CHARS (WS-CHAR-IDX) = '/' OR '*'    ELPARSE 
00752                  OR    WS-SIX-IDX > 1                             ELPARSE 
00753                  OR    NOT ERROR-FREE.                            ELPARSE 
00754      IF   CONTROL-RECORD-CHARS (WS-CHAR-IDX) = '*'                ELPARSE 
00755              AND  WS-SIX-IDX = 1                                  ELPARSE 
00756          PERFORM 00171-INCREMENT-CHARACTER-INDE                   ELPARSE 
00757      ELSE IF  ERROR-FREE                                          ELPARSE 
00758              AND CONTROL-RECORD-CHARS (WS-CHAR-IDX) = '/'         ELPARSE 
00759              AND WS-SIX-CHARS (1) IS NUMERIC                      ELPARSE 
00760          PERFORM 00268-INSERT-VALID-LINE-OF-BUS                   ELPARSE 
00761      SKIP1                                                        ELPARSE 
00762 *                                                          *      ELPARSE 
00763 *        SIGNAL LINE OF BUSINESS INVALID                   *      ELPARSE 
00764 *                                                          *      ELPARSE 
00765      ELSE                                                         ELPARSE 
00766          SET  LOB-IND-INVALID    TO TRUE.                         ELPARSE 
00767      SKIP1                                                        ELPARSE 
00768      EJECT                                                        ELPARSE 
00769                                                                   ELPARSE 
00770                                                                   ELPARSE 
00771 ************************************************************      ELPARSE 
00772 *                                                          *      ELPARSE 
00773 *        INSERT VALID LINE OF BUSINESS                     *      ELPARSE 
00774 *                                                          *      ELPARSE 
00775 ************************************************************      ELPARSE 
00776  00268-INSERT-VALID-LINE-OF-BUS.                                  ELPARSE 
00777      MOVE WS-SIX-CHARS (1)   TO CR-LINE-OF-BUSINESS.              ELPARSE 
00778      EJECT                                                        ELPARSE 
00779                                                                   ELPARSE 
00780                                                                   ELPARSE 
00781 ************************************************************      ELPARSE 
00782 *                                                          *      ELPARSE 
00783 *        EXTRACT PROVIDER CONTROL                          *      ELPARSE 
00784 *                                                          *      ELPARSE 
00785 ************************************************************      ELPARSE 
00786  00272-EXTRACT-PROVIDER-CONTROL.                                  ELPARSE 
00787 ***************************************************************   ELPARSE 
00788 **    PROVIDER CONTROL IS 2 CHARACTERS IN LENGTH             **   ELPARSE 
00789 ***************************************************************   ELPARSE 
00790      SET  WS-SIX-IDX TO 1.                                        ELPARSE 
00791      MOVE SPACES     TO WS-SIX-CHARS-FIELD.                       ELPARSE 
00792      PERFORM 00171-INCREMENT-CHARACTER-INDE.                      ELPARSE 
00793      PERFORM 00218-HOLD-CHARACTERS-IN-TABLE                       ELPARSE 
00794          UNTIL CONTROL-RECORD-CHARS (WS-CHAR-IDX) = '/' OR '*'    ELPARSE 
00795                  OR    WS-SIX-IDX > 2                             ELPARSE 
00796                  OR    NOT ERROR-FREE.                            ELPARSE 
00797      IF CONTROL-RECORD-CHARS (WS-CHAR-IDX) = '*' AND              ELPARSE 
00798                 WS-SIX-IDX = 1                                    ELPARSE 
00799          PERFORM 00171-INCREMENT-CHARACTER-INDE                   ELPARSE 
00800      ELSE IF   ERROR-FREE                                         ELPARSE 
00801              AND  CONTROL-RECORD-CHARS (WS-CHAR-IDX) = '/'        ELPARSE 
00802              AND  WS-SIX-IDX > 2                                  ELPARSE 
00803          PERFORM 00285-INSERT-VALID-PROVIDER-CO                   ELPARSE 
00804      SKIP1                                                        ELPARSE 
00805 *                                                          *      ELPARSE 
00806 *        SIGNAL PROVIDER CONTROL INVALID                   *      ELPARSE 
00807 *                                                          *      ELPARSE 
00808      ELSE                                                         ELPARSE 
00809          SET  PROV-CNTL-INVALID        TO TRUE.                   ELPARSE 
00810      SKIP1                                                        ELPARSE 
00811      EJECT                                                        ELPARSE 
00812                                                                   ELPARSE 
00813                                                                   ELPARSE 
00814 ************************************************************      ELPARSE 
00815 *                                                          *      ELPARSE 
00816 *        INSERT VALID PROVIDER CONTROL                     *      ELPARSE 
00817 *                                                          *      ELPARSE 
00818 ************************************************************      ELPARSE 
00819  00285-INSERT-VALID-PROVIDER-CO.                                  ELPARSE 
00820      MOVE WS-SIX-CHARS (1)         TO WS-FIRST-DIGIT.             ELPARSE 
00821      MOVE WS-SIX-CHARS (2)         TO WS-SECOND-DIGIT.            ELPARSE 
00822      MOVE WS-PROV-CNTL             TO CR-PROVIDER-CONTROL.        ELPARSE 
00823      EJECT                                                        ELPARSE 
00824                                                                   ELPARSE 
00825                                                                   ELPARSE 
00826 ************************************************************      ELPARSE 
00827 *                                                          *      ELPARSE 
00828 *        EXTRACT FAMILY RELATIONSHIP                       *      ELPARSE 
00829 *                                                          *      ELPARSE 
00830 ************************************************************      ELPARSE 
00831  00289-EXTRACT-FAMILY-RELATIONS.                                  ELPARSE 
00832 ***************************************************************   ELPARSE 
00833 **    FAMILY RELATIONSHIP CODE IS 1 CHARACTER IN LENGTH      **   ELPARSE 
00834 ***************************************************************   ELPARSE 
00835      SET  WS-SIX-IDX TO 1.                                        ELPARSE 
00836      MOVE SPACES     TO WS-SIX-CHARS-FIELD.                       ELPARSE 
00837      PERFORM 00171-INCREMENT-CHARACTER-INDE.                      ELPARSE 
00838      PERFORM 00218-HOLD-CHARACTERS-IN-TABLE                       ELPARSE 
00839          UNTIL CONTROL-RECORD-CHARS (WS-CHAR-IDX) = '/' OR '*'    ELPARSE 
00840                  OR    WS-SIX-IDX > 1                             ELPARSE 
00841                  OR    NOT ERROR-FREE.                            ELPARSE 
00842      IF CONTROL-RECORD-CHARS (WS-CHAR-IDX) = '*' AND              ELPARSE 
00843                 WS-SIX-IDX = 1                                    ELPARSE 
00844          PERFORM 00171-INCREMENT-CHARACTER-INDE                   ELPARSE 
00845      ELSE IF   ERROR-FREE                                         ELPARSE 
00846              AND  CONTROL-RECORD-CHARS (WS-CHAR-IDX) = '/'        ELPARSE 
00847              AND  WS-SIX-IDX > 1                                  ELPARSE 
00848          PERFORM 00300-INSERT-VALID-FAMILY-RELA                   ELPARSE 
00849      SKIP1                                                        ELPARSE 
00850 *                                                          *      ELPARSE 
00851 *        SIGNAL FAMILY RELATION INVALID                    *      ELPARSE 
00852 *                                                          *      ELPARSE 
00853      ELSE                                                         ELPARSE 
00854          SET  FAM-REL-INVALID    TO TRUE.                         ELPARSE 
00855      SKIP1                                                        ELPARSE 
00856      EJECT                                                        ELPARSE 
00857                                                                   ELPARSE 
00858                                                                   ELPARSE 
00859 ************************************************************      ELPARSE 
00860 *                                                          *      ELPARSE 
00861 *        INSERT VALID FAMILY RELATION                      *      ELPARSE 
00862 *                                                          *      ELPARSE 
00863 ************************************************************      ELPARSE 
00864  00300-INSERT-VALID-FAMILY-RELA.                                  ELPARSE 
00865      MOVE WS-SIX-CHARS (1)   TO CR-FAMILY-RELATION.               ELPARSE 
00866      EJECT                                                        ELPARSE 
00867                                                                   ELPARSE 
00868                                                                   ELPARSE 
00869 ************************************************************      ELPARSE 
00870 *                                                          *      ELPARSE 
00871 *        EXTRACT EFFECTIVE DATE                            *      ELPARSE 
00872 *                                                          *      ELPARSE 
00873 ************************************************************      ELPARSE 
00874  00304-EXTRACT-EFFECTIVE-DATE.                                    ELPARSE 
00875      SET EXTRACTING-EFF-DATE   TO  TRUE.                          ELPARSE 
00876      SET  WS-SIX-IDX           TO 1.                              ELPARSE 
00877      MOVE SPACES               TO WS-SIX-CHARS-FIELD.             ELPARSE 
00878      PERFORM 00171-INCREMENT-CHARACTER-INDE.                      ELPARSE 
00879      PERFORM 00313-HOLD-DATE-CHARACTERS                           ELPARSE 
00880          UNTIL CONTROL-RECORD-CHARS (WS-CHAR-IDX) = '/'           ELPARSE 
00881                  OR    WS-SIX-IDX > 7                             ELPARSE 
00882                  OR    NOT ERROR-FREE.                            ELPARSE 
00883      IF WS-SIX-IDX  NOT  =  7                                     ELPARSE 
00884          PERFORM 00318-SIGNAL-EFFECTIVE-DATE-IN                   ELPARSE 
00885      ELSE IF ERROR-FREE                                           ELPARSE 
00886          PERFORM 00242-INSERT-VALID-EFFECTIVE-D.                  ELPARSE 
00887      IF ERROR-FREE                                                ELPARSE 
00888          PERFORM 00244-CHECK-FOR-END-OF-RECORDX.                  ELPARSE 
00889      EJECT                                                        ELPARSE 
00890                                                                   ELPARSE 
00891                                                                   ELPARSE 
00892 ************************************************************      ELPARSE 
00893 *                                                          *      ELPARSE 
00894 *        HOLD DATE CHARACTERS                              *      ELPARSE 
00895 *                                                          *      ELPARSE 
00896 ************************************************************      ELPARSE 
00897  00313-HOLD-DATE-CHARACTERS.                                      ELPARSE 
00898      IF CONTROL-RECORD-CHARS (WS-CHAR-IDX) IS NUMERIC             ELPARSE 
00899          PERFORM 00178-STORE-CHARACTER-FOR-SIXX                   ELPARSE 
00900      ELSE IF EXTRACTING-EFF-DATE                                  ELPARSE 
00901          PERFORM 00318-SIGNAL-EFFECTIVE-DATE-IN                   ELPARSE 
00902      ELSE IF EXTRACTING-TERMN-DATE                                ELPARSE 
00903          PERFORM 00384-SIGNAL-TERMINATION-DATEX.                  ELPARSE 
00904      PERFORM 00171-INCREMENT-CHARACTER-INDE.                      ELPARSE 
00905                                                                   ELPARSE 
00906                                                                   ELPARSE 
00907 ************************************************************      ELPARSE 
00908 *                                                          *      ELPARSE 
00909 *        SIGNAL EFFECTIVE DATE INVALID                     *      ELPARSE 
00910 *                                                          *      ELPARSE 
00911 ************************************************************      ELPARSE 
00912  00318-SIGNAL-EFFECTIVE-DATE-IN.                                  ELPARSE 
00913      SET EFF-DATE-INVALID        TO TRUE.                         ELPARSE 
00914      EJECT                                                        ELPARSE 
00915                                                                   ELPARSE 
00916                                                                   ELPARSE 
00917 ************************************************************      ELPARSE 
00918 *                                                          *      ELPARSE 
00919 *        EXTRACT TERMINATION DATE                          *      ELPARSE 
00920 *                                                          *      ELPARSE 
00921 ************************************************************      ELPARSE 
00922  00320-EXTRACT-TERMINATION-DATE.                                  ELPARSE 
00923      SET EXTRACTING-TERMN-DATE  TO  TRUE.                         ELPARSE 
00924      SET  WS-SIX-IDX           TO 1.                              ELPARSE 
00925      MOVE SPACES               TO WS-SIX-CHARS-FIELD.             ELPARSE 
00926      PERFORM 00313-HOLD-DATE-CHARACTERS                           ELPARSE 
00927          UNTIL CONTROL-RECORD-CHARS (WS-CHAR-IDX) = '/'           ELPARSE 
00928                  OR    WS-SIX-IDX > 7                             ELPARSE 
00929                  OR    NOT ERROR-FREE.                            ELPARSE 
00930      IF WS-SIX-IDX  NOT  =  7                                     ELPARSE 
00931          PERFORM 00384-SIGNAL-TERMINATION-DATEX                   ELPARSE 
00932      ELSE IF ERROR-FREE                                           ELPARSE 
00933          PERFORM 00328-INSERT-VALID-TERMINATION.                  ELPARSE 
00934      IF ERROR-FREE                                                ELPARSE 
00935          PERFORM 00244-CHECK-FOR-END-OF-RECORDX.                  ELPARSE 
00936                                                                   ELPARSE 
00937                                                                   ELPARSE 
00938 ************************************************************      ELPARSE 
00939 *                                                          *      ELPARSE 
00940 *        INSERT VALID TERMINATION DATE                     *      ELPARSE 
00941 *                                                          *      ELPARSE 
00942 ************************************************************      ELPARSE 
00943  00328-INSERT-VALID-TERMINATION.                                  ELPARSE 
00944      MOVE WS-SIX-CHARS-FIELD     TO CR-TERMINATION-DATE.          ELPARSE 
00945      EJECT                                                        ELPARSE 
00946                                                                   ELPARSE 
00947                                                                   ELPARSE 
00948 ************************************************************      ELPARSE 
00949 *                                                          *      ELPARSE 
00950 *        EXTRACT ALL MESSAGE POINTERS GIVEN                *      ELPARSE 
00951 *                                                          *      ELPARSE 
00952 ************************************************************      ELPARSE 
00953  00330-EXTRACT-ALL-MESSAGE-POIN.                                  ELPARSE 
00954      MOVE ZEROS                 TO CR-NUMBER-OF-MESSAGES.         ELPARSE 
00955      PERFORM 00171-INCREMENT-CHARACTER-INDE.                      ELPARSE 
00956      PERFORM 00334-VALIDATE-ALL-MESSAGES-UN                       ELPARSE 
00957          UNTIL STOP-PROCESSING                                    ELPARSE 
00958                  OR    NOT ERROR-FREE                             ELPARSE 
00959                  OR    CR-NUMBER-OF-MESSAGES > 20.                ELPARSE 
00960      EJECT                                                        ELPARSE 
00961                                                                   ELPARSE 
00962                                                                   ELPARSE 
00963 ************************************************************      ELPARSE 
00964 *                                                          *      ELPARSE 
00965 *        VALIDATE ALL MESSAGES UNTIL END OF CONTROL RECORD *      ELPARSE 
00966 *                                                          *      ELPARSE 
00967 ************************************************************      ELPARSE 
00968  00334-VALIDATE-ALL-MESSAGES-UN.                                  ELPARSE 
00969      SET WS-PTR-IDX               TO 1.                           ELPARSE 
00970      MOVE SPACES                  TO WS-MESSAGE-PTR.              ELPARSE 
00971      IF CHANGE-FUNCTION                                           ELPARSE 
00972          PERFORM 00343-VALIDATE-MESSAGE-ACTIONX.                  ELPARSE 
00973      PERFORM 00358-HOLD-CHARACTERS-FOR-MESS                       ELPARSE 
00974          UNTIL CONTROL-RECORD-CHARS (WS-CHAR-IDX) = 'X' OR        ELPARSE 
00975              ',' OR SPACE                                         ELPARSE 
00976                  OR    WS-PTR-IDX > 6                             ELPARSE 
00977                  OR    NOT ERROR-FREE.                            ELPARSE 
00978      IF WS-PTR-IDX > 6                                            ELPARSE 
00979          PERFORM 00076-SIGNAL-MESSAGE-POINTER-I                   ELPARSE 
00980      ELSE IF CONTROL-RECORD-CHARS (WS-CHAR-IDX) = 'X'             ELPARSE 
00981                 AND ERROR-FREE                                    ELPARSE 
00982          PERFORM 00361-DETERMINE-IF-PROPER-USEX                   ELPARSE 
00983      ELSE IF (CONTROL-RECORD-CHARS (WS-CHAR-IDX) = ',' OR         ELPARSE 
00984          SPACE)                                                   ELPARSE 
00985                  AND ERROR-FREE                                   ELPARSE 
00986          PERFORM 00078-INSERT-VALID-MESSAGE-POI.                  ELPARSE 
00987      PERFORM 00171-INCREMENT-CHARACTER-INDE.                      ELPARSE 
00988      EJECT                                                        ELPARSE 
00989                                                                   ELPARSE 
00990                                                                   ELPARSE 
00991 ************************************************************      ELPARSE 
00992 *                                                          *      ELPARSE 
00993 *        VALIDATE MESSAGE ACTION FOR CHANGE TRANSACTION    *      ELPARSE 
00994 *                                                          *      ELPARSE 
00995 ************************************************************      ELPARSE 
00996  00343-VALIDATE-MESSAGE-ACTIONX.                                  ELPARSE 
00997 ******************************************************************ELPARSE 
00998 ** FOR CHANGING A GROUP OR CONTRACT THE USER HAS THE ABILITY    **ELPARSE 
00999 ** TO INDICATE WHETHER TO ADD A POINTER BY PUTTING A '+' BEFORE **ELPARSE 
01000 ** THE MESSAGE NUMBER THEY WANT ADDED OR THE NUMBER ITSELF.     **ELPARSE 
01001 ** TO DELETE A MESSAGE POINTER OFF GROUP OR CONTRACT USERS MUST **ELPARSE 
01002 ** USE  A '-' TO ACCOMPLISH IT.                                 **ELPARSE 
01003 ******************************************************************ELPARSE 
01004      IF (CONTROL-RECORD-CHARS (WS-CHAR-IDX) IS NUMERIC)           ELPARSE 
01005                          OR                                       ELPARSE 
01006                 (CONTROL-RECORD-CHARS (WS-CHAR-IDX) = '-' OR      ELPARSE 
01007          '+' OR 'X')                                              ELPARSE 
01008          PERFORM 00353-HOLD-THE-MESSAGE-ACTIONX                   ELPARSE 
01009      ELSE PERFORM 00076-SIGNAL-MESSAGE-POINTER-I.                 ELPARSE 
01010                                                                   ELPARSE 
01011                                                                   ELPARSE 
01012 ************************************************************      ELPARSE 
01013 *                                                          *      ELPARSE 
01014 *        HOLD THE MESSAGE ACTION FOR POINTER               *      ELPARSE 
01015 *                                                          *      ELPARSE 
01016 ************************************************************      ELPARSE 
01017  00353-HOLD-THE-MESSAGE-ACTIONX.                                  ELPARSE 
01018      IF CONTROL-RECORD-CHARS (WS-CHAR-IDX) = '-' OR '+'           ELPARSE 
01019          PERFORM 00355-USE-THE-VALID-MESSAGE-AC.                  ELPARSE 
01020                                                                   ELPARSE 
01021                                                                   ELPARSE 
01022 ************************************************************      ELPARSE 
01023 *                                                          *      ELPARSE 
01024 *        USE THE VALID MESSAGE ACTION GIVEN                *      ELPARSE 
01025 *                                                          *      ELPARSE 
01026 ************************************************************      ELPARSE 
01027  00355-USE-THE-VALID-MESSAGE-AC.                                  ELPARSE 
01028      MOVE CONTROL-RECORD-CHARS (WS-CHAR-IDX)  TO                  ELPARSE 
01029          WS-HOLD-MSG-ACTION.                                      ELPARSE 
01030      PERFORM 00171-INCREMENT-CHARACTER-INDE.                      ELPARSE 
01031      EJECT                                                        ELPARSE 
01032                                                                   ELPARSE 
01033                                                                   ELPARSE 
01034 ************************************************************      ELPARSE 
01035 *                                                          *      ELPARSE 
01036 *        HOLD CHARACTERS FOR MESSAGE POINTER               *      ELPARSE 
01037 *                                                          *      ELPARSE 
01038 ************************************************************      ELPARSE 
01039  00358-HOLD-CHARACTERS-FOR-MESS.                                  ELPARSE 
01040      IF CONTROL-RECORD-CHARS (WS-CHAR-IDX) IS NUMERIC             ELPARSE 
01041          PERFORM 00072-STORE-MESSAGE-POINTER-CH.                  ELPARSE 
01042      PERFORM 00171-INCREMENT-CHARACTER-INDE.                      ELPARSE 
01043      EJECT                                                        ELPARSE 
01044                                                                   ELPARSE 
01045                                                                   ELPARSE 
01046 ************************************************************      ELPARSE 
01047 *                                                          *      ELPARSE 
01048 *        DETERMINE IF PROPER USE OF UNIQUE MESSAGE INDICATO*      ELPARSE 
01049 *                                                          *      ELPARSE 
01050 ************************************************************      ELPARSE 
01051  00361-DETERMINE-IF-PROPER-USEX.                                  ELPARSE 
01052      IF PROCESS-GROUP                                             ELPARSE 
01053             OR PROCESS-CONTRACT                                   ELPARSE 
01054          PERFORM 00364-USE-DEFAULT-UNIQUE-MESSA                   ELPARSE 
01055      ELSE PERFORM 00044-SIGNAL-INVALID-USE-OF-UN.                 ELPARSE 
01056                                                                   ELPARSE 
01057                                                                   ELPARSE 
01058 ************************************************************      ELPARSE 
01059 *                                                          *      ELPARSE 
01060 *        USE DEFAULT UNIQUE MESSAGE VALUE                  *      ELPARSE 
01061 *                                                          *      ELPARSE 
01062 ************************************************************      ELPARSE 
01063  00364-USE-DEFAULT-UNIQUE-MESSA.                                  ELPARSE 
01064      ADD  +1                   TO CR-NUMBER-OF-MESSAGES.          ELPARSE 
01065      MOVE WS-UNIQUE-MSG        TO                                 ELPARSE 
01066           CR-MESSAGE-POINTER (CR-NUMBER-OF-MESSAGES).             ELPARSE 
01067      MOVE WS-HOLD-MSG-ACTION   TO                                 ELPARSE 
01068           CR-MESSAGE-ACTION  (CR-NUMBER-OF-MESSAGES).             ELPARSE 
01069      SET  STOP-PROCESSING      TO TRUE.                           ELPARSE 
01070      EJECT                                                        ELPARSE 
01071                                                                   ELPARSE 
01072                                                                   ELPARSE 
01073 ************************************************************      ELPARSE 
01074 *                                                          *      ELPARSE 
01075 *        CONVERT INPUT EFFECTIVE DATE TO JULIAN            *      ELPARSE 
01076 *                                                          *      ELPARSE 
01077 ************************************************************      ELPARSE 
01078  00371-CONVERT-INPUT-EFFECTIVEX.                                  ELPARSE 
01079      MOVE CR-EFFECTIVE-DATE                    TO GREG-DATE.      ELPARSE 
01080      CALL 'TSGJULN' USING JULIAN-DATE, GREG-DATE.                 ELPARSE 
01081      IF JULIAN-DATE = ZEROS                                       ELPARSE 
01082          PERFORM 00318-SIGNAL-EFFECTIVE-DATE-IN                   ELPARSE 
01083      SKIP1                                                        ELPARSE 
01084 *                                                          *      ELPARSE 
01085 *        INSERT VALID JULIAN EFFECTIVE DATE                *      ELPARSE 
01086 *                                                          *      ELPARSE 
01087      ELSE                                                         ELPARSE 
01088          MOVE JULIAN-DATE                          TO             ELPARSE 
01089           CR-JULIAN-EFFECTIVE-DATE.                               ELPARSE 
01090      SKIP1                                                        ELPARSE 
01091      EJECT                                                        ELPARSE 
01092                                                                   ELPARSE 
01093                                                                   ELPARSE 
01094 ************************************************************      ELPARSE 
01095 *                                                          *      ELPARSE 
01096 *        CONVERT INPUT TERMINATION DATE TO JULIAN          *      ELPARSE 
01097 *                                                          *      ELPARSE 
01098 ************************************************************      ELPARSE 
01099  00379-CONVERT-INPUT-TERMINATIO.                                  ELPARSE 
01100      MOVE CR-TERMINATION-DATE       TO GREG-DATE.                 ELPARSE 
01101      CALL 'TSGJULN' USING JULIAN-DATE, GREG-DATE.                 ELPARSE 
01102      IF JULIAN-DATE = ZEROS                                       ELPARSE 
01103          PERFORM 00384-SIGNAL-TERMINATION-DATEX                   ELPARSE 
01104      SKIP1                                                        ELPARSE 
01105 *                                                          *      ELPARSE 
01106 *        INSERT VALID JULIAN TERMINATION DATE              *      ELPARSE 
01107 *                                                          *      ELPARSE 
01108      ELSE                                                         ELPARSE 
01109          MOVE JULIAN-DATE               TO                        ELPARSE 
01110              CR-JULIAN-TERMINATION-DATE.                          ELPARSE 
01111      SKIP1                                                        ELPARSE 
01112                                                                   ELPARSE 
01113                                                                   ELPARSE 
01114 ************************************************************      ELPARSE 
01115 *                                                          *      ELPARSE 
01116 *        SIGNAL TERMINATION DATE INVALID                   *      ELPARSE 
01117 *                                                          *      ELPARSE 
01118 ************************************************************      ELPARSE 
01119  00384-SIGNAL-TERMINATION-DATEX.                                  ELPARSE 
01120      SET  TERM-DATE-INVALID         TO TRUE.                      ELPARSE 
01121      EJECT                                                        ELPARSE 
01122                                                                   ELPARSE 
01123                                                                   ELPARSE 
01124 ************************************************************      ELPARSE 
01125 *                                                          *      ELPARSE 
01126 *        USE DEFAULT TERMINATION DATE                      *      ELPARSE 
01127 *                                                          *      ELPARSE 
01128 ************************************************************      ELPARSE 
01129  00388-USE-DEFAULT-TERMINATIONX.                                  ELPARSE 
01130      MOVE '123199'                  TO CR-TERMINATION-DATE.       ELPARSE 
01131      MOVE  +99365                   TO                            ELPARSE 
01132          CR-JULIAN-TERMINATION-DATE.                              ELPARSE 
01133      EJECT                                                        ELPARSE 
01134                                                                   ELPARSE 
01135                                                                   ELPARSE 
01136 ************************************************************      ELPARSE 
01137 *                                                          *      ELPARSE 
01138 *        SORT MESSAGE POINTERS IN ASCENDING ORDER          *      ELPARSE 
01139 *                                                          *      ELPARSE 
01140 ************************************************************      ELPARSE 
01141  00391-SORT-MESSAGE-POINTERS-IN.                                  ELPARSE 
01142 ******************************************************            ELPARSE 
01143 ** THIS WILL SORT ALL POINTERS ENTERED IN ASCENDING **            ELPARSE 
01144 ** ORDER TO SIMPLY THE PROCESSING MAINLINE MUST DO. **            ELPARSE 
01145 ******************************************************            ELPARSE 
01146      PERFORM 00399-INSERT-ALL-POINTERS-INTO                       ELPARSE 
01147          VARYING CR-MSG-IDX FROM 1 BY 1                           ELPARSE 
01148                  UNTIL   CR-MSG-IDX > CR-NUMBER-OF-MESSAGES.      ELPARSE 
01149      PERFORM 00402-COMPARE-FOR-ASCEND-ORDER                       ELPARSE 
01150          VARYING J FROM 2 BY 1                                    ELPARSE 
01151                  UNTIL   J > CR-NUMBER-OF-MESSAGES.               ELPARSE 
01152      PERFORM 00410-INSERT-SORTED-POINTERS-B                       ELPARSE 
01153          VARYING CR-MSG-IDX FROM 1 BY 1                           ELPARSE 
01154                  UNTIL   CR-MSG-IDX > CR-NUMBER-OF-MESSAGES.      ELPARSE 
01155                                                                   ELPARSE 
01156                                                                   ELPARSE 
01157 ************************************************************      ELPARSE 
01158 *                                                          *      ELPARSE 
01159 *        INSERT ALL POINTERS INTO SORT TABLE               *      ELPARSE 
01160 *                                                          *      ELPARSE 
01161 ************************************************************      ELPARSE 
01162  00399-INSERT-ALL-POINTERS-INTO.                                  ELPARSE 
01163      MOVE CR-MESSAGE-POINTER (CR-MSG-IDX) TO WS-MSG-PTR           ELPARSE 
01164          (CR-MSG-IDX).                                            ELPARSE 
01165      MOVE CR-MESSAGE-ACTION  (CR-MSG-IDX) TO WS-MSG-ACTION        ELPARSE 
01166          (CR-MSG-IDX).                                            ELPARSE 
01167                                                                   ELPARSE 
01168                                                                   ELPARSE 
01169 ************************************************************      ELPARSE 
01170 *                                                          *      ELPARSE 
01171 *        COMPARE FOR ASCEND ORDER                          *      ELPARSE 
01172 *                                                          *      ELPARSE 
01173 ************************************************************      ELPARSE 
01174  00402-COMPARE-FOR-ASCEND-ORDER.                                  ELPARSE 
01175      IF SORT-KEY (J - 1) NOT <                                    ELPARSE 
01176                 SORT-KEY (J)                                      ELPARSE 
01177          PERFORM 00404-GET-READY-FOR-ASCEND-SWA.                  ELPARSE 
01178                                                                   ELPARSE 
01179                                                                   ELPARSE 
01180 ************************************************************      ELPARSE 
01181 *                                                          *      ELPARSE 
01182 *        GET READY FOR ASCEND SWAP                         *      ELPARSE 
01183 *                                                          *      ELPARSE 
01184 ************************************************************      ELPARSE 
01185  00404-GET-READY-FOR-ASCEND-SWA.                                  ELPARSE 
01186      PERFORM 00406-SWAP-ENTRIES-AROUND                            ELPARSE 
01187          VARYING K FROM J BY -1                                   ELPARSE 
01188                  UNTIL   K = 1                                    ELPARSE 
01189                  OR      SORT-KEY (K - 1) NOT >                   ELPARSE 
01190                          SORT-KEY (K).                            ELPARSE 
01191      EJECT                                                        ELPARSE 
01192                                                                   ELPARSE 
01193                                                                   ELPARSE 
01194 ************************************************************      ELPARSE 
01195 *                                                          *      ELPARSE 
01196 *        SWAP ENTRIES AROUND                               *      ELPARSE 
01197 *                                                          *      ELPARSE 
01198 ************************************************************      ELPARSE 
01199  00406-SWAP-ENTRIES-AROUND.                                       ELPARSE 
01200      MOVE SORT-ITEM (K)                        TO SORT-WORK.      ELPARSE 
01201      MOVE SORT-ITEM (K - 1)                    TO SORT-ITEM       ELPARSE 
01202          (K).                                                     ELPARSE 
01203      MOVE SORT-WORK                            TO SORT-ITEM       ELPARSE 
01204          (K - 1).                                                 ELPARSE 
01205      EJECT                                                        ELPARSE 
01206                                                                   ELPARSE 
01207                                                                   ELPARSE 
01208 ************************************************************      ELPARSE 
01209 *                                                          *      ELPARSE 
01210 *        INSERT SORTED POINTERS BACK TO CONTROL RECORD     *      ELPARSE 
01211 *                                                          *      ELPARSE 
01212 ************************************************************      ELPARSE 
01213  00410-INSERT-SORTED-POINTERS-B.                                  ELPARSE 
01214      MOVE WS-MSG-PTR    (CR-MSG-IDX) TO CR-MESSAGE-POINTER        ELPARSE 
01215          (CR-MSG-IDX).                                            ELPARSE 
01216      MOVE WS-MSG-ACTION (CR-MSG-IDX) TO CR-MESSAGE-ACTION         ELPARSE 
01217          (CR-MSG-IDX).                                            ELPARSE 
